onnx/onnx

docs/Operators.md, onnx/defs/nn/defs.cc
GlobalMaxPooll -> GlobalMaxPool
=> fixed typo in Operators.md

README.md
The docker image with GPU support is added, and nvidia-docker is necessary to run CUDA code.
=> Add GPU support docker image description

onnx/numpy_helper.py
We want to do the py3 style absolute import
=> Fix imports in numpy_helper

README.md
Clean up automatically when the contain exits.
=> Add cleanup option to the docker run commands

docs/Operators.md, onnx/defs/experiments/defs.cc, onnx/defs/generator/defs.cc
Move constant from experiment, constant is needed network parameters.
=> Move constant from experiment to core.

onnx/helper.py
also fixes the bug of using plural "graph" field to store singular GraphProto value
=> Add support for making attribute with TensorProto as value

onnx/helper.py
=> Make printable_graph more deterministic across Python versions.

onnx/backend/test.py, onnx/backend/test_util.py, setup.cfg
=> Create backend test

onnx/backend/test.py
https://travis-ci.org/onnx/onnx-caffe2/jobs/278346399#L1998
=> Fix np.load failure in python3 when loading numerical data serialized in python2

.gitignore
=> Ignore autogenerated version.py file.

README.md
Move the docker images to the onnx organization account.
=> Update the onnx-docker repository

onnx/onnx.proto
Trailing spaces in onnx.proto look ugly in my editor... I prefer to remove them...
=> Remove trailing space in onnx.proto

conda/meta.yaml
=> Bump conda meta.yaml

onnx/backend/test_rnn.py
=> Python 3 compatibility fix

.travis/build.sh
=> Check whether autogen files are up-to-date

onnx/backend/test.py, onnx/helper.py, onnx/mapping.py
Fix some bugs.
Add a little bit hack to store the module name.
=> Fix some bugs in onnx, and lint the code a bit

docs/Versioning.md
=> Minor formatting improvements to Versioning.md

docs/Operators.md, onnx/cpp2py_export.cc, onnx/defs/experiments/defs.cc, onnx/defs/gen_doc.py, onnx/defs/schema.cc, onnx/defs/schema.h, onnx/defs/tensor/defs.cc, onnx/test/checker_test.py
Addresses #151 
We still have flexible stuff around NumInputs with arbitrary c function. It seems it's not used that much so we can probably clean up it separately. For now optional inputs are introduced as a separate concept.
=> Optional inputs, schema validation and docs prettification

.clang-format
I don't have strong preference on each individual rule, feel free to comment and make changes.
=> Add clang-format rules file

README.md, appveyor.yml, setup.py
Note that this badge isn't correct.
=> Add support for AppVeyor - Windows CI

docs/Operators.md, onnx/cpp2py_export.cc, onnx/defs/experiments/defs.cc, onnx/defs/gen_doc.py, onnx/defs/schema.cc, onnx/defs/schema.h
This is basically a following-up PR to resolve comments in my last PR that I have resolved. Thank you very much! For using "assert", I'll deal with it in a separate PR later. btw, looks like there're changes due to I run clang-format for each file I touched.
=> Correct input/output type for constantfill, change std::tuple to short struct, etc

onnx/tools/net_drawer.py
Borrowed most of this from caffe2. This allows us to easily visualize an ONNX net using graphviz
=> A net drawer for ONNX

docs/Operators.md, onnx/defs/experiments/defs.cc
Those are experimental OPs not ready to be put in core ONNX.
=> Add experimental OPs.

onnx/defs/data_type_utils.cc, onnx/onnx-ml.proto, onnx/onnx-ml.proto3, onnx/onnx.in.proto, onnx/onnx.proto, onnx/onnx.proto3
Fixes https://github.com/onnx/onnx/issues/78
=> Rename TypeProto nested messages

docs/Operators.md, onnx/defs/experiments/defs.cc, onnx/defs/nn/defs.cc
Based on feedbacks I am separate this change from the split change which is BC breaking. So this one shouldn't be a breaking change.
=> Promote LpNormalization from experiment.

docs/Operators.md, onnx/defs/experiments/defs.cc
=> Add an upsample2d operator as experimental

onnx/tools/net_drawer.py
This allows us to have an interactive svg export where you can click on an op to see the stack trace
=> Update net_drawer to include docstring

docs/Operators.md, onnx/defs/nn/defs.cc, onnx/defs/tensor/defs.cc
Update pads pattern on all OPs to match what we discussed.
=> Fix padding mess.

docs/Operators.md, onnx/defs/nn/defs.cc
Any variable that represents a weight tensor will utilize the name “W”
=> op signature consistency - weight input name

docs/Implementing an ONNX backend.md
=> Revised Implementing an ONNX backend.md

onnx/__init__.py, onnx/test/basic_test.py
1) Add onnx.load_from_string function.
2) Add related unit tests
=> Add onnx.load_from_string and related tests

docs/IR.md
=> Revised IR.md

docs/IR.md
Minor additions to the IR.md file.
=> Updates to IR.md

docs/Overview.md
=> Revised Overview.md

setup.py
https://github.com/pypa/setuptools/commit/f012485e4767f3be81493c93ad534a02c6f14f14
=> Use list for *requires

docs/Operators.md, onnx/defs/tensor/defs.cc
The doc string needs to be updated too
=> update pads example

docs/Operators.md, onnx/defs/experiments/defs.cc
Input is 4-D tensor, NCHW.
Two modes: nearest, bilinear.
=> Change ResizeNearest op to Upsample op

docs/IR.md
Dropped reference to control inputs. Changed reference to float32/float64 to float/double. Added reference to versioning document.
=> Minor tweaks to IR.md

README.md
Used to show the latest build, which can come from PR
=> Fix Windows build status badge to show master branch

onnx/backend/test/runner/__init__.py, onnx/backend/test_rnn.py, onnx/test/test_backend_test.py
~~The tests themselves actually fail right now for 2 reasons:~~
~~1) renamed SpatialBN -> BatchNorm~~
~~2) LRN loosing it's second parameter~~
=> Add dummy backend test to run checker on all model and node tests

README.md
Maybe "nicer" than @ezyang's personal channel, now that [it's available](https://github.com/conda-forge/onnx-feedstock).
=> switch instructions to conda-forge onnx

onnx/backend/test/runner/__init__.py
=> Fix wrong failed download message in Backend Test

onnx/cpp2py_export.cc, onnx/defs/__init__.py, onnx/helper.py
=> Add onnx_opset_version and have make_model default to it.

docs/Changelog.md, docs/Operators.md, onnx/defs/reduction/defs.cc
Thank you very much @gramalingam for catching this!
=> fix argmin/argmax output type to int32

docs/Versioning.md
=> Revised Versioning.md

docs/CONTRIBUTING.md
- Minor changes (voice, some typos)
=> Revised CONTRIBUTING.md

docs/Installation.md
=> Revised Installation.md

docs/Changelog.md, docs/Operators.md, onnx/defs/schema.cc
update min number of inputs/outputs to contain optional inputs/outputs which are not trailing ones.
=> update logic to calculate min number of inputs/outputs

setup.py, tools/ninja_builder.py
=> Port back Zach's improvements to Ninja script.

docs/Changelog-ml.md, docs/Operators-ml.md, onnx/defs/traditionalml/defs.cc
Update ML operator dictvectorizer input/output types.
=> update dictvectorizer input/output types.

docs/Changelog.md, docs/Operators.md, onnx/defs/experiments/defs.cc
Using variadic input and output.
=> Update the def of ATen op

onnx/cpp2py_export.cc, onnx/defs/experiments/defs.cc, onnx/defs/generator/defs.cc, onnx/defs/logical/defs.cc, onnx/defs/math/defs.cc, onnx/defs/nn/defs.cc, onnx/defs/nn/old.cc, onnx/defs/reduction/defs.cc, onnx/defs/rnn/defs.cc, onnx/defs/schema.cc, onnx/defs/schema.h, onnx/defs/tensor/defs.cc, onnx/defs/tensor/old.cc, onnx/defs/traditionalml/defs.cc
Remove the OpSchema::AttrType, which is kind of dup thing of AttributeType in AttributeProto.
=> remove OpSchema::AttrType and reuse the AttributeProto::AttributeType.

docs/Implementing an ONNX backend.md
Files were renamed in the onnx-tensorflow repo, updating link.
=> Implementing backend docs - fix broken link

docs/Changelog-ml.md, docs/Changelog.md, docs/Operators-ml.md, docs/Operators.md, onnx/backend/test/loader/__init__.py, onnx/defs/math/defs.cc, onnx/defs/nn/defs.cc, onnx/defs/nn/old.cc, onnx/defs/reduction/defs.cc, onnx/defs/schema.cc, onnx/defs/schema.h, onnx/defs/tensor/defs.cc, onnx/defs/tensor/old.cc, onnx/defs/traditionalml/defs.cc, tools/ninja_builder.py
Mainly fix some building issues and typos.
=> Changes done internally at Facebook

docs/Changelog-ml.md, docs/Operators-ml.md, onnx/defs/traditionalml/defs.cc
don't update the version as we're now still using latest version. Signed-off by Ke Zhang.
=> update ml op definition

docs/IR.md
Updates to IR.md to clarify types of values and the requirement of types for inputs and outputs of graph.
=> minor updates to IR documentation

docs/Changelog.md, docs/Operators.md, onnx/defs/rnn/defs.cc, onnx/defs/rnn/old.cc, onnx/defs/tensor/defs.cc
this adds an option to match the semantics of cudnn
=> add linear_before_reset attribute to GRU

docs/Versioning.md
This PR modifies the operator versioning guidance to permit not revising the version number when there are BC-compatible changes, and defines BC-compatibility to mean that all old operator specifications remain valid with exactly the same semantics.
This specification update affects PRs #397 and #407; I've CC'ed the authors of these PRs since these changes directly affect you. I also CC'ed @linkerzhang and @donbox.
=> Revise versioning w.r.t to #409

onnx/helper.py, onnx/test/helper_test.py
=> Fix a bug in making ValueInfoProto for scalar values

README.md
Let's have more contribution from the community.
=> Add low-hanging fruit list to README.md

docs/Changelog.md, docs/Operators.md, onnx/defs/tensor/defs.cc
1. Remove caffe2 specific description.
2. Turn `to` attribute to be required.
=> Fix schema of Cast

docs/Changelog.md, docs/Operators.md, onnx/defs/generator/defs.cc
Add default value for optional parameters of random generators:
RandomUniform, RandomNormal, RandomUniformLike, RandomNormalLike.
=> Add default value for optional parameters of random generators

onnx/defs/schema.h
In 092907c8b8fc531621749bfe8dfc5593e247a8cf (@anderspapitto), an updated version number was added, but the corresponding bound in DomainToVersionRange was not updated. All of us missed this in CR, and when that happens, you know it's time for some machine checking.
This PR fixes the version range, and it also adds a test which will fail if you forget to bump the version range.
=> Fix missed version bump, and add test that versions are in range.

onnx/optimizer/passes/eliminate_nop_transpose.h
We should put more tests on optimizer.
=> Fix a bug in EliminateNopTranspose

onnx/test/optimizer_test.py
=> Add tests for optimizer

onnx/common/array_ref.h, onnx/common/assertions.cc, onnx/common/assertions.h, onnx/common/graph_node_list.h, onnx/common/interned_strings.cc, onnx/common/interned_strings.h, onnx/common/ir.h, onnx/common/ir_pb_converter.cc, onnx/common/ir_pb_converter.h, onnx/common/tensor.h, onnx/optimizer.py, onnx/optimizer/optimize.cc, onnx/optimizer/optimize.h, onnx/optimizer/passes/eliminate_nop_transpose.h, onnx/optimizer/passes/fuse_consecutive_transposes.h, onnx/optimizer/passes/fuse_transpose_into_gemm.h, onnx/optimizer/passes/optimize_pass.h, onnx/optimizer/passes/split.h
Add comments which explicitly tell users that the contents in these files are experimental, and we may change them soon.
=> Mark IR and optimizer related files as experimental

onnx/optimizer/passes/optimize_pass.h
we compile internally with Werror and Wall
=> Fix warning on onnx-optimize

onnx/checker.cc, onnx/checker.h, onnx/cpp2py_export.cc
To facilitate ops with nested graph attributes, such as in https://github.com/onnx/onnx/pull/436
=> Lexical scoping in checker

onnx/helper.py
Example: 
```
node {
output: "a"
op_type: "Constant"
attribute {
name: "value"
t {
data_type: INT32
int32_data: 3
name: "three"
}
type: TENSOR
}
}
node {
output: "b"
op_type: "Constant"
attribute {
name: "value"
t {
data_type: INT32
int32_data: 6
name: "three"
}
type: TENSOR
}
}
node {
output: "keepgoing"
op_type: "Constant"
attribute {
name: "value"
t {
data_type: BOOL
int32_data: 1
name: "three"
}
type: TENSOR
}
}
node {
output: "max_trip_count"
op_type: "Constant"
attribute {
name: "value"
t {
data_type: INT32
int32_data: 10
name: "three"
}
type: TENSOR
}
}
node {
input: "max_trip_count"
input: "b"
input: "keepgoing"
op_type: "DoWhile"
attribute {
name: "body"
g {
node {
input: "a"
input: "b"
output: "my_local"
op_type: "Add"
}
node {
input: "a"
input: "b"
output: "b_out"
op_type: …
```
=> Printable Graph support for nested graphs + sugar

onnx/onnx_pb.h
Copying more stuff from https://github.com/caffe2/caffe2/blob/master/caffe2/core/common.h
=> Fix build on mac

onnx/defs/controlflow/defs.cc, onnx/defs/experiments/defs.cc, onnx/defs/generator/defs.cc, onnx/defs/logical/defs.cc, onnx/defs/math/defs.cc, onnx/defs/nn/defs.cc, onnx/defs/nn/old.cc, onnx/defs/reduction/defs.cc, onnx/defs/rnn/defs.cc, onnx/defs/rnn/old.cc, onnx/defs/schema.h, onnx/defs/tensor/defs.cc, onnx/defs/tensor/old.cc, onnx/defs/traditionalml/defs.cc
To avoid conflict with other frameworks
=> Rename schema registration macros to be onnx specific

docs/Changelog.md, docs/Operators.md, onnx/defs/tensor/defs.cc, onnx/optimizer/passes/eliminate_nop_transpose.h, onnx/optimizer/passes/fuse_consecutive_transposes.h, onnx/test/optimizer_test.py
1) Fix the doc
2) Fix the optimizer
3) Add some tests
=> Check whether perm exists before using it

onnx/common/ir_pb_converter.cc, onnx/optimizer.py, onnx/optimizer/optimize.h, onnx/optimizer/passes/nop.h, onnx/test/optimizer_test.py
in particular, we'll need this so that we can actually store inferred
shapes without them vanishing
=> preserve value infos if they are needed

.travis.yml
it's broken currently, remove it while investigating
=> temporarily disable python3 on osx for travis

onnx/helper.py
`onnx_attr` and `onnx_arg` doesn't exist.
=> fix `get_attribute_value` can not get `g` field bug

docs/Changelog.md, docs/Operators.md, onnx/defs/math/defs.cc, onnx/defs/math/old.cc
https://github.com/onnx/onnx/issues/531
=> Fix Gemm doc wording

onnx/__init__.py, onnx/test/basic_test.py
Save model function and related test.
=> Add model save function

onnx/onnx-ml.proto, onnx/onnx-ml.proto3, onnx/onnx.in.proto, onnx/onnx.proto, onnx/onnx.proto3
https://github.com/onnx/onnx/issues/511
=> Fix doc for initializer

onnx/helper.py, onnx/test/helper_test.py
Add support to add shape info in the model in python api
=> Add value_info support in make_graph

docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc
=> [easy] Fix an error in Conv doc

onnx/helper.py, onnx/test/helper_test.py
Fixed the problem described in the title.
=> The content of a string is doubled if it's a string tensor

onnx/cpp2py_export.cc, onnx/defs/__init__.py
=> Align schema function signatures in python and c++

.travis/before_install.sh
I think this should fix it. I'll wait for the CI run for confirmation though.
=> Fix Protobuf error message in CI

docs/Changelog.md, docs/Operators.md, onnx/defs/experiments/defs.cc
https://github.com/onnx/onnx/issues/805
=> Fix the ConstantFill spec

onnx/backend/test/case/model/__init__.py, onnx/backend/test/data/real/test_vgg16/data.json, onnx/backend/test/data/real/test_zfnet/data.json, onnx/test/backend_shape_inference_test.py, onnx/test/test_backend_test.py
=> Rename real model test case from VGG-16 to ZFNet

onnx/test/test_backend_test.py
=> disable shape inference test to unbreak ci

docs/Changelog.md, docs/Operators.md, onnx/defs/math/defs.cc
=> [super easy] Remove useless text in docs

onnx/defs/math/defs.cc, onnx/defs/shape_inference.h, onnx/test/shape_inference_test.py
=> Add some math function shape inference

onnx/defs/generator/defs.cc, onnx/defs/shape_inference.h
RandomUniform, RandomNormal. RandomUniformLike, RandomNormalLike, and Constant ops.
=> Type and shape inference for generator ops

onnx/defs/math/defs.cc, onnx/test/shape_inference_test.py
this one is relatively involved, since it requires implementing numpy
broadcasting semantics
=> shape inference for matmul

onnx/defs/math/defs.cc
straight forward uses of propagateShapeAndTypeFromFirstInput
=> inference for math ops

onnx/test/shape_inference_test.py
=> Lint the code and fix the CI

onnx/__init__.py, onnx/bin/checker.py, onnx/checker.py, onnx/defs/__init__.py, onnx/helper.py, onnx/numpy_helper.py, onnx/optimizer.py
Stacked diff. First two commits are reviewed in https://github.com/onnx/onnx/pull/911
=> [Typing 3/5] Add type hints to some top level files

onnx/defs/shape_inference.h, onnx/defs/tensor/defs.cc, onnx/helper.py, onnx/shape_inference/implementation.h, onnx/test/shape_inference_test.py
Also ensure that a value-info without any information is ignored
=> fix segfault in shape inference for concat

CMakeLists.txt
=> fix build dependency between onnx-operators.proto and onnx.proto

onnx/defs/shape_inference.h, onnx/shape_inference/implementation.h
Exception mechanism for use in type and shape inference
=> add exception mechanism for use in type and shape inference

onnx/backend/base.py, onnx/backend/test/runner/__init__.py, onnx/gen_proto.py, onnx/test/__init__.pyi, onnx/test/shape_inference_test.py, tools/gen_coverage_report.py, tools/mypy-onnx.py
A few more functions didn't have type hints, this adds them.
=> Add more missing type hints

onnx/backend/base.py
=> Support opset_version in Backend's run_node 

docs/Operators.md, onnx/defs/gen_doc.py
Otherwise we have duplicate entries for Upsample. (Older version is experimental)
=> [Easy] Fix the gen_doc.py

tools/protoc-gen-mypy.py
The upstream PRs are merged, so let's get a new upstream version so we have fewer differences to it.
=> Update from upstream

onnx/optimizer/passes/eliminate_unused_initializer.h
This breaks on fbcode CI because it shadows another variable
=> Fix for fbcode CI

docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc
Context - https://github.com/onnx/onnx/pull/903#issuecomment-395167044
=> Fix local region definition in LRN spec

onnx/optimizer/passes/extract_constant_to_initializer.h, onnx/test/optimizer_test.py
that has all graph level outputs as its outputs.
@zrphercule 
discovered by @varunjain99
=> Graph should only have one (input) kParam node

onnx/optimizer/optimize.cc
=> fix optimizer does not set ir_version bug

CMakeLists.txt
=> Add missing warning ignoring flags to onnx_proto CMake target

docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc
=> Fix the LRN's doc

.travis/script.sh, docs/TestCoverage-ml.md, docs/TestCoverage.md, onnx/backend/test/stat_coverage.py
Although right now the generated page is a little bit similar to the operator page, later more information will be added. The purpose of two pages are also quite different. So it's better to have a separate page for test coverage information instead of adding it into the existing page.
No need to run the test cases.
=> Add stats on ONNX node tests

docs/TestCoverage-ml.md, docs/TestCoverage.md, onnx/backend/test/stat_coverage.py
=> Exclude Random Generator from Test Coverage Stat

CMakeLists.txt, onnx/onnxifi_loader.c, onnx/onnxifi_loader.h
to be consistent with other files in the onnx repo
=> Change include style for onnxifi

README.md
I run into issues while trying to build onnx from source because I did not checkout the submodules.
=> Update build from source instructions in README

docs/Changelog.md, docs/Operators.md, onnx/defs/math/defs.cc, onnx/defs/math/old.cc
Add the default value for `alpha` and `beta`
=> Fix the Spec for Gemm

onnx/common/assertions.cc, onnx/common/assertions.h, onnx/common/tensor.h, onnx/defs/schema.cc
- Address https://github.com/onnx/onnx/issues/1140
- Unify the assertion and error handling
=> Use ONNX_ASSERT(M) instead of throwing exception

onnx/onnxifi.h
As agreed per discussion with WinML
=> Clarify uniqueness of backend ID for the life-time of the process

onnx/onnxifi.h
As per discussion with WinML, clarify behavior of onnxSetGraphIO w.r.t. in-flight graph executions
=> Clarify behaviour of onnxSetGraphIO w.r.t in-flight graph executions

onnx/common/ir.h, onnx/string_utils.h
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-android-ubuntu16.04-build/12188/console
=> backports stoi on android

onnx/version_converter/convert.cc
Should resolve issue with static references to OpSchemaRegistry as detected by @bddppq in debug tests
=> Fixed static reference issue with _version_converter

onnx/defs/tensor/defs.cc
=> Fix the usage of std::to_string

onnx/onnxifi_dummy.c, onnx/test/cpp/onnxifi_backend_test.cc
=> clang-format for onnxifi dummy backend code

onnx/test/version_converter_test.py, onnx/version_converter/convert.h
Specifically for Add from Version 5 to Version 8
=> Test for Version Conversion Adapters that Insert Unsqueeze Nodes

onnx/test/version_converter_test.py, onnx/version_converter.py, onnx/version_converter/convert.h
Relu Version Conversion Adapters
=> Relu Version Conversion Adapters

onnx/backend/test/case/node/argmax.py, onnx/backend/test/case/node/argmin.py
@snnn #1319 
test data files are already correct though
=> Arg tests output int64

onnx/optimizer.py
=> Lint the code

docs/ONNXIFI.md
Reflect changed in API before ONNXIFI 1.0
=> Update ONNXIFI documentation

onnx/onnxifi.h
Is seems plausible that several backends will support variable or data-dependent batch size, but not other shape dimensions. This PR adds capability values for such "partial" support for variable shapes. Currently, TensorRT follows this model.
=> Add capability values for variable batch size

onnx/onnxifi.h
OpenCL context is necessary to make passing OpenCL buffers in/out of ONNXIFI graph possible, as OpenCL buffers exist within a context.
=> Add init properties for CUDA stream and OpenCL context

docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc
=> fix AvgPool doc. add default value for count_include_pad

onnx/backend/test/cpp/driver/test_driver.cc, onnx/backend/test/cpp/driver/test_driver.h, onnx/backend/test/cpp/driver_test.cc, onnx/backend/test/cpp/gtest_utils.cc, onnx/backend/test/cpp/gtest_utils.h
Change the name of some classes in onnxifi test driver for better description, also added some documents.
=> Change onnxifi test driver classname

onnx/onnx-ml.proto, onnx/onnx-ml.proto3
=> refresh onnx-ml.proto

onnx/backend/test/cpp/driver_test.cc
Fix a few nits for onnxifi test driver.
=> [ONNXIFI]Fix the crash when weightCount = 0

onnx/optimizer/passes/lift_lexical_references.h
=> Fix lift_lexical_references to support nest loops in ONNXWhile

onnx/backend/test/cpp/driver_test.cc
Gtest assert only jumps out of local function, therefore we cannot put the assert_eq in another function.
=> [ONNXIFI]Fix gtest assert

tools/update_doc.sh
Integrate all the steps together.
=> Add a script to ease the work of adding new op

onnx/backend/test/case/node/pool_op_common.py, onnx/backend/test/report/__init__.py, onnx/backend/test/runner/__init__.py, onnx/defs/gen_doc.py, onnx/helper.py, onnx/numpy_helper.py, tools/protoc-gen-mypy.py
=> Fix 'line break after binary operator' flake8 warnings.

onnx/common/interned_strings.h, onnx/examples/optimize_onnx.ipynb, onnx/optimizer/pass_registry.h, onnx/optimizer/passes/fuse_consecutive_concats.h, onnx/test/optimizer_test.py
=> implement fusing of consecutive concats

onnx/checker.cc
https://github.com/onnx/onnx/issues/1577
=> handle uint8 typed field in onnx checker

onnx/checker.cc
`.clang` formatter added some things
=> Handle new types in the switch.

onnx/shape_inference/implementation.cc
Fix a bug in accessing vector element
=> Bugfix in function shape/type inference

onnx/backend/test/cpp/driver_test.cc
=> Fix onnxifi test

docs/AddNewOp.md
This PR add the instructions of adding new operators.
=> Add Doc about Adding New Operator into ONNX

onnx/optimizer/passes/fuse_pad_into_conv.h
Otherwise some compiler may complain.
=> [Easy] Lint the code and remove the warning/error

onnx/common/status.h
=> Fix unused var warning

docs/Changelog.md, docs/Operators.md, onnx/defs/experiments/defs.cc, onnx/defs/gen_doc.py, onnx/defs/operator_sets.h
Fix the documentation, per issue #1689
=> ONNX does not maintain versions for experimental ops

onnx/test/shape_inference_test.py
To improve the test coverage. Also address https://github.com/onnx/onnx/issues/1159
=> Add a shape inference test for group conv

onnx/mapping.py, onnx/numpy_helper.py, onnx/test/numpy_helper_test.py
This is a follow up for https://github.com/onnx/onnx/pull/1734
Cc: @houseroad
=> Use strings directly for casing as np.object w/o redundant StringHolder.

README.md
Add ppc64le build script files and update README to
display build status. We will start with the nightly
builds to ensure a successful build every day. If
needed, we could change and/or add more triggers for
example for each git push defined in git SCM.
We will switch Jenkins from using personal fork
to the ONNX master after reviews and approvals.
This PR addresses issue #1589.
=> Add ppc64le build

docs/Changelog.md, docs/Operators.md, onnx/defs/logical/defs.cc
fix https://github.com/onnx/onnx/issues/1775
=> Fix TypeConstraint description for Greater and Less in Opset9

docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc, onnx/defs/nn/old.cc
fix the issue that the version was not bumped when changing its type constraint declaration.
=> bump the version for dropout

onnx/backend/test/runner/__init__.py
Strings are represented as np.objects  and all other objects.
=> Handle string comparision in tests

onnx/onnx-operators.in.proto, onnx/onnx-operators.proto, onnx/onnx-operators.proto3
To fix https://github.com/onnx/onnx/issues/1840
=> Fix the ir_version in onnx-operators.proto

docs/Changelog.md, docs/Operators.md, onnx/defs/tensor/defs.cc
fix https://github.com/onnx/onnx/issues/1755
=> Update the squeeze and unsqueeze doc

community/working-groups.md, onnx/defs/math/defs.cc, onnx/defs/nn/defs.cc, onnx/test/shape_inference_test.py
* Adding shape inference tests for quantized ops 
* Bug fix for QLinearConv shape inference
* Adding more checks for QLinearConv and QLinearMatMul type inference
=> Shape Inference Tests for QOps

.travis/script.sh
=> Fix the Travis CI

onnx/optimizer/passes/fuse_add_bias_into_conv.h
This addresses https://github.com/onnx/onnx/issues/2003
=> Prevent using invalid iterator, fix arithmetics.

docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc, onnx/test/shape_inference_test.py
1. Add dilations support in convtranspose shape inference
1. Update docs of MaxPool and ConvTranspose
=> Add dilations support in ConvTranspose shape inference and update docs

docs/AddNewOp.md
Clarify shape inference requirements for new operators
CC: @linkerzhang
=> Clarify shape inference requirements for new operators

docs/AddNewOp.md
Update the NewOP doc based on what we approved in the SIG operator meeting.
=> Update AddNewOP document.

docs/Changelog.md, docs/Operators.md, onnx/checker.cc, onnx/defs/logical/defs.cc, onnx/defs/logical/old.cc, onnx/defs/operator_sets.h
Equal should support all numeric types.
=> add more types support for Equal op

onnx/shape_inference/implementation.cc
A bug in onnx function's shape inference function.
=> fix a bug in func shape inference

docs/IR.md
Clarify the scoping of dimension variables further.
=> Clarify dimension variable scoping

onnx/onnx-ml.proto, onnx/onnx-ml.proto3, onnx/onnx.in.proto, onnx/onnx.proto, onnx/onnx.proto3
As title. Change TBD to the expected release date and regenerate protobuf files.
=> Regenerate ONNX proto and add release date to ver 6 IR

docs/Changelog.md, docs/Operators.md, onnx/defs/tensor/defs.cc
Made some wording changes to NonZero and Slice operators. These changes do not warrant an opset update.
=> minor changes to NonZero and Slice

onnx/optimizer/passes/fuse_consecutive_transposes.h, onnx/test/optimizer_test.py
This change fix https://github.com/onnx/onnx/issues/2446
=> fix the optimize pass of fuse_consecutive_transposes

docs/PythonAPIOverview.md
The example given in the "Creating an ONNX Model Using Helper
Functions" example.
=> Edited PythonAPIOverview.md

docs/Changelog.md, docs/Operators.md, onnx/defs/operator_sets.h, onnx/defs/reduction/defs.cc, onnx/defs/reduction/old.cc
Adding 8 bit support to reducemin and reducemax ops
=> add 8 bit support to reducemin and reducemax ops

community/repo_guidelines.md
Draft was shared on Gitter for feedback in December and approved by Steering Committee on 1/9
=> Repository guidelines

.circleci/build.sh
To match the version in https://github.com/pytorch/pytorch/pull/31835
=> Bump ORT version

onnx/common/ir_pb_converter.cc
The current error message as shown in https://github.com/onnx/onnx/issues/1385 is not informative.
=> better error message for undefined inputs

onnx/backend/test/data/node/test_min_float16/model.onnx, onnx/backend/test/data/node/test_min_float32/model.onnx, onnx/backend/test/data/node/test_min_float64/model.onnx, onnx/backend/test/data/node/test_min_int16/model.onnx, onnx/backend/test/data/node/test_min_int32/model.onnx, onnx/backend/test/data/node/test_min_int64/model.onnx, onnx/backend/test/data/node/test_min_int8/model.onnx, onnx/backend/test/data/node/test_min_uint16/model.onnx, onnx/backend/test/data/node/test_min_uint32/model.onnx, onnx/backend/test/data/node/test_min_uint64/model.onnx, onnx/backend/test/data/node/test_min_uint8/model.onnx
Related too https://github.com/onnx/onnx/pull/2640
=> Regenerate test data of Min-12

onnx/common/constants.h, onnx/defs/generator/defs.cc, onnx/defs/logical/old.cc, onnx/defs/math/old.cc, onnx/defs/nn/defs.cc, onnx/defs/nn/old.cc, onnx/defs/reduction/defs.cc, onnx/defs/reduction/old.cc, onnx/defs/rnn/defs.cc, onnx/defs/rnn/old.cc, onnx/defs/sequence/defs.cc, onnx/defs/tensor/defs.cc, onnx/defs/tensor/old.cc, onnx/defs/traditionalml/defs.cc, onnx/defs/traditionalml/old.cc, onnx/defs/training/defs.cc
=> Rename OPTIONAL to OPTIONAL_VALUE

docs/Changelog.md, docs/Operators.md, onnx/defs/tensor/defs.cc, onnx/test/shape_inference_test.py
Fix shape inference for unfold to depth.
Dimension should be = C * prod({kernel_size})
=> Fix shape inference for unfold to depth

onnx/checker.py, onnx/defs/gen_doc.py
I performed some small code refactoring. ONNX is a wonderful project. Thank you.
=> Some small refactoring

setup.py
Updates the below Author, Author-email and License in ONNX pip account.
=> Update setup info for ONNX pip account

community/sc-election-guidelines.md
original location: https://github.com/onnx/steering-committee/blob/master/election-guidelines-draft.md
=> Move election guideline doc from steering committee repo

README.md
Updating README build badges for CIs
=> Updating build badges for ONNX pipelines

README.md
=> fix label for PPC build

.azure-pipelines/MacOS-CI.yml
According to https://github.com/onnx/onnx/issues/2859, the MacOS-CI has a timeout problem.
=> Fix timeout in MacOS-CI

docs/Relicensing.md
Relicensing update on behalf of NVIDIA
=> Update relicensing list on behalf of NVIDIA

.circleci/build.sh
According to https://github.com/onnx/onnx/issues/2869, update the ort version to 1.3.1 in CircleCI.
=> Update ort version in CircleCI

docs/Relicensing.md
Add IBM to the relicensing doc after legal approval
=> Add IBM to the relicensing doc

.azure-pipelines/Linux-CI.yml
report typecheck errors in Linux CI
=> report typecheck errors in linux ci

.github/ISSUE_TEMPLATE/bug.md
Closing PR https://github.com/onnx/onnx/pull/2867 in favor of this one.
The older PR was wrongly based off a branch in onnx instead of a fork.
=> Extending issue template to add a section for converter related issues

onnx/defs/controlflow/defs.cc, onnx/defs/controlflow/old.cc
Fixes issue:  https://github.com/onnx/onnx/issues/3013
=> fix shape inference for loop

.azure-pipelines/Windows-CI.yml
Fix the conda failure
**Motivation**
Windows-CI is failing because of the conda issue as follows:
```
2020-10-07T20:39:09.0745559Z conda create --yes --quiet --name py3.7 -c conda-forge python=3.7 numpy libprotobuf=3.11.3 protobuf
2020-10-07T20:39:09.1202973Z ========================== Starting Command Output ===========================
2020-10-07T20:39:09.1455477Z ##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\978d3d2a-5bc2-4f69-8e80-b51af612d5a5.cmd""
2020-10-07T20:39:50.7955045Z Collecting package metadata: ...working... failed
2020-10-07T20:39:50.9196083Z 
2020-10-07T20:39:50.9196620Z # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
2020-10-07T20:39:50.9196849Z 
2020-10-07T20:39:50.9197070Z     Traceback (most recent call …
```
=> Fix conda-forge failure in Windows-CI

.github/workflows/release_win.yml
=> build protobuf in pipeline

onnx/test/cpp/function_context_test.cc
Add unit test for function type-context extension.
=> Function type-context unit-test

onnx/common/ir.h, onnx/common/ir_pb_converter.cc, onnx/test/optimizer_test.py
Reverts onnx/onnx#3131
Sorry that I merged this. There are still some issues.
=> Revert "update ir for subgraph and optimizer, add some const methods"

docs/Changelog.md, docs/Operators.md, onnx/defs/math/defs.cc, onnx/defs/math/old.cc, onnx/defs/operator_sets.h
* Bumps opset to ver14
* Allows all signed types to be used with Relu
See #3111 for more info
=> Allow all signed types to be used with Relu

.github/workflows/release_mac.yml, .github/workflows/release_win.yml
Should only test release-CI in release branch
**Motivation**
https://github.com/onnx/onnx/pull/3226
=> Only test release-CI in release branch

docs/Changelog.md, docs/Operators.md, onnx/defs/operator_sets.h, onnx/defs/tensor/defs.cc, onnx/defs/tensor/old.cc
=> Adding back identity opset bump for change in previous PR

onnx/defs/data_type_utils.cc
=> change assertions to throw exception

README.md, setup.py
Signed-off-by: Ewa21 <ewa.tusien@intel.com>
=> Add content of Readme to package description

README.md
Signed-off-by: Ewa21 <ewa.tusien@intel.com>
=> Fix broken link to logo image

onnx/defs/nn/defs.cc, onnx/test/shape_inference_test.py
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>
=> To signoff again: Fix Batchnorm type inference for mean and variance and add a test

README.md
We have encountered an issue where the logo image does not appear in TestPyPI. 
This PR provides a fix for the issue.
=> Fix logo url so that it leads to a raw image

onnx/onnx-ml.proto, onnx/onnx-ml.proto3, onnx/onnx.in.proto, onnx/onnx.proto, onnx/onnx.proto3
=> Remove comment about ONNX being very early stage.

onnx/examples/check_model.ipynb, onnx/examples/load_model.ipynb, onnx/examples/make_model.ipynb, onnx/examples/np_array_tensorproto.ipynb, onnx/examples/save_model.ipynb, onnx/examples/shape_inference.ipynb
I think python 2 isn't supported anymore (see onnx/sklearn-onnx#336).
=> Examples: Update to python 3

docs/PythonAPIOverview.md, onnx/examples/check_model.ipynb
Also use repo-relative links so that they'll work as expected locally or
in a branch.
=> Python API Overview: minor improvements for clarity

.github/workflows/manylinux/entrypoint.sh, .github/workflows/manylinux/test_package_i686.sh, .github/workflows/release_linux_x86_64.yml
Applying a recent bugfix from master to rel-1.9.1
Cherry pick resulted in a bnunch of merge conflicts so just decided to make the change.
=> bugfix for release pipeline

.azure-pipelines/Linux-CI.yml, .azure-pipelines/Windows-CI.yml, .github/workflows/manylinux/entrypoint.sh, .github/workflows/manylinux/test_package_i686.sh, .github/workflows/release_linux_i686.yml, .github/workflows/release_linux_x86_64.yml, .github/workflows/release_mac.yml, .github/workflows/release_win.yml, .github/workflows/weekly_mac_ci.yml, .github/workflows/win_no_exception_ci.yml, README.md
Updating the protobuf version to 3.16.0
=> update protobuf version to 3.16.0

docs/Changelog.md, docs/Operators.md, onnx/defs/math/defs.cc
Clarify spec for zero point and scale shape expectations in case of ND inputs
=> spec clarification for matmulinteger and qlinearmatmul

onnx/shape_inference/implementation.cc, onnx/shape_inference/implementation.h, onnx/test/cpp/shape_inference_test.cc
Makes symbol generation optional.
=> make symbol generation optional

MANIFEST.in, docs/OnnxReleases.md
- Include requirements.txt while producing source distribution
- Correct release document: use the right way to test uploaded source distribution.
https://github.com/onnx/onnx/issues/3621
=> Include requirements.txt in source distribution

.github/workflows/release_linux_x86_64.yml, onnx/test/hub_test.py
- Reducing LFS Usage in ONNX Hub Tests
- Requested by Jacky Chen
=> Reducing LFS Usage in ONNX Hub Tests

onnx/test/hub_test.py
Signed-off-by: Mark <mhamilton723@gmail.com>
- Changing one opset. This will fix an eventual test failure next time weekly tests are run
=> Hotfix for hub test

onnx/defs/parser.h
Signed-off-by: Ganesan Ramalingam <grama@microsoft.com>
Improve error messages produced by the parser by adding the last line source before the error location.
=> Add error context in parser error messages

onnx/test/test_backend_test.py
Signed-off-by: Alexandre Eichenberger <alexe@us.ibm.com>
Change whitelist into the more neutral safelist word 
We have been asked to remove certain terms from our code, this is the only instance that I found in the entire ONNX/ONNX repo.
No functionality was changed, just the name of a function.
=> replace whitelist by safelist

docs/CONTRIBUTING.md
Add explanation to CONTIBUTING.md about how to run cpp tests.
=> Add explanation to run gtest

onnx/backend/test/report/__init__.py
cherry pick from main branch to fix a pytest issue
=> cherry pick from the main branch to fix a pytest issue

onnx/defs/function.h
Signed-off-by: Liqun Fu <liqfu@microsoft.com>
- add FunctionBuilder.Const() api to take a tensor argument
-  that API is needed by onnx runtime
=> add FunctionBuilder.Const() api to take a tensor argument

onnx/defs/math/defs.cc
Signed-off-by: Ganesan Ramalingam <grama@microsoft.com>
Fix bug in SCE function body.
=> Fix bug in SCE function body

docs/IR.md
- Add OperatorSetId definition in IR docs.
- Fixes #1100
=> Add OperatorSetId definition in docs

.github/stale.yml
=> Add config for Stale Bot

docs/CIPipelines.md
=> typo: Update CIPipelines.md

requirements.txt
* Upgrade python syntax with pyupgrade (#4212)
Signed-off-by: Eduardo <eduardomoreno2594@gmail.com>
* Update requirements.txt
Signed-off-by: Eduardo <eduardomoreno2594@gmail.com>
* include the previous restriction as well
Signed-off-by: Eduardo <eduardomoreno2594@gmail.com>
Co-authored-by: Justin Chu <justinchuby@users.noreply.github.com>
=> Update requirements.txt (#4223)

onnx/shape_inference/implementation.cc
=> Cherry pick PR #4224

onnx/defs/schema.cc, onnx/shape_inference/implementation.cc, onnx/test/checker_test.py
=> cherry pick PR 4282 and 4283

.azure-pipelines/Linux-CI.yml, .github/workflows/lint.yaml, pyproject.toml, requirements-dev.txt, setup.cfg
- Set up configurations for black and isort. The actual formatting will be in the following pr.
- Create github action to enforce style
- Fix CI errors when having a pyproject.toml file 
- Add lint dependencies to requirements-dev 
Standardize python code format
=> Set up black and isort

.github/workflows/lint.yaml
Install ONNX before linting
#4427
=> [ci] Install ONNX before linting

.gitignore, .vscode/settings.json
Set up VS Code to format python code at save
=> Set up VS Code to format python code at save

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/operator.md, .github/ISSUE_TEMPLATE/question.md, docs/Hub.md
Update issues template and ONNX Hub doc
- Improve issues template. Similar to https://github.com/onnx/onnx/pull/4434.
- Update ONNX Hub document since it has  been officially released for quite a while.
=> Update issues template and ONNX Hub doc

.github/workflows/codeql.yml
Use GitHub code scanning before retiring deprecated LGTM.com
Closes https://github.com/onnx/onnx/issues/4468.
=> Use GitHub code scanning before retiring deprecated LGTM.com

docs/docsgen/source/tutorial_python/concepts.rst, docs/docsgen/source/tutorial_python/converters.rst
Signed-off-by: andife <fehlner@arcor.de>
=> fix spelling new python doc

docs/Changelog.md, docs/Operators.md, onnx/defs/tensor/defs.cc
Address issue https://github.com/onnx/onnx/issues/4550
=> Clarify reshape behavior

docs/docsgen/source/intro/concepts.rst, docs/docsgen/source/intro/converters.rst, docs/docsgen/source/intro/python.rst
Signed-off-by: andife <fehlner@arcor.de>
fix some spelling and grammer issues
=> fix some spelling and grammar issues

README.md
Fix one link on README.md
Better documentation.
=> Fix link to package documentation on README.md

onnx/reference/ops/_op_common_pool.py, onnx/reference/ops/op_dft.py, onnx/reference/ops/op_gather.py, onnx/reference/ops/op_gather_elements.py, onnx/reference/ops/op_scatter_elements.py, onnx/reference/ops/op_stft.py, onnx/reference/ops/op_topk.py, onnx/reference/ops/op_unsqueeze.py, onnx/test/reference_evaluator_backend_test.py
=> Fix backend test for ReferenceEvaluator with numpy 1.16.6

onnx/__init__.py
Update doc stirng for function `onnx.save_model`
The old doc string is confusing and missing documentation of one input parameter `save_as_external_data`,
=> update docs for onnx.save_model

docs/docsgen/source/intro/python.rst
Fixed typos in 6 places.
Signed-off-by: Anand Krishna <51157561+AnandKri@users.noreply.github.com>
Changed lines - 83,170,233,253,272,1006.
Some small grammatical errors were there.
=> Fixed some typos in python.rst

onnx/defs/schema.h, onnx/defs/traditionalml/defs.cc, onnx/test/shape_inference_test.py, setup.cfg
Backport of https://github.com/onnx/onnx/pull/4681
=> misc fixes for issues found in ort integration (#4681)

onnx/defs/operator_sets.h, onnx/defs/schema.h
Signed-off-by: p-wysocki <przemyslaw.wysocki@intel.com>
Release branch has been cut, new opset can be introduced. Based on https://github.com/onnx/onnx/pull/4134.
=> Bump current opset to 19

README.md, community/working-groups.md
Signed-off-by: Andreas Fehlner <fehlner@arcor.de>
release wg was integrated in arch&infra sig
=> doc: minor corrections, release wg was integrated in arch&infra sig

docs/docsgen/source/onnx_sphinx.py
=> Swap colors on operators diff in the documentation

onnx/__init__.py
Fix import submodules in the root `__init__`
@jcwchen
=> Fix import submodules

docs/docsgen/source/api/checker.rst
Fix incorrect member CheckerContext in checker API for web
Follow up of #4720. [CheckerContext](https://onnx.ai/onnx/api/checker.html#id1) does not show correctly
=> Fix incorrect member CheckerContext in checker API for web

docs/docsgen/source/api/mapping.rst
correspondance -> correspondence
=> Fix typo in mapping.rst

onnx/reference/ops/_op.py, onnx/reference/ops/op_reduce_sum.py, onnx/test/reference_evaluator_test.py
=> Fix linked_attributes in reference implementation of ReduceSum

onnx/backend/test/__init__.py, onnx/reference/ops/op_constant.py, onnx/reference/ops/op_resize.py, onnx/reference/ops/op_scatter_elements.py
Remove empty noqa directives and run autofix with ruff
Follow up of #4851
=> Remove empty noqa directives

.lintrunner.toml, docs/Operators.md, docs/TestCoverage.md, onnx/backend/test/case/node/cast.py, onnx/backend/test/case/node/castlike.py, onnx/backend/test/stat_coverage.py, onnx/gen_proto.py, onnx/helper.py, onnx/reference/ops/aionnxml/op_binarizer.py, onnx/reference/ops/op_non_max_suppression.py, onnx/reference/ops/op_upsample.py, onnx/reference/reference_evaluator.py, onnx/test/reference_evaluator_test.py, onnx/test/test_backend_test.py, pyproject.toml, setup.py
Autoformat with ruff SIM rules: https://beta.ruff.rs/docs/rules/#flake8-simplify-sim
Fixes including yoda conditions. There are some more opinionated rules I disabled.
Code quality.
cc @jcwchen @xadupre @gramalingam
=> Autoformat with ruff SIM rules

docs/IR.md
Update the documentation of default-attributes in a FunctionProto (a recently added feature).
=> Update function default-attribute documentation

docs/IR.md
Update IR.md to clarify the distinction between the two kinds of optional arguments in ONNX.
=> Update documentation of optional arguments

onnx/test/checker_test.py
=> Clean up checker_test

docs/PythonAPIOverview.md
Fix typo in Converting Version of an ONNX Model document
It imporves the PythonAPI document for ONNX
=> Fix typo in Converting Version of an ONNX Model

setup.py
Use correct package name onnx
Fix a bug brought by https://github.com/onnx/onnx/pull/4956.
=> Use correct package name onnx

docs/Versioning.md, onnx/common/version.h, onnx/defs/schema.h, onnx/helper.py, onnx/test/helper_test.py
=> v1.14.0 version update

.lintrunner.toml, .reuse/dep5, onnx/reference/ops/op_roi_align.py, onnx/reference/ops/op_string_normalizer.py, onnx/test/basic_test.py, onnx/test/reference_evaluator_backend_test.py, pyproject.toml, pyproject_pylint.toml, requirements-dev.txt, requirements-lintrunner.txt
Move requirements from lintrunner.toml to a requirements file so dependabot can update it. Also bumped versions.
Dependency control
=> Move requirements from lintrunner.toml

docs/proposals/SymbolicShapeInfProposal.md, onnx/defs/controlflow/old.cc, onnx/defs/controlflow/utils.cc, onnx/defs/data_propagators.h, onnx/defs/tensor/defs.cc, onnx/defs/tensor/old.cc
Better documentation and comments.
=> Fix misspellings related to word propagate

onnx/onnx-ml.proto, onnx/onnx-ml.proto3, onnx/onnx.in.proto, onnx/onnx.proto, onnx/onnx.proto3
There are typos in proto files. This PR fixes these typos.
=> Fix typos in proto files

docs/docsgen/source/api/helper.md
delete the repeated line
line 36 and 38
line 180-182 and 188-190
=> Remove duplicated links in helper.md

docs/docsgen/source/technical/float8.md
Modify the error number in line23
=> Modify the error number in float8.md

onnx/helper.py, onnx/numpy_helper.py, onnx/reference/ops/op_conv.py, onnx/reference/ops/op_tfidf_vectorizer.py, onnx/test/reference_evaluator_backend_test.py, onnx/test/reference_evaluator_test.py, requirements-lintrunner.txt
=> Bump ruff to 0.0.272 and fix new errors

docs/docsgen/source/api/checker.md, docs/docsgen/source/api/defs.md
Update OpSchema docs
Fixes #5292
=> Update OpSchema docs to include new methods and classes

README.md
add community day2023 confluence page link
=> add community day2023 confluence page link

onnx/backend/test/case/base.py, onnx/reference/op_run.py, onnx/reference/ops/op_non_max_suppression.py, onnx/reference/reference_evaluator.py, onnx/test/shape_inference_test.py, onnx/test/test_backend_onnxruntime.py, requirements-lintrunner.txt, setup.py
Bump ruff to v0.0.277 and fix new errors
ruff v0.0.277 introduced new checks and found lint errors we needed to fix. Replaces #5394
=> Bump ruff to v0.0.277 and fix new errors

docs/Changelog.md, docs/Operators.md, onnx/defs/tensor/defs.cc
Torch ref: https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html#torch.Tensor.scatter_
Issue: https://github.com/onnx/onnx/issues/5443
=> Fix doc of ScatterElements

onnx/checker.cc
This PR fixes build for web assembly
=> fix build for web assembly

onnx/serialization.py, onnx/test/basic_test.py
Create serializers to the `json` format and register the `json` and `onnxjson` extensions to it.
```python
import onnx
model = onnx.load_model("onnx/backend/test/data/light/light_resnet50.onnx")
onnx.save_model(model, "resnet50.json")
```
yields
```json
{
"ir_version": "3",
"producer_name": "onnx-caffe2",
"producer_version": "",
"domain": "",
"model_version": "0",
"doc_string": "",
"graph": {
"node": [
{
"input": [
"gpu_0/conv1_w_0__SHAPE"
],
"output": [
"gpu_0/conv1_w_0"
],
"op_type": "ConstantOfShape",
"attribute": [
{
"name": "value",
"t": {
"dims": [
"1"
],
"data_type": 1,
"float_data": [
0.02
],
"name": ""
},
"type": "TENSOR"
}
]
},
{
"input": [
"gpu_0/pred_b_0__SHAPE"
],
"output": [
"gpu_0/pred_b_0"
],
"op_type": "ConstantOfShape",
"attribute": [
{
"name": "value",
"t": {
"dims": [ …
```
=> Support JSON as a serialization target

docs/Changelog.md, docs/Operators.md, onnx/defs/math/defs.cc
Fixes the typo described in #5282 
fixes https://github.com/onnx/onnx/issues/5282
=> Fix einsum documentation typo

docs/Syntax.md, onnx/defs/printer.cc
* Update parser documentation to show syntax for initializers and value-infos
* Update printer to print initializers and value-infos
(See https://github.com/onnx/onnx/issues/5529 )
=> Handle initializers in printer

docs/Changelog-ml.md, docs/Changelog.md, docs/Operators-ml.md, docs/Operators.md, onnx/defs/math/defs.cc, onnx/defs/math/old.cc, onnx/defs/nn/defs.cc, onnx/defs/nn/old.cc, onnx/defs/quantization/defs.cc, onnx/defs/tensor/defs.cc, onnx/defs/tensor/old.cc, onnx/defs/traditionalml/defs.cc, onnx/defs/traditionalml/old.cc
Squash typos in defs
Replace https://github.com/onnx/onnx/pull/4888 and then some.
=> Squash typos in */defs.cc

onnx/defs/schema.h
Remove deprecated functions in schema.h that are marked for deletion in 1.15
=> Remove deprecated functions in schema.h

onnx/__init__.py, onnx/external_data_helper.py
Respect the proto def. Close #5552.
=> Reject absolute path when saving external data

.github/workflows/release_mac.yml, .github/workflows/release_win.yml
Set env for onnx-weekly correctly.
Fix Windows and Mac weekly CI failure: set env correctly:
- https://github.com/onnx/onnx/actions/runs/6140254770
- https://github.com/onnx/onnx/actions/runs/6140288376
=> Fix Windows and Mac weekly CI failure: set env correctly

.azure-pipelines/Linux-CI.yml, .azure-pipelines/MacOS-CI.yml, .azure-pipelines/Windows-CI.yml, README.md
Fix broken status badge in README: running CI nightly in main branch from Azurepipelines
Fixes https://github.com/onnx/onnx/issues/5577.
=> Fix broken status badge in README: nightly run CI in main branch

onnx/defs/shape_inference.h, onnx/shape_inference/implementation.cc, onnx/shape_inference/implementation.h
rename createNewImpl with createNew
more compact interface
=> Rename `createNewImpl` to `createNew`

onnx/common/platform_helpers.h
Simplify endian detection logic by removing if branches and leveraging c++ syntax.
Reference: https://github.com/pytorch/pytorch/blob/653c1564bf4c46d9758000ea70a610ee3699acf1/caffe2/operators/fused_rowwise_nbitfake_conversion_ops.h#L16-L19
Code quality
=> Simplify endian detection logic

onnx/test/reference_evaluator_backend_test.py, onnx/test/reference_evaluator_test.py, onnx/test/test_backend_reference.py, onnx/test/version_utils.py
=> Set tolerance for dft tests

onnx/test/reference_evaluator_backend_test.py, onnx/test/reference_evaluator_test.py, onnx/test/test_backend_reference.py, onnx/test/version_utils.py
=> cherry-pick from main - Set tolerance for dft tests (#5623)

.azure-pipelines/Linux-CI.yml, .reuse/dep5, codecov.yml, requirements-release.txt
Use the codecov uploader in azure pipelines to report coverage to codecov
=> Report coverage to codecov

docs/PythonAPIOverview.md, docs/docsgen/source/api/index.md, docs/docsgen/source/api/inliner.md
=> Add documentation for inliner

onnx/version_converter/convert.h
Fix swapped version numbers in version converter.
=> Fix swapped version numbers in version converter

onnx/checker.py
Closes #5018
Add what type of exception checks `check_model` function has.
=> Doc: Add exception checks in check_model

onnx/reference/__init__.py
=> Define `__all__` in onnx.reference

onnx/onnx-ml.proto, onnx/onnx-ml.proto3, onnx/onnx.in.proto, onnx/onnx.proto, onnx/onnx.proto3
Fix documentation in file *.proto about FLOAT8E5M2FNUZ
=> Fix documentation in file *.proto about FLOAT8E5M2FNUZ

docs/docsgen/source/conf.py
Update documentation copyright.
=> Increment year to 2024 in conf.py

onnx/defs/parser.h
Add parser support for int4 types
=> Add parser support for int4 types

docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc
Update batchnorm documentation (number of outputs for training mode)
Redo of PR #5288 (since that PR is stalled).
=> Update batchnorm documentation (number of outputs for training mode)

onnx/helper.py, onnx/onnx-ml.proto, onnx/onnx-ml.proto3, onnx/onnx.in.proto, onnx/onnx.proto, onnx/onnx.proto3
Followup of #5938 to add similar metadata field to ValueInfoProto as well.
=> Metadata for ValueInfo

onnx/defs/tensor/old.cc, onnx/test/shape_inference_test.py
replicate of https://github.com/onnx/onnx/pull/5735 by @daquexian 
Fix shape inference for Squeeze-11 and Squeeze-1
=> Fix shape inference for Squeeze-11 and Squeeze-1

.github/workflows/check_urls.yml, docs/Hub.md
Fix Check URLs errors
* Update ONNX model zoo URL to reflect changes in their repo
* Update timeout so https://github.com/onnx/onnx/blob/main/docs/Operators.md passes
=> Fix Check URLs errors in `main`

.azure-pipelines/Windows-CI.yml
fix find libprotobuf which is suggested by https://gitlab.kitware.com/cmake/cmake/-/issues/25704
=> Use CMAKE_PREFIX_PATH in finding libprotobuf

onnx/defs/math/defs.cc, onnx/defs/math/old.cc
Add the invalid shape information in errors message of NegativeLogLikelihoodLoss's inference function.
Better errors
=> Update error messages for NegativeLogLikelihoodLoss inference function

docs/OnnxReleases.md
* Update release process documentation
* Add more detailed steps in some sections
* Add steps to create local test pypi instance so changes can be tested locally before pushing to TestPyPI or PyPI
* Update the documentation based on steps I used for the 1.16.0 release.
=> Update release process documentation

onnx/numpy_helper.py
=> Fix 1 typo in numpy_helper.py

onnx/common/version.h
Prepare for rel-1.16.1 branch
Prepare ONNX 1.16.1 release
=> Prepare for rel-1.16.1 branch

onnx/reference/ops/op_reduce_sum_square.py, onnx/test/reference_evaluator_test.py
Reverts onnx/onnx#6121
https://github.com/onnx/onnx/issues/6103
cc @xadupre @gramalingam
=> Revert "Corrected the ReduceSumSqure op to match the reference"

.github/workflows/dco_merge_group.yml, .github/workflows/main.yml, .github/workflows/release_win.yml, .github/workflows/scorecard.yml, .github/workflows/stale.yml, .github/workflows/weekly_mac_ci.yml, .github/workflows/win_no_exception_ci.yml, CONTRIBUTING.md, README.md, RELEASE-MANAGEMENT.md, SECURITY.md
=> Add/Format License/Copyright headers

.github/workflows/main.yml, .github/workflows/win_no_exception_ci.yml
=> Better name for Github Action and fix Windows build on CI

onnx/hub.py
Hi, this pr is cleaner version than #6145
=> Mitigate tarball directory traversal risks

onnx/utils.py
This change modifies the DFS search used in model extraction to use sets rather than iterables
While shape inference is the most significant bottleneck, these changes are a step in the direction of being able to support model extraction for very large graphs.
```python3
import onnx
from onnx.utils import Extractor
model = onnx.load("obertquant.onnx")
extractor = Extractor(model)
extracted_model = extractor.extract_model(
input_names=["input_ids", "attention_mask", "token_type_ids"], output_names=["2058"]
)
onnx.save(extracted_model, "truncated.onnx")
```
Benchmarks were produced using pyinstrument and analyzing the `Extractor.extract_model` function
| Model Name | Num Nodes | Previous | New |
| ---- | -------- | --------- | ----- |
| obertquant.onnx | 1271  | 0.158s   | 0.110s |
| …
=> Use sets to improve performance of dfs search

docs/OnnxReleases.md
=> typo: Update OnnxReleases.md

onnx/checker.cc, onnx/defs/data_type_utils.cc, onnx/defs/parser.cc, onnx/inliner/inliner.cc, onnx/version_converter/convert.h
Remove some unused variables detected by static analyzer.
=> Remove unused variables

.github/workflows/check_urls.yml, docs/ImplementingAnOnnxBackend.md, docs/docsgen/source/intro/converters.md
Fixed URLs to pass URL check in main branch
PR fixes the URL check failing links on main branch : https://github.com/onnx/onnx/actions/runs/10477762212/job/29019601472
=> Fix main url checks

.github/workflows/release_linux_x86_64.yml, .github/workflows/release_win.yml, .github/workflows/scorecard.yml
Bump actions/upload-artifact from 3 to 4
=> Bump actions/upload-artifact from 3 to 4 

.github/workflows/main.yml
=> Update main.yml (upgrade github actions download/upload artifact)

onnx/checker.cc, onnx/defs/data_type_utils.cc, onnx/defs/parser.cc, onnx/inliner/inliner.cc, onnx/version_converter/convert.h
Cherry-Pick (#6303) - Remove unused variables into the `rel-1.17.0` branch
Cherry pick commit to `rel-17.0` branch to target 1.17 release
=> [Cherry-Pick] Remove unused variables (#6303)

.github/workflows/create_release.yml
fix condition for publishing to testpypi (Update create_release.yml)
=> BF: fix condition for publishing to testpypi (Update create_release.yml)

onnx/defs/math/defs.cc, onnx/test/data_propagation_test.py
=> Fix OOB in data propagation of math ops when input is broadcasted to zero

.github/workflows/main.yml
Set up codecov Test Analytics: https://docs.codecov.com/docs/test-result-ingestion-beta
=> Set up codecov test analysis

.github/workflows/check_urls.yml, docs/ImplementingAnOnnxBackend.md, docs/docsgen/source/intro/converters.md
Cherry-Pick (#6312) - Fix main url checks into the `rel-1.17.0` branch
Cherry pick commit to `rel-1.17.0` branch to target 1.17 release
=> [Cherry-Pick] Fix main url checks (#6312)

onnx/reference/custom_element_types.py, onnx/reference/ops/op_non_max_suppression.py
Fixes a bug in ReferenceEvaluator.
=> Fix NonMaxSuppression default values in ReferenceEvaluator

.github/workflows/release_win.yml
=> Update Protobuf to latest version (Win)

onnx/checker.cc, onnx/common/file_utils.h, onnx/common/interned_strings.cc, onnx/common/interned_strings.h, onnx/common/ir.h, onnx/defs/function.cc, onnx/defs/math/defs.cc, onnx/defs/operator_sets.h, onnx/defs/operator_sets_ml.h, onnx/defs/operator_sets_preview.h, onnx/defs/operator_sets_training.h, onnx/defs/schema.cc, onnx/defs/sequence/defs.cc, onnx/defs/tensor/defs.cc, onnx/defs/tensor/old.cc, onnx/version_converter/BaseConverter.h, onnx/version_converter/adapters/adapter.h, onnx/version_converter/adapters/axes_attribute_to_input.h, onnx/version_converter/adapters/axis_attribute_to_input.h, onnx/version_converter/adapters/axis_input_to_attribute.h, onnx/version_converter/adapters/broadcast_backward_compatibility.h, onnx/version_converter/adapters/broadcast_forward_compatibility.h, onnx/version_converter/adapters/extend_supported_types.h, onnx/version_converter/adapters/type_restriction.h, onnx/version_converter/convert.cc, onnx/version_converter/convert.h
Fix more static analyser warnings.
Better code.
=> Fix more static analyser warnings

onnx/common/interned_strings.h, onnx/common/ir.h, onnx/common/ir_pb_converter.h, onnx/common/model_helpers.cc, onnx/common/model_helpers.h, onnx/common/status.h, onnx/common/visitor.h, onnx/defs/data_propagators.h, onnx/defs/function.h, onnx/defs/printer.cc, onnx/defs/schema.h, onnx/defs/sequence/defs.cc, onnx/defs/shape_inference.cc, onnx/defs/shape_inference.h, onnx/defs/tensor_proto_util.cc, onnx/defs/tensor_util.cc, onnx/inliner/inliner.cc, onnx/test/cpp/function_verify_test.cc, onnx/version_converter/adapters/axes_input_to_attribute.h, onnx/version_converter/adapters/transformers.h, onnx/version_converter/convert.cc
=> Fix more static analyzer warnings

.clang-tidy, onnx/checker.h, onnx/common/ir.h, onnx/common/ir_pb_converter.cc, onnx/common/model_helpers.cc, onnx/common/status.cc, onnx/common/status.h, onnx/defs/data_type_utils.cc, onnx/defs/data_type_utils.h, onnx/defs/function.h, onnx/defs/math/old.cc, onnx/defs/nn/defs.cc, onnx/defs/nn/old.cc, onnx/defs/parser.cc, onnx/defs/parser.h, onnx/defs/printer.cc, onnx/defs/schema.cc, onnx/defs/schema.h, onnx/shape_inference/implementation.h, onnx/version_converter/convert.cc, onnx/version_converter/helper.cc
This PR fixes more clang-tidy warnings and adds more checks.
Better code.
=> Fix clang-tidy warnings

CMakeLists.txt
Remove usage of deprecated module.
=> Use CMake python module 

CMakeLists.txt, onnx/common/path.h
=> Enable more compiler warnings

CMakeLists.txt
=> Set hidden visibility on onnx target

onnx/checker.cc, onnx/common/ir_pb_converter.cc, onnx/defs/controlflow/old.cc, onnx/defs/controlflow/utils.cc, onnx/defs/math/old.cc, onnx/defs/shape_inference.h, onnx/inliner/inliner.cc
=> Fix more static analyser warnings 

CMakeLists.txt
=> Use -Wall -Wextra on APPLE platforms

onnx/utils.py
Optimize the dfs function by merging two for loop into one.
There's no meaning to keep `stack += nodes[node_index].input` in an independent for loop.
=> Optimize DFS

docs/IR.md
- Clarify that static optionals are available to all IR versions
- Improve wording.
Spec clarification.
=> Update IR spec to clarify optional input/output availability

onnx/defs/parser.cc, onnx/defs/parser.h
=> Refactor parser code

onnx/common/tensor.h, onnx/version_converter/adapters/reshape_5_4.h, onnx/version_converter/adapters/split_13_12.h, onnx/version_converter/adapters/upsample_9_8.h
I found some wrong use cases of const_cast in ONNX and fixed them.
=> Fix invalid use of const_cast

onnx/test/cpp/function_context_test.cc
Fix function_context_test.cc so that it works when exceptions are disabled.
=> Fix excpetion handling

onnx/utils.py
Optimized the `_collect_new_io_core` function.
The updated version behaves the same way as the previous one.
The modification includes:
1. Use a for loop to build `new_io_tensors`
2. Add return type
3. Moved the duplicate check to `extract_model` function.
The original version uses `set`, `map` and `dict` to make simple works complicated.
=> Optimize _collect_new_io_core in extract_model

onnx/defs/parser.cc, onnx/defs/parser.h
Fix some ODR violations in parser.
=> Fix ODR violations

onnx/backend/test/runner/__init__.py, pyproject.toml, requirements-lintrunner.txt
=> Update ruff to 0.7.0

onnx/external_data_helper.py, onnx/helper.py, onnx/mapping.py, onnx/model_container.py, onnx/shape_inference.py, onnx/subbyte.py
Remove some 'type: ignore' and other fixes
=> Add more type annotations and fix warnings in Python code

onnx/defs/generator/utils.cc, onnx/defs/math/old.cc, onnx/defs/schema.cc, onnx/defs/schema.h, onnx/defs/sequence/defs.cc, onnx/defs/shape_inference.h, onnx/test/cpp/shape_inference_test.cc
=> Fix clang -Weverything warnings

.github/workflows/pages.yml
Another attempt to downgrade the protobuf version used in CI jobs
=> Another attempt to fix protobuf version problem

.github/workflows/create_release.yml
=> Bugfix fix file name in create_release.yml

.github/workflows/main.yml, docs/docsgen/source/api/model_container.md, docs/docsgen/source/requirements.txt
=> Fix pipeline, limit to onnxruntime <1.20 for docs build

.github/workflows/create_release.yml
Add publishing of devbuild to testpypi up to publishing to pypi is fixed
=> Add publishing of devbuild to testpypi

.github/workflows/pages.yml
=> Use localy build protobuf in doc pages

.github/workflows/release_mac.yml, .github/workflows/release_test_weekly_sdist.yml
=> Remove usage of Mac12-Runner

.github/workflows/create_release.yml
Improving the environment name
=> Improving the environment name

setup.py
For better compatibility in different platforms.
=> Simplify CMake argument handling in setup.py

.github/workflows/create_release.yml
* Improve naming
* fix missing check for workflow_dispatch
* check if publish option was set to "yes"
=> Fix of the devbuild publish-workflow

.github/workflows/release_linux_aarch64.yml, .github/workflows/release_linux_x86_64.yml, .github/workflows/release_mac.yml, .github/workflows/release_win.yml
Removing any unit test involving onnxruntime.
https://github.com/onnx/onnx/issues/6484
https://github.com/onnx/onnx/pull/6214
=> Removing unit test involving onnxruntime

docs/Changelog.md, docs/Operators.md, onnx/defs/tensor/defs.cc
Update gather doc, as per discussion in https://github.com/onnx/onnx/issues/5619
=> Update gather doc

docs/docsgen/source/api/helper.md, docs/docsgen/source/intro/python.md
Corrected two grammatical errors in documentation.
Self explanatory.
=> add grammatical corrections to documentation

.clang-tidy, onnx/checker.cc, onnx/common/assertions.h, onnx/common/ir.h, onnx/cpp2py_export.cc, onnx/defs/controlflow/old.cc, onnx/defs/controlflow/utils.cc, onnx/defs/math/defs.cc, onnx/defs/math/old.cc, onnx/defs/nn/old.cc, onnx/defs/printer.cc, onnx/defs/shape_inference.cc, onnx/defs/traditionalml/defs.cc, onnx/test/cpp/shape_inference_test.cc, onnx/version_converter/adapters/scan_9_8.h
Enables more clang-tidy readability checks and apply the fixes.
Better engineering.
=> Enable more readability checks

README.md
=> fix typo: Update README.md

CONTRIBUTING.md
Fix https://github.com/onnx/onnx/issues/6634
=> Fix link in readme

.github/workflows/create_release.yml
Unify names of github environments
I already updated the github environments.
=> Unify names of github environments

.github/workflows/create_release.yml
=> Improve Names in CI pipeline

.github/workflows/create_release.yml
=> Improve name in CI-Pipeline

.github/workflows/release_linux_aarch64.yml, .github/workflows/release_linux_x86_64.yml
Don't run further steps when wheel was not created
=> Improve release_linux_*.yml

INSTALL.md
Update recommended Protobuf version and other improvements in INSTALL.md
Better documentation.
=> Update recommended Protobuf version and other improvements in INSTALL.md

docs/PythonAPIOverview.md
This PR corrects the `Pad` operator example in the Python API documentation. The original code incorrectly treated `value` as an input tensor and used an invalid `pads` data type. The updated example sets `value` as a float attribute, uses `INT64` for `pads`, and includes OPSET 11 compatibility.
The incorrect example could lead users to create invalid ONNX models. This fix ensures the documentation reflects proper usage of the `Pad` operator and ONNX standards, improving the developer experience.
=> Fix Pad operator example in Python API docs (correct attribute usage)

CMakeLists.txt, setup.py
Use Python3_add_library to simplify build code
Better engineering.
=> Use Python3_add_library to simplify build code

.github/workflows/create_release.yml
=> Fix condition at download step for publishing manuel preview build

.github/workflows/auto_update_doc.yml, docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc
Format rotary embedding documentation for proper rendering.
cc @gramalingam
=> Format rotary embedding documentation

.github/workflows/create_release.yml
=> Fix condition in CI for sdist download

docs/PythonAPIOverview.md
Small PR - Commit c1bd5cca137343edd74975cd973e854cb54b58ec moved the notebook examples. This PR adjusts sources to changes.
=> Update Jupyter notebook examples

docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc
Add more details on handling of negatives axes for RMSNormalization op.
=> Modify axis description for RMSNormalization op

.github/workflows/create_release.yml
Publish to testpypi only for workflow_dispatch
=> Publish to testpypi only for workflow_dispatch event

pyproject.toml
=> Add copyright header to pyproject.toml

.github/workflows/sdist_test.yml
=> define top-level permission

.github/workflows/release_linux_aarch64.yml, .github/workflows/release_linux_x86_64.yml
=> Simplify checkout submodules

.github/workflows/create_release.yml
=> Improve condition in create_release.yml

.github/workflows/release_win.yml
=> Remove separate onnx-directory in release_win.yml

.github/workflows/create_release.yml
=> fix: names of jobs in create_release.yml

onnx/checker.py, onnx/compose.py, onnx/external_data_helper.py, onnx/gen_proto.py, onnx/helper.py, onnx/model_container.py, onnx/numpy_helper.py, onnx/reference/ops/op_quantize_linear.py, onnx/reference/ops/op_string_split.py, onnx/reference/reference_evaluator.py, onnx/serialization.py, onnx/shape_inference.py, onnx/subbyte.py, onnx/utils.py, pyproject.toml
Fix some mypy warnings without breaking the code.
Better code quality.
=> Improve Python code typing

requirements-lintrunner.txt
Use latest ruff
Better tooling.
=> Bump ruff to 0.9.10

requirements-min.txt, requirements-release.txt
=> Adapt requirements files as 3.9 is the minimal supported python version

.github/workflows/release_win_freethreading.yml
=> refactor: remove unnecessary x86 check in win freethreading

.github/workflows/release_mac_freethreading.yml
=> fix non existing requirements-file

.github/workflows/release_linux_x86_64.yml
=> fix wrong use of always in release_linux_x86_64.yml

.github/workflows/release_linux_x86_64.yml
=> hard code docker image docker://quay.io/pypa/manylinux2014_x86_64:2025.02.28-1 in release pipeline

.github/workflows/release_mac_freethreading.yml, .github/workflows/release_win.yml, .github/workflows/release_win_freethreading.yml
=> windows-latest -> windows-2022

onnx/backend/test/report/__init__.py, onnx/backend/test/report/coverage.py, onnx/numpy_helper.py, tools/protoc-gen-mypy.py
=> [2/N]Remove ignore_type suppression

.github/workflows/create_release.yml
a) fix wrong condition
b) don't print the variables twice
=> fix condition in pipeline

.github/workflows/main.yml, .github/workflows/pages.yml, .github/workflows/release_mac.yml, .github/workflows/release_mac_freethreading.yml, .github/workflows/release_win.yml, .github/workflows/release_win_freethreading.yml, CMakeLists.txt
Change `ONNX_WERROR` to take effect only for onnx source.
=> Use ONNX_WERROR=ON in all jobs

.github/workflows/main.yml
It's possible to ``use pip install -e .`` in all Python versions on Windows.
Better tooling.
=> Merge Windows CI jobs

.github/workflows/preview_source_dist_test.yml
=> Improve source build testing

.github/workflows/release_linux_x86_64.yml
=> Update pypa / manylinux2014_x86_64 in release_linux_x86_64.yml to 2025.03.22-2

onnx/defs/data_type_utils.cc, onnx/defs/logical/defs.cc, onnx/defs/logical/old.cc, onnx/defs/math/defs.cc, onnx/defs/math/old.cc, onnx/defs/nn/defs.cc, onnx/defs/nn/old.cc, onnx/defs/reduction/defs.cc, onnx/defs/reduction/old.cc, onnx/defs/schema.cc, onnx/defs/text/defs.cc, onnx/test/cpp/function_context_test.cc, onnx/version_converter/convert.h, requirements-lintrunner.txt
Bump clang-format and format code.
Better code.
=> Bump clang-format to 20

.github/workflows/preview_source_dist_test.yml
It is pulling from pypi so it shouldn't be triggered by pull requests.
=> Remove the pull trigger in source dist test

.github/workflows/create_release.yml, .github/workflows/release_mac_freethreading.yml
=> Fix missing inputs in create_release.yml

.github/workflows/preview_source_dist_test.yml
=> remove not used condition in preview_source_dist_test.yml

.github/workflows/create_release.yml, .github/workflows/release_win_x86_64.yml
=> Update and rename release_win.yml to release_win_x86_64.yml

docs/Versioning.md, onnx/defs/schema.h, onnx/helper.py, onnx/test/helper_test.py
=> Update versioning in the main branch after release branch cut

.github/workflows/release_linux_aarch64.yml
=> Update release_linux_aarch64 to include 3.13t

.github/workflows/lint.yml, onnx/test/model_container_refeval_test.py, requirements-release_test.txt
This pull request includes changes to the `.github/workflows/lint.yml` file to update the Python version, improve submodule handling, and refine the installation process for ONNX.
Workflow improvements:
* Updated the `python-version` to `3.11` to use the latest Python version.
* Added `submodules: recursive` to ensure all submodules are checked out recursively.
Installation process improvements:
* Changed the ONNX installation command from `python setup.py install` to `python -m pip install .` for better compatibility and reliability.
=> Improve lint CI

.github/workflows/create_release.yml, .github/workflows/main.yml, .github/workflows/release_win_aarch64.yml, .github/workflows/release_win_x86_64.yml, .github/workflows/win_no_exception_ci.yml, requirements-release_build.txt, requirements-release_test.txt, workflow_scripts/protobuf/build_protobuf_win.ps1
=> Add native ARM64 Windows Builds

.github/workflows/main.yml
=> Remove win arm64 from main.yml

.github/workflows/create_release.yml
=> better condition and explanations in create_release.yml 

onnx/defs/schema.h
Export some symbols used by PyTorch, see https://github.com/pytorch/pytorch/pull/151694
API compatibility.
=> Export symbols used by PyTorch

onnx/shape_inference/implementation.h
Expose more symbols for PyTorch. After these changes my builds success without linking errors.
API compatibility.
=> Export more symbols used by PyTorch

CMakeLists.txt
Add quotes and conversions to path variables in CMake build to fix Windows building.
Better code.
=> Pick CMake changes

CMakeLists.txt
Rewrite some CMake code to simplify it.
Better code.
=> Simplify CMake code

.github/workflows/release_mac.yml, .github/workflows/release_sdist.yml
=> Replace requirements-release.txt with requirements-release_build.txt

docs/OnnxReleases.md
=> Update OnnxReleases.md (add remove of rc packages at test.pypi)

.github/install_test.yml
=> Update and rename Install_test.yml to install_test.yml

docs/docsgen/source/onnx_sphinx.py, onnx/backend/test/case/node/layernormalization.py, onnx/reference/ops/op_layer_normalization.py, onnx/reference/ops/op_roi_align.py, onnx/test/cpp/inliner_test.cc
=> Fix typos in multiple files

.github/release.yml
=> Add workflow to generate release notes

.gitattributes
=> Set eol in gitattributes

onnx/defs/schema.h
For all C++17 compilers we support, it's possible to use this attribute.
Remove old code.
=> Use [[maybe_unused]]

onnx/onnx-ml.proto, onnx/onnx-ml.proto3, onnx/onnx.in.proto, onnx/onnx.proto, onnx/onnx.proto3
This documents TBD of onnx.proto release date of IR version 11
Ref: https://pypi.org/project/onnx/1.18.0/
=> Fix IR 11 release comment of onnx.in.proto

onnx/onnx-ml.proto, onnx/onnx-ml.proto3, onnx/onnx.in.proto, onnx/onnx.proto, onnx/onnx.proto3
Update IRv10 brief docs to include relevant updates. Fix https://github.com/onnx/onnx/issues/6050
=> Update IRv10 brief docs

.github/workflows/create_release.yml, .github/workflows/release_linux.yml, .github/workflows/release_mac.yml, .github/workflows/release_win_aarch64.yml, .github/workflows/release_win_x86_64.yml
=> Shorten names in create_release/release_linux for better UX in github ui

RELEASE-MANAGEMENT.md
=> fix typo in Update RELEASE-MANAGEMENT.md

.github/workflows/release_win_aarch64.yml
=> python 3.14-dev for release_win_aarch64.yml

.github/workflows/release_win_aarch64.yml
=> use newest python 3.13 version in release_win_aarch64.yml

.github/workflows/pixi_build.yml
=> Update and rename pixi-build.yml to pixi_build.yml

.github/workflows/manylinux/entrypoint.sh
=> clean up unnecessary dependencies in entrypoint.sh

requirements-dev.txt
there are no versions in setup.py ?
=> remove outdated comment in requirements-dev.txt

RELEASE-MANAGEMENT.md
=> fix typo in  RELEASE-MANAGEMENT.md

.github/workflows/weekly_modelzoo.yml
change runner from mac to linux
linux runner are considerably cheaper than mac runner
=> weekly_modelzoo.yml (mac -> linux runner)

.github/workflows/release_mac.yml
=> add fail-fast to release_mac.yml

.github/workflows/main.yml
=> Reduce macos runs in main.yml

.github/workflows/release_mac.yml
=> Use specific version for mac os runner

.github/workflows/pixi_build.yml
=> add top level permissions (Update pixi_build.yml)

.github/workflows/copilot-setup-steps.yml
=> define top level permission (Update copilot-setup-steps.yml)

.github/workflows/release_win_x86_64.yml
=> add python 3.14-dev (release_win_x86_64.yml)

docs/OnnxReleases.md
Document new workflow
Releases without offline tasks to enchance supply chain security
=> Add documentation for building and publishing whls to pypi (OnnxReleases.md)

.github/workflows/release_win_x86_64.yml
=> no pytest for 3.13t (release_win_x86_64.yml)

.github/release.yml
=> Update release.yml module: CI pipelines

.github/workflows/create_release.yml
=> add missing call-win_arm64 (Update create_release.yml)

docs/Versioning.md, onnx/common/version.h, onnx/defs/schema.h, onnx/helper.py, onnx/test/helper_test.py
Update various versions for 1.19 release
=> update versions for 1.19 release

.github/install_test.yml, .github/workflows/manylinux/entrypoint.sh, .github/workflows/release_mac.yml, .github/workflows/win_no_exception_ci.yml, requirements-min.txt, requirements-release_test.txt
Remove conditional code for Python 3.9 in CI
Python 3.9 support is gradually being dropped.
=> Remove conditional code for Python 3.9 in CI and requirements*txt

requirements.txt
=> adapt to numpy req min, Update requirements.txt

docs/OnnxReleases.md
Update the release checklist with the correct pipeline configs for generating pypi artifacts.
=> Update OnnxReleases.md with the correct pipeline configs

RELEASE-MANAGEMENT.md
=> Update figures; Update RELEASE-MANAGEMENT.md

.github/workflows/create_release.yml
=> add check for rc-candidates (Update create_release.yml)

CMakeLists.txt
Signed-off-by: cyy <cyyever@outlook.com>
=> Avoid unnecessary re-generating of proto files (#7253)

.github/workflows/main.yml
https://api.securityscorecards.dev/projects/github.com/onnx/onnx
complains about
"Info: Possibly incomplete results: error parsing shell code: statements must be separated by &, ; or a newline: .github/workflows/main.yml:131",
=> Use PowerShell (pwsh) in windows step in main.yml

docs/Changelog.md, docs/Operators.md, onnx/defs/nn/defs.cc, onnx/reference/ops/op_rotary_embedding.py
Address comments https://github.com/onnx/onnx/pull/7313#discussion_r2370175660
=> Rename variables in rotary embedding reference for clarity

setup.py
=> Revert "Drop 32bit support on Windows"

.github/workflows/main.yml
Due to external changes, this test combination can pass.
Better CI
=> Enable macOS + Python 3.13 test

setup.py
Support ninja builds except on Windows.
Speed up builds.
=> Support Ninja builds

onnx/reference/ops/op_reduce_sum.py, onnx/reference/ops/op_unsqueeze.py, onnx/tools/update_model_dims.py
Use `TypeError` for type exceptions.
More pythonic code.
=> Throw TypeError

.github/workflows/release_mac.yml
=> Update release_mac.yml; don't run pytest for 3.14-dev
