onnx/onnx

- docs/Operators.md
- onnx/defs/nn/defs.cc
Pool input should always have channel or depth dimension, rename convolution input from `filter` to `weights`, to avoid confusion with kernel and remove the optional third input to convolution which wasn't used.
> Fix pool and conv doc

- onnx/onnx.proto
Including the names of tensors in the initializer list also in the input list is redundant (and somewhat confusing). It is simpler to treat them as being disjoint.
> changed documentation to make initializers disjoint from inputs

- onnx/__init__.py
- onnx/checker.py
- onnx/helper.py
- onnx/onnx.proto
- onnx/test/basic_test.py
- onnx/test/helper_test.py
Reordered the fields of Graph per issue #53 in order to allow streaming implementations to read version info first in order to either fail fast or quirk based on the IR version and producer version used to produce the graph.
Note that this is a breaking change to (a) any serialized GraphProto's and (b) any code that used the GraphProto.producer_version, which is now encoded as a string given that we can't assume that all frameworks/runtimes that will emit ONNX adhere to the SemVer versioning scheme.
Note, that there is one other potential BC once we reconcile typeshape and operator_library PRs.
> BREAKING CHANGE: Reordered fields of GraphProto to enable streaming implementations to read version info first.

- onnx/defs/tensor/defs.cc
Pad:
Input(1): The tensor to be padded.
Output(1): The padded tensor.
Attr:
paddings: a list of int, size(paddings) should be equal to dim(input) * 2. Indicates the size of paddings at the beginning/end of each dimension. (Required = true)
mode: a string, can be constant(default), reflect, replicate
value: a float, the value of paddings, default is 0.
> Add pad operator

- onnx/defs/rnn/defs.cc
Pretty much adds a spec for a fixed stacked RNN that can be supported by CuDNN backend. Attributes are taken almost directly from CuDNN/TensorRT spec.
One interesting question is how to standardize the layout of parameters. Theoretically, layout of parameters in CuDNN is opaque (and one needs to set them via separate calls), however we need to choose some. I happen to pick the layout of parameters that corresponds to the real one used by CuDNN (did some reverse engineering). Backend implementations should still go with cudnn calls to reorder the parameters, but it might be convenient for some early testing.
Alternative to merging all parameters in a single tensor would be having directions * layers * 2 * 4 * 2 separate tensors which would be too much in my opinion.
When we land the …
> Operator for fixed RNN (CuDNN style)

- onnx/defs/nn/defs.cc
Since the second output is optional.
> changed NumOutputs of Dropout to be 1 or 2

- onnx/backend/base.py
- onnx/backend/test.py
1. Exposes tests to onnx-caffe2 in a better way, so that we can run only model tests or only node tests or some subset of tests. Change is backward-compatible and the only change in onnx-caffe2 needs to be:
```
globals().update(onnx.backend.test.BackendTest(c2).test_cases)
```
2. Adds device support to node_test - I need it for now for RNN tests before we have reference implementation done in Caffe2.
> Improving tests: suites handling and device support

- onnx/backend/test.py
- onnx/backend/test_rnn.py
Add backend test for the RNN op. As reference implementation I actually added numpy cudnn-compatible implementation (adopted from earlier code from fooling around).
Note, that some tests are disabled because Caffe2 backend doesn't support them yet. Will enable accordingly.
> Add RNN reference tests

- onnx/backend/base.py
- onnx/backend/test.py
as we now have GPU only tests for CuDNN-style RNNs
> Skip the GPU-only tests if no GPU is available 

- setup.py
Read "PROTOBUF_LIB" from environment variable (in my local case it's "C:\ProgramData\Anaconda3\pkgs\protobuf-3.4.0-py36_vc14_0\Library" after running "conda install -c conda-forge protobuf numpy"), so that the include dirs. and libraries could be relative to "PROTOBUF_LIB".
Adding "/MT" when compiling to fix "MT_STATICRELEASE" and "MD_DYNAMICRELEASE" mismatch.
> Read protobuf lib from environment variable and add compile option /MT

- docs/Operators.md
- onnx/defs/reduction/defs.cc
This PR fix the following:
1. Change ArgMin and ArgMax to take a single axis instead a vector of axis.
2. Fix the doc to all reduce OPs including argmin and argmax.
> Fix ArgMin and ArgMax, the should take a single axis not axes.

- README.md
Installation from source (```pip install onnx``` or ```pip install -e .``` in the source directory) requires one to first install the Protobuf compiler (protoc). This should be documented in README.md.
> Update README.md for non-conda build from source

- onnx/__init__.py
Linter does not like unused import. But this is needed.
> add __version__ back

- onnx/backend/test.py
We should always set self._parent_module to parent_module.
> Fix a little bug in backend/test.py

- onnx/checker.py
- onnx/defs/schema.h
- onnx/helper.py
- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.proto
- onnx/onnx.proto.in
- onnx/onnx.proto3
This PR adds a type discriminator to AttributeProto to address issues for proto3 users.
Because we want to make the discriminator required in subsequent versions of the spec, I bumped the IR version patch # so that our checker can catch when it is missing.
> Add discriminator to attribute proto

- onnx/__init__.py
- onnx/checker.py
- setup.py
```
commit f0f4747e70547a78827f69a525261f37bd6fa977
Author: Edward Z. Yang <ezyang@fb.com>
Date:   Mon Oct 30 08:17:20 2017 -0700
Complain about stale onnx_pb2 file.
I noticed some library code was importing onnx_pb2 incorrectly.  The
name of this file has changed, but the old source file was left around
because it was generated by protoc.  This leads to weird errors like
TypeError: 'GraphProto' object is not iterable because we're doing
a GraphProto test with two things named GraphProto, but not the same
thing.
Easiest to tell the user to remove the stale file manually.
commit b1af2957cc8eec5d19dfc2519fdfba81af49bd80
Author: Edward Z. Yang <ezyang@fb.com>
Date:   Mon Oct 30 08:12:08 2017 -0700
Undo BC-breaking change, restore 'import onnx' …
```
> Bugfixes I noticed porting latest ONNX to PyTorch

- docs/Operators.md
- onnx/defs/nn/defs.cc
This PR contains multiple changes together:
1. Add back bias to Conv and ConvTranpose, similar to GEMM this is needed for performance.
2. Add auto_pad with 3 options: SAME_UPPER, SAME_LOWER and VALID in order to cover conversion from other frameworks.
3. pads: add back lower and upper that we had in Caffe2, because now we have the auto_pad option and this is the manual option.
4. Update the documentation to cover the behavior in details.
5. MaxPool and AveragePool need to have the same behavior.
6. Add Group for ConvTranspose to be consistent with conv.
7. Add bias for ConvTranspose to be consistent with conv.
> Update Conv, ConvTranspose, MaxPooling and AveragePooling.

- setup.py
window build was broken by recent changes (the python command should be explicitly called when generating .proto files).
Windows CI build should be setup quickly to prevent this kind of build break.
> fix build break in windows

- onnx/test/numpy_helper_test.py
The type can be specified directly to randint; casting it after the fact won't work after the min/max values given are in the i64 range.
> Fix 'ValueError: low is out of bounds for int32' error in test_int64

- onnx/backend/test.py
Hi, 
I believe using relative tolerance is more sensible (this change roughly translates to we can tolerate 0.1% deviation) . In many model outputs, values are softmaxed, which means they are very small (in most cases, first non-zero digit starts from the third decimal place) and errors are squashed. Therefore checking 4 decimal place is not enough. This may give new backends unwarranted confidence in terms of correctness.
Best wishes,
Tian Jin.
> Using more sensible assertions

- docs/Operators.md
- onnx/defs/nn/defs.cc
> VALID mean no padding, therefore, read the pixel values from the pads attribute.
We cannot make sense of the logical consequence as evinced in the use of `therefore` here. Therefore in this PR we hope to resolve the conflict of auto_pad and pads in a more coherent way.
More specific reason for change, quoted from https://github.com/onnx/onnx/pull/166 
> If auto_pad = 'VALID' that mean not auto_padding, in this case if pads is specified then use the value in pads attribute, otherwise no padding is applied.
> 
> Here is the logic,
> If auto_pad = SAME_LOWER or SAME_UPPER, then ignore pads attribute.
> If auto_pad = VALID, then check pads attribute. If pads attribute isn't empty, then use it. Otherwise no padding.
> @ebarsoum This could be very confusing for the Tensorflow world as 'VALID' …
> Suggesting Conv Pads Behavior

- onnx/defs/schema.cc
```
onnx/defs/schema.cc:28:7: warning: field 'description_' will be initialized after field 'type_str_' [-Wreorder]
description_(description),
^
1 warning generated.
```
> Fix compilation warning

- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.in.proto
- onnx/onnx.proto
- onnx/onnx.proto3
I'm removing message "valueproto" since it's not being used for now. We could add it back when we see a case using it, for example, if there's an initializer which is not a tensor data.
> remove value proto message since it's not being used in any model.

- docs/Operators.md
- onnx/defs/experiments/defs.cc
- onnx/defs/math/defs.cc
- onnx/defs/rnn/defs.cc
- onnx/defs/tensor/defs.cc
*Any variable represented by a full word or multiple words is all lower case and uses underscores when it helps with readability
*Any variable that represents a bias tensor will utilize the name “bias”
> operator signature consistency updates

- docs/Operators.md
- onnx/defs/nn/defs.cc
As discussed in #185 from the TensorFlow authors, there is a consensus to move away from the auto_pad settings and move towards explicit padding values in the future. As a result, this PR adds an explicit deprecation warning to auto_pad suggesting people to not use auto_pad in any future models, and only use it for legacy support.
Shall we also consider a deprecation timeline in general?
For more reads on why the auto_pad setting (especially SAME) is bad, I wrote up a longer note which is essentially the points I shared in the earlier onnx design meeting a few weeks ago:
https://gist.github.com/Yangqing/47772de7eb3d5dbbff50ffb0d7a98964
> Add deprecation warning to auto_pad

- onnx/checker.cc
- onnx/checker.h
- onnx/helper.py
- strip_doc_string is useful for tests in pytorch which puts entire stacktrace into docstring. I think it's quite generally useful
- validation error appends the entire bad node spec if invoked inside check_graph - makes it much easier to spot the problem
> Stripping doc string and better error message for ValidationError

- onnx/__init__.py
Specified the wrong model file and onnx.load silently ate it while producing an empty result struct, which is not cool
> Check that the entire protobuf is deserialized

- docs/Operators.md
- onnx/cpp2py_export.cc
- onnx/defs/schema.cc
- onnx/defs/schema.h
- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
This is on top of https://github.com/onnx/onnx/pull/235 to demonstrate the bare minimum necessary to get the SinceVersion machinery working, with multiple versions of operators. It moves the old 'split' operator (modified in a BC-breaking way by Emad) into an old.cc file, sets up OpSchema to record multiple versions of an operator, but then has the public Python interface only return the latest versions.
I think the next thing to do is build a changelog rendererer, which shows a chronological listing of operator definitions as they change over operator definitions.
> Bare minimum to get SinceVersion running

- onnx/examples/Protobufs.ipynb
- onnx/helper.py
- setup.cfg
Example output: git push --set-upstream origin dzhulgakov/update-printer
For future work, would be nice to rewrite it using something like https://github.com/caffe2/caffe2/blob/master/caffe2/python/net_printer.py
> Prettify printer: show initializers, types, etc

- .gitignore
- .travis.yml
- .travis/build.sh
- .travis/install.sh
- onnx/gen_proto.py
- setup.py
Why do we need this:
- As more and more of our development happens in c++, `distutils`'s default compilation mechanism slows down our development speed (no incremental build, no parallel build).
- With ninja build file, we can generate clang compilation database, which enables us using all kinds of clang tools (e.g. clang static analyser, clang-tidy ...)
As a beginning, we don't by default opt-in users to use ninja, instead it will only be enabled if users have installed ninja in their environment.
In this diff, only support for unix builds are added, mostly because I'm unfamiliar with windows.
> Integrate ninja build system into setup.py (Unix only)

- docs/Operators.md
- onnx/defs/tensor/defs.cc
Addresses #296 - it's generally useful. For example Caffe2 has Gather (axis=0) and BatchGather (axis=1). I haven't added tests because we want to fix backends first probably.
> add axis attribute to Gather

- MANIFEST.in
- setup.cfg
Redistributions of your source code are supposed to include the `LICENSE` text under the terms of your license, but your distributions currently don't – this makes it harder for everyone to follow the license. :)
The `MANIFEST.in` file makes sure that `LICENSE` ends up in the `.tar.gz` source files from `sdist`, and the `setup.cfg` setting tells wheels about it.
> include license info in distributions

- onnx/cpp2py_export.cc
- onnx/defs/gen_doc.py
- onnx/defs/schema.h
Now the API accurately reflects how we use it.
> Change get_all_schemas to return a vector rather than map.

- docs/Operators.md
- onnx/cpp2py_export.cc
- onnx/defs/experiments/defs.cc
- onnx/defs/gen_doc.py
- onnx/defs/math/defs.cc
- onnx/defs/nn/defs.cc
- onnx/defs/rnn/defs.cc
- onnx/defs/schema.cc
- onnx/defs/schema.h
- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
- onnx/defs/traditionalml/defs.cc
This is a follow-up of https://github.com/onnx/onnx/issues/285.
More thoughts and open questions:
1. Remove all "NumInputs", "NumOutputs" API, which seem to be not needed now given we have "optional", "variadic" types specified clearly.
2. Do we need to support "optional" and "variadic" outputs? for example, operator "Split". How do we hook up the outputs of "Split" with another node (op)?
> Change API to support specifying "single", "optional" and "variadic" input

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
I think the input tensor shape description for BatchNormalization may be outdated. ONNX `BatchNormalization` Op does not have an `order` attribute, so I believe the axes order should just be `NCHW`.
> BatchNormalization docs - change input tensor shape description

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
Some updates to the `Split` operation docs are needed:
* remove mention of optional second input blob
* update Argument name `axis` to `split`
> Split docs - remove mention of optional second input blob

- .gitignore
- onnx/checker.cc
- onnx/checker.h
- onnx/checker.py
- onnx/cpp2py_export.cc
- onnx/defs/__init__.py
- onnx/defs/schema.cc
- onnx/defs/schema.h
- onnx/helper.py
- onnx/test/checker_test.py
Now all checker functions take a CheckerContext, which specifies what
the set of in-scope opset imports are.  We use this to decide which
version of a schema to pull out of the schema checker when doing
validation.
Public facing APIs default to the most recent operator set version
we know about.
>  Fix checker to know about versions.

- onnx/defs/schema.h
I used to use "opname" as the static op registry field name, which is not good given we now having many versions with the same op.
> fix issue so that we could handle many versions of one op

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
- onnx/defs/rnn/defs.cc
1. Rename activation function to follow the Op Name
- e.g. linear -> Affine, sigmoidhard -> HardSigmoid
2. Remove PRelu and ParametricSoftPlus
Only description change.
> Update RNN Activation Funcs

- README.md
Docker image is specific to the tutorials, so move there
> Move docker links to Tutorials

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
- onnx/defs/nn/old.cc
There are a couple of requests for this feature from PyTorch side https://github.com/pytorch/pytorch/issues/3826. So I think we should add adjs attribute into ConvTranspose. Actually, this PR chooses the second solution in https://github.com/onnx/onnx/issues/102, which enables both output_shape and adj. Adjs will be ignored if output_shape exists, so it won't break any existing models.
> Add adjs attribute to ConvTranspose

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
In `InstanceNormalization`, the `variance` rather than input `B` are computed per instance per channel.
> Fix a typo in InstanceNormalization doc.

- setup.py
While using "pip install -e onnx" in windows using Anaconda, there will be message like "...onnx\onnx/onnx.pb.h(9): fatal error C1083: Cannot open include file: 'google/protobuf/stubs/common.h': No such file or directory", which is descript in [Issue133](https://github.com/onnx/onnx/issues/133). This message will help beginning users to find out the problem quickly. @linkerzhang
> Issue 133: Print useful message for missing ProtoBuf Environment Variable problem.

- setup.py
setup.py is looking for git, and when git is not installed it fails the setup.
Updating error handling to gracefully handle the case where git is not installed.
> PyPi install fails when git is not installed

- onnx/checker.cc
Two changes here
- tensor and graph checks for singular tensor and graph arguments were missing, this adds those
- Fix a bug in the tensor check where an empty list of dims would cause checking to fail, but this is semantically valid as it indicates a scalar
> Add checking for singular graph and tensor arguments

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/experiments/defs.cc
Based on discussions, Gather can be used in place of Embedding. Gather is a supported operator whereas Embedding is an experimental operator so remove to avoid any confusion.
> remove unnecessary experimental Embedding op

- onnx/common/ir.h
- onnx/optimizer/passes/split.h
when we split a graph, all initializers go to the init net
> Deduplicate initializers in split graphs

- onnx/proto_utils.h
Destructor of CodedInputStream will not free the ZeroCopyInputStream, hence previously we have a leak in the code. This PR fixes it. 
https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.io.coded_stream#CodedInputStream
> Fix leakage in proto_util

- onnx/backend/test/runner/__init__.py
Since we change the file extension from .pb to .onnx, we should not keep the old cached files.
> Change the cached model checking logic

- CMakeLists.txt
Since onnx can be used as a submodule, we want to add option to avoid include its own pybind11 dir if the target is already exported in upper level. This can avoid version clashes in submodules. 
@Maratyszcza
> Don't include pybind11 if its target is already exported

- docs/ImplementingAnOnnxBackend.md
Since we have moved `onnx-caffe2` into `caffe2`. Update the documentation here.
> Remove onnx-caffe2 reference

- CMakeLists.txt
`mkdir -p` argument is not supported on Windows. The PR uses CMake functions instead to create the output directory.
> Minimally fix CMakeLists on Windows

- CMakeLists.txt
When we need to build protobuf on the fly, we can use its target binary to process .proto file. 
Also fixes the linkage issue on Mac OS. (Same situation as https://github.com/caffe2/caffe2/pull/1514)
> Handle situations where protobuf is built on the fly

- CMakeLists.txt
Sometimes we need to use protoc compiled for host architecture while linking libprotobuf against target architecture (iOS and Android). See https://github.com/caffe2/caffe2/blob/96f35ad75480b25c1a23d6e9e97bccae9f7a7f9c/cmake/ProtoBuf.cmake#L92-L99
This PR provides such an option to do so. In addition, it makes compiling of python binding optional as on some of the platform, there might not be `Python.h`.
> Add option to use customized protoc

- onnx/checker.cc
- onnx/common/ir.h
- onnx/string_utils.h
Android doesn't have `std::to_string` and we need to in order to build with Caffe2 in Android. 
Code copied from https://github.com/caffe2/caffe2/blob/4f534fad1af9f77d4f0496ecd37dafb382330223/caffe2/core/common.h#L198-L206
> to_string for Android

- CMakeLists.txt
- onnx/onnx_pb.h
- Use `__declspec(dllexport)` only in shared library build
- Use `target_compile_definitions` for macros instead of `target_compile_options`
- Avoid redefining ONNX_API
> Fix ONNX library build for Windows

- onnx/defs/rnn/old.cc
This seems to be a typo and missing namespace will resulting in symbol conflict when we load multiply copies of onnx with different `ONNX_NAMESPACE`.
> Add ONNX_NAMESPACE around rnn/old.cc

- .gitmodules
- CMakeLists.txt
- tools/protobuf-bench.cc
This PR is in relation to decision about proper message for `onnxGetBackendCompatibility` in #551
In my experiments `GraphProto` version takes `19 us`, `ModelProto` version - `20 us`.
> Microbenchmark for encoding+decoding single-op GraphProto and ModelProto

- onnx/checker.cc
- onnx/proto_utils.h
It's generally preferable to use libprotobuf_lite on mobile. However, some features in ONNX were not supported by libprotobuf_lite. To make ONNX lite compatible:
- Add flag ONNX_USE_LITE_PROTO
- Use MessageLite.SerializeAsString() in place of Message.ShortDebugString()
> Add ONNX_USE_LITE_PROTO

- onnx/proto_utils.h
This sets the protobuf parse limit to 2GB rather than one. This unblocks the use of potentially large models, for example NLP models with embeddings tables.
We plan to come out with a more general solution for handling prohibitively large models in the near future.
> Set 2GB protobuf parse limit

- onnx/cpp2py_export.cc
- onnx/defs/schema.cc
- onnx/defs/schema.h
- onnx/defs/tensor/defs.cc
- onnx/shape_inference.py
- onnx/shape_inference/shape_inference.h
- onnx/test/backend_shape_inference_test.py
- onnx/test/shape_inference_test.py
as an optimizer pass, and a proof-of-concept shape inference
implementation for Transpose.
The way that we define the actual shape-inference logic is subject to
change, but the way in which it's tied into the optimizer is pretty
straightforward and probably won't need a big overhaul.
> Introduce shape inference

- onnx/cpp2py_export.cc
- onnx/defs/__init__.py
- onnx/test/schema_test.py
```
In [1]: from onnx import defs
In [2]: s = defs.get_schema('BatchNormalization')
In [3]: s.attributes['epsilon'].default_value
Out[3]:
name: "epsilon"
f: 9.999999747378752e-06
type: FLOAT
In [4]: type(s.attributes['epsilon'].default_value)
Out[4]: onnx_pb2.AttributeProto
```
> Fix Attribute default value pybind11 binding

- onnx/cpp2py_export.cc
- onnx/defs/__init__.py
Return the schema with biggest version, which is not greater than specified maxInclusiveVersion.
Make get_schema function easier to use.
> add max inclusive version to defs.get_schema function

- setup.py
on centos7 cmake3 is available as the command "cmake3" instead of "cmake"
> Use cmake3 if it's available

- setup.py
The bug can cause `pip uninstall` to remove the user's entire site-packages directory
> Fix incorrect package output paths

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
I have checked Tensorflow, MxNet, PyTorch, Caffe2, they all support at least 3d, 4d, 5d tensors. CNTK seems also supporting ND tensor. To improve the interoperability, I think it's better to extend the BatchNorm and InstanceNorm spec to support ND tensor as input.
> Fix the spec of batchnorm and instancenorm

- .travis/before_install.sh
- pyproject.toml
This PR is to try out if this would work with pip on CI.
An alternative is: https://github.com/onnx/onnx/pull/783
> Try using pep518 to install the protobuf build dependency

- onnx/defs/shape_inference.h
- onnx/proto_utils.h
old version protobuf uses `long long` as int64 type, new version uses `int64_t` and `RepeatedField<long long>` can not be converted to `RepeatedField<int64_t>`
> Make proto_utils compatible for old version of protobuf

- onnx/checker.cc
- onnx/defs/shape_inference.h
- onnx/shape_inference/implementation.h
caffe2_benchmark.cc build is failing on android because of use of std::to_string. This PR fixes it
> Use ONNX_NAMESPACE::to_string instead of std::to_string

- onnx/optimizer/passes/eliminate_identity.h
- onnx/optimizer/passes/eliminate_nop_transpose.h
- onnx/optimizer/passes/fuse_add_bias_into_conv.h
- onnx/optimizer/passes/fuse_consecutive_transposes.h
- onnx/optimizer/passes/fuse_transpose_into_gemm.h
- onnx/optimizer/passes/optimize_pass.h
- onnx/test/optimizer_test.py
This allows us to properly handle optimizing the body of control operators.
For the moment, we've skipped applying this to the `Split` pass. This is because doing so would turn that pass into a true loop-invariant hoisting pass. This introduces issues in that we can no longer assume that the graphs we are splitting are run at least once (as we've assumed for the existing split pass). This can cause operations that can fault to be hoisted out, when in reality they may never have been run under normal conditions.
> Extend optimizer passes to recursively descend on GraphProto attributes

- onnx/common/interned_strings.h
- onnx/common/ir.h
- onnx/common/ir_pb_converter.cc
- onnx/defs/schema.cc
- onnx/optimizer/optimize.h
- onnx/optimizer/passes/lift_lexical_references.h
- onnx/test/optimizer_test.py
Lift lexically-scoped references within control operators to be inputs of the
ops themselves. This transformation yields a graph that does not conform to
the ONNX spec.
The purpose of this pass is to expose the data dependencies within control
blocks for frameworks that use those dependencies to schedule parallel
execution. e.g. caffe2 graph execution.
There are a few edits here and there to allow for this transformation, but nothing earth-shattering.
> Pass to lift captured values as inputs to control nodes

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
- onnx/optimizer/passes/fuse_add_bias_into_conv.h
- onnx/test/optimizer_test.py
~~Change the type and description of 2nd and 3rd inputs.~~
With more investigation, most existing frameworks aligned with numpy. So I aligned our spec with numpy, too. Numpy strongly suggests not using broadcast in tile. In our spec, broadcast is not supported.
> Tile - align with numpy

- docs/Changelog-ml.md
- docs/Operators-ml.md
- onnx/defs/traditionalml/defs.cc
Change the return type for the zipmap operator to match the description in the spec.
> Change the return type for the zipmap operator to match the description in the spec.

- docs/Changelog-ml.md
- docs/Operators-ml.md
- onnx/defs/traditionalml/defs.cc
Coefficients represent the model for LinearClassifier. Having it as OPTIONAL makes the implementation to assume defaults and could lead to different results. So this change is to make it non optional.
> Make the coefficient non optional for LinearClassifier

- onnx/onnxifi.h
- Change the type to `LUID` instead of generic `GUID`
- Document relation to `ID3D12Device::GetAdapterLuid()`
> Update return type and documentation on ONNXIFI_BACKEND_DIRECTX_ID

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/generator/defs.cc
Use OpSchema::all_tensor_types() as per https://github.com/onnx/onnx/pull/846 comment
> Use op schema.all tensor types in random like definitions

- onnx/cpp2py_export.cc
- onnx/defs/gen_shape_inference_information.py
- onnx/defs/schema.h
- onnx/defs/shape_inference.h
at the moment, this outputs
```
103 operators have a type/shape inference function.
12 do not. These are:
ATen
ConvTranspose
Crop
FC
GRU
GRUUnit
If
LSTM
Loop
LoopIndexTensor
RNN
Upsample
```
> add script to count shape inference implementations

- CMakeLists.txt
- setup.py
- tools/protoc-gen-mypy.py
type stubs should not be a hard requirements for users
> Do not generate protobuf python type stubs if protobuf python package is not installed

- CMakeLists.txt
Protobuf compiler wasn't found on my system, which caused the cmake ONNX_PROTOC_EXECUTABLE to be not set, and what should have been a command like `protoc onnx.proto ...` became `onnx.proto ...`. The error message was then `onnx.proto: Permission denied` which was quite unhelpful and took me some time to track down.
This PR improves the error message for this case.
> Better error message if protoc isn't found

- onnx/test/__init__.pyi
- tools/__init__.pyi
- tools/mypy-onnx.py
Before, we had this custom script running mypy on all files in the onnx/test folder. This is, however, not a great solution.
I figured out that I can add a `__init__.pyi` file to the folder, which makes it a python module in respect to mypy, but not in respect to installation (i.e. users are still not able to import the module and it's not part of the pypi distribution). Seems this is a better way.
> Better way to enable mypy in test/ and tools/ folder.

- onnx/backend/test/case/node/reducel1.py
- onnx/backend/test/case/node/reducel2.py
- onnx/backend/test/case/node/reducelogsumexp.py
- onnx/backend/test/case/node/reducemax.py
- onnx/backend/test/case/node/reducemean.py
- onnx/backend/test/case/node/reducemin.py
- onnx/backend/test/case/node/reduceprod.py
- onnx/backend/test/case/node/reducesum.py
- onnx/backend/test/case/node/reducesumsquare.py
- setup.cfg
Only look at last commit, the rest is in PR #991  .
This changes the mypy config so that untyped functions are disallowed. So in future, if someone writes python code, they're forced to write type hints and I won't have to play catch up again.
> Enforce writing type hints.

- onnx/defs/math/defs.cc
- onnx/defs/shape_inference.h
I've factored out a function that I will use to implement shape inference after https://github.com/onnx/onnx/pull/907 lands.
However this diff is standalone and can be pushed separately
> refactor matmul shape inference for generality

- docs/Changelog.md
- docs/Operators.md
- onnx/checker.cc
- onnx/checker.h
- onnx/common/assertions.h
- onnx/common/ir_pb_converter.cc
- onnx/common/ir_pb_converter.h
- onnx/cpp2py_export.cc
- onnx/defs/controlflow/defs.cc
- onnx/defs/experiments/defs.cc
- onnx/defs/function.cc
- onnx/defs/generator/defs.cc
- onnx/defs/logical/defs.cc
- onnx/defs/logical/old.cc
- onnx/defs/math/defs.cc
- onnx/defs/math/old.cc
- onnx/defs/nn/defs.cc
- onnx/defs/nn/old.cc
- onnx/defs/operator_sets-ml.h
- onnx/defs/operator_sets.h
- onnx/defs/reduction/defs.cc
- onnx/defs/rnn/defs.cc
- onnx/defs/rnn/old.cc
- onnx/defs/schema.cc
- onnx/defs/schema.h
- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
- onnx/defs/traditionalml/defs.cc
- onnx/shape_inference/implementation.h
This changes how operator schema are registered and used by ONNX. 
The motivation for this change is two-fold.  First, it transfers policy to the consumer for which operator schema and versions of those schema will be registered.  Second, it avoids a pattern of static object usage which can cause downstream compilation and performance issues.
Before this change, schema are registered using a macro (ONNX_OPERATOR_SCHEMA) which populates a static map.  This PR changes these macros to implement methods constructing the schema.  It also exposes functions that iterate across schema in different operator sets.
By default, the static registration map is populated with the operator sets on first use.  Callers can also disable this and populate the map manually.  Finally they can implement …
> Enable non-static schema registration

- onnx/defs/nn/defs.cc
- onnx/defs/shape_inference.h
- onnx/defs/tensor/defs.cc
@gramalingam Before passing an index to protobuf's repeated field, you must check if the index is valid first.  Otherwise, it's a security issue.
> Add index check for Transpose's type inference function

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/math/defs.cc
- onnx/defs/math/old.cc
- onnx/defs/reduction/defs.cc
- onnx/defs/schema.h
float16 was supported for math and reduction ops before, and now add it back.
cublas support half op half -> half as https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemm
> add float16 support back for math and reduction ops

- onnx/common/tensor.h
Should fix issues with std I just saw in the pytorch builds. For example:
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.6-gcc5.4-build/10549/console
```
/var/lib/jenkins/workspace/third_party/onnx/onnx/common/tensor.h:342:40: error: 'sqrt' is not a member of 'std'
```
> Use cmath instead of math.h

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
https://github.com/onnx/onnx/issues/1114
I consider this as fixing a bug in spec, and it's backward compatible for existing models.
So I prefer not bumping up the opset version.
> Make Axes in Squeeze Optional

- README.md
Just realized the `benchmark` module also contains another submodule.
Better to add it.
> Add recursive flag to the submodule command

- onnx/onnxifi.h
ONNXIFI_SYNCHRONIZATION_DEFAULT was renamed to ONNXIFI_SYNCHRONIZATION_EVENT, but few comments were not updated
> Fix comment refencing ONNXIFI_SYNCHRONIZATION_DEFAULT

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/controlflow/defs.cc
- onnx/defs/nn/defs.cc
Simple typos that I noticed when implementing the specs + docs generation.
> Fix docs typos and generate docs

- onnx/onnxifi.h
Functions returning a handle via output parameter must return this status if output pointer is NULL.
> Document ONNXIFI_STATUS_INVALID_POINTER return code

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
- onnx/defs/operator_sets.h
- onnx/test/shape_inference_test.py
Address https://github.com/onnx/onnx/issues/417
However, MaxUnpool is also missing. We probably should add it, too (in a different PR).
> Support output indices in MaxPool op

- docs/Optimizer.md
The links are not relative to the project root folder but the current file, so they are broken.
> Fix broken links in docs/Optimizer.md

- onnx/onnxifi.h
Previous text is gibberish in this part.
> Clarify supported synchronization primitives in onnxRunGraph

- onnx/onnxifi.h
Most deep learning frameworks and higher-level software let users specify verbosity level. The new ONNXIFI_BACKEND_PROPERTY_LOG_LEVEL property lets a deep learning framework convey this information to an ONNXIFI backend.
> Add ONNXIFI_BACKEND_PROPERTY_LOG_LEVEL backend initialization property

- onnx/onnxifi.h
As per discussion with WinML, this PR adds version tags to tensor descriptor and memory fence structures, to ensure that we can extend/revise these structures in the future without losing compatibility with existing backends.
Attn @yinghai, @rdzhabarov, @varunjain99, @zrphercule: this is a breaking change.
> Add version tags to tensor descriptor and memory fence structures

- onnx/onnxifi.h
I noticed that we don't have an appropriate error code when reviewing ONNXIFI-TensorRT implementation. This PR adds `ONNXIFI_STATUS_INVALID_MEMORY_TYPE` and `ONNXIFI_STATUS_UNSUPPORTED_MEMORY_TYPE`
> Add error code for invalid/unsupported memory types in ONNXIFI

- onnx/onnxifi.h
Add detailed backend information queries about for ONNXIFI version, ONNX IR versions, and opset versions supported by a backend, as suggested by WinML. Deep learning frameworks can use this information to choose which version of ONNXIFI/IR/opset to use when interfacing the backend.
> Add info queries for ONNXIFI version, ONNX IR version, and opset version

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/data_type_utils.cc
- onnx/defs/schema.h
- onnx/defs/tensor/defs.cc
For many tensor ops, they should support all tensor types. this PR is fixing the wrong type constraints specified before.
> fix type constraints for tensor ops.

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
The strides defaults should be 1 along each axis.
Maybe we should have a `strides_doc` ?
> Fix LpPool document.

- onnx/test/optimizer_test.py
The models in optimizer test cases produce errors when we run the shape-inference checking on them. This PR tries to fix the errors in the shape-specifications in these test cases. (Please take a look, since I don't know what features these test-cases are supposed to test.)
> fix shape errors in optimizer test cases

- docs/OpsetVersionConverter.md
Appended a "/" to fix the outbound links from the OpsetVersionConverter.md page.
> Correcting links in OpsetVersionConverter.md

- onnx/onnxifi.h
- onnx/onnxifi_loader.c
- onnx/onnxifi_loader.h
Per discussion with WinML, add a non-blocking function to query `onnxEvent` state.
> Add onnxGetEventState function in ONNXIFI

- onnx/onnxifi.h
- onnx/onnxifi_dummy.c
- onnx/test/cpp/onnxifi_backend_test.cc
This is needed to support per-graph accuracy specification and similar external attributes.
Attn: @yinghai, @varunjain99, @bddppq, @zrphercule: this is a breaking change
> Add auxiliary property list argument to onnxInitGraph

- .travis.yml
We suggest you use the real image with Xcode 9.3 GM i.e. `osx_image: xcode9.3`
> Move off the Xcode 9.3 beta image on Travis CI

- CMakeLists.txt
When compiled as static library and included as a lib in other project, current cmake OLD behavior won't honor the visibility settings from the outer projects, resulting in warning in linking. This fixes it.
> Honor visibility options when compiled as a static library

- onnx/common/interned_strings.h
- onnx/examples/optimize_onnx.ipynb
- onnx/optimizer.py
- onnx/optimizer/optimize.h
- onnx/optimizer/passes/eliminate_nop_pad.h
- onnx/test/optimizer_test.py
[Why]
A Pad layer with argument pads = zeros does nothing and should be removed.
Such a nop pad is observed when converting torchvision.resnet to onnx
[How]
* We mimic the optimization pass of nop_transpose and created the nop_pads optimizer.
* Test cases are added ensuring the correctness.
> [Optimization Pass] Add optimization pass eliminating nop Pad

- onnx/common/ir.h
- onnx/common/ir_pb_converter.cc
We noticed that after optimizing a model that node domains were stripped out. After investigating we noticed that the domain was not loaded from the GraphProto. After this change optimizing a model will not lose the node domains.
**Summary of changes:**
Added domain_ member to the Node class, plus setter/getters
Modified graphProtoToGraph to copy across the domain
Modified  encodeGraph(GraphProto * p_g, const std::shared_ptr<Graph> & g) to copy the domain back into the GraphProto node.
> Domain exists in GraphProto but not in Node

- CMakeLists.txt
Pybind in Fedora 26 repo is 2.0.x, but ONNX requires pybind 2.2+.
Modify CMakeLists.txt to check that.
> Check pybind version

- onnx/defs/tensor/defs.cc
#1320 
```
error: 'floor' is not a member of 'std'
```
> Add missing include for using std::floor

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/controlflow/defs.cc
Drop the words "specified axes of" from the documentation of scan op. (This refers to a outdated version.)
> minor fix to scan documentation

- CMakeLists.txt
~~Also fixed the issue of duplicating libonnx in the link command of onnx_cpp2py_export~~
Results of `nm -g .setuptools-cmake-build/onnx_cpp2py_export.so | wc -l`:
Before: 2677
After: 396
> Do not export onnx symbols in the python extension

- onnx/onnxifi.h
Error when releasing an object is often not actionable, and thus no need to force user to check it.
> Remove ONNXIFI_CHECK_RESULT from onnxRelease* functions

- onnx/common/ir_pb_converter.cc
This situation occurs, for example, in code like this:
```
x = 3
if foo:
x = 4
```
Notice there is no textual `else` branch, but in the graph we will have an empty `else` graph on the `If` node with the original value of `x` as the output. In this case, this is value in an enclosing scope that's used as a graph output, so we need to replicate the dummy node logic for graph outputs as well.
> Fixup handling of captured values as graph outputs

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/logical/defs.cc
- onnx/defs/logical/old.cc
- onnx/defs/operator_sets.h
More like a spec fix instead of adding new features. So prefer not bumping the opset version for these two ops (really no need).
> Supporting int32 and int64 in Less and Greater

- CMakeLists.txt
By setting ONNX_SRCS before including onnx's cmake files
> [cmake] Allow adding extra source files to the onnx lib

- CMakeLists.txt
When downstream project includes onnx, it usually sets ONNX_NAMESPACE to avoid protobuf conflicts, for example https://github.com/pytorch/glow/blob/21cf654a0192924d8d9415d1577caef7d0af3114/lib/Importer/CMakeLists.txt#L6-L13. 
In ONNX CMakefile, if we do `set(ONNX_NAMESPACE "onnx" CACHE STRING "onnx namespace")`, it will ignore previous set ONNX_NAMESPACE because of `CACHE`. Quote
> The code ‘set(FOO “x”)’ sets the normal variable ‘FOO’. It does not touch the cache, but it will hide any existing cache value ‘FOO’.
>
>The code ‘set(FOO “x” CACHE …)’ checks for ‘FOO’ in the cache, ignoring any normal variable of the same name. If ‘FOO’ is in the cache then nothing happens to either the normal variable or the cache variable. If ‘FOO’ is not in the cache, then it is added to the cache.
From …
> Fix ONNX_NAMESPACE definition

- onnx/backend/test/cpp/driver_test.cc
Bug: using unserialized model in test driver. It is now fixed.
> [ONNXIFI]serialized model data in test driver, ir version is now corrected

- onnx/backend/test/cpp/driver_test.cc
Change the expect to assert for some tests in onnxifi test driver. This can prevent onnxifi test driver from crashing once model is not supported by backend.
> [ONNXIFI]gtest:expect to assert

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/generator/defs.cc
This is a bug in the spec of `ConstantLike` op. The spec says that if `dtype` is not specified then the type of the input tensor should be used as the output tensor type. But currently, with the default value specified for this op, this attribute will always be _present_, and therefore, it is contrary to the spec. With this fix the default value is removed, which will allow the `dtype` attribute to be absent, in which case the input tensor type can be used for output type. 
Since this op was checked in very recently (less than two weeks ago), I am not updating the opset for this change.
> Remove default value for 'dtype' attribute in ConstantLike op.

- onnx/backend/test/cpp/driver_test.cc
Add two more expect/assert in test driver.
The examine of compat will finally be changed to skipping the test instead of failing it.
> [ONNXIFI]Add examine of onnxGetBackendCompatibility and onnxGetBackendInfo in onnxifi test driver

- onnx/defs/schema.cc
- onnx/defs/schema.h
Putting it in a header file causes multiple instances of DomainToVersionRange existing in different libs
> Move the definition of the singleton DomainToVersionRange to .cc file

- onnx/common/ir_pb_converter.cc
/Users/travis/build/onnx/onnx/onnx/common/ir_pb_converter.cc:20:10: warning: enumeration value 'TensorProto_DataType_BFLOAT16' not handled in switch [-Wswitch]
> Fix compiler warnings on unhandled bfloat16 switch case

- onnx/defs/data_type_utils.cc
Opaque type ToString() does not wrap the result into the supplied  left and right. Reformat.
> Fix Opaque ToString

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/math/defs.cc
- onnx/defs/math/old.cc
- onnx/defs/nn/defs.cc
- onnx/defs/nn/old.cc
- onnx/defs/operator_sets.h
Gemm should support ints, like MatMul (fixed in previous PR).
Flatten should support all types.
PRelu: y=slope*x if x < 0 and y = x if x >0, mathematically, it can support int types as added in this PR.  I'm not sure whether there's real use case using PRelu operating ints.
> support more types for Gemm, Flatten and PRelu

- cmake/external/googletest.cmake
- onnx/backend/test/cpp/driver_test.cc
Add gtest_skip in test driver to skip no-compatible test cases.
now we have 275 skipped test cases.
> [ONNXIFI]Add skip logic in onnxifi test driver

- docs/Versioning.md
It is highly desirable for model loaders to quickly gauge their compatibility with the operators in a model when loading it and to reliably know that they can compute correct results. The current wording though for op set versioning is unclear regarding optional attributes, which makes it sound like it's legal to add a new attribute to an operator without updating the version number so long as (a) it's marked optional, and (b) it's absence would yield the same behavior as the earlier version of the operator. This is okay when the attribute *is* missing, but it would be bad for the model loader when the new attribute is present as the execution would think that it could successfully process a model and all operators in it, only to yield incorrect results because it was unaware of a newly …
> Operator set versioning - tighten wording regarding breaking changes

- cmake/Utils.cmake
- cmake/unittest.cmake
- onnx/defs/experiments/experiments_functions.cc
- onnx/defs/function.cc
- onnx/defs/function.h
- onnx/defs/operator_sets.h
* Change Function registry flow into the Opschema registering way.
* Get rid of whole-archive during compiling
> Change Function registry flow; Get rid of whole-archive in compile

- onnx/backend/test/cpp/driver_test.cc
Right now, we dont clean when our test failed, which may cause memory leaking.
In this pr we introduced a macro to handle the clean up in test driver.
We also updated the testing process in onnxifi test driver, fixed a few bug of not using signal.
> Clean memory when failed test

- onnx/backend/test/cpp/driver_test.cc
- onnx/onnxifi_utils.cc
- onnx/onnxifi_utils.h
We didnt use persistent memory in test driver, which may cause memory leaking.
> [ONNXIFI]Reliable memory of shape in test driver

- appveyor.yml
- onnx/backend/test/cpp/driver/test_driver.cc
- onnx/backend/test/cpp/driver/test_driver.h
- onnx/backend/test/cpp/driver_test.cc
Before:
[ RUN      ] ONNXCppAllTest/ONNXCppDriverTest.ONNXCppDriverUnitTest/1
[       OK ] ONNXCppAllTest/ONNXCppDriverTest.ONNXCppDriverUnitTest/1
[ RUN      ] ONNXCppAllTest/ONNXCppDriverTest.ONNXCppDriverUnitTest/2
[       OK ] ONNXCppAllTest/ONNXCppDriverTest.ONNXCppDriverUnitTest/2
After:
[ RUN      ] ONNXCppAllTest/ONNXCppDriverTest.ONNXCppDriverUnitTest/test_maxpool_2d_strides
[       OK ] ONNXCppAllTest/ONNXCppDriverTest.ONNXCppDriverUnitTest/test_maxpool_2d_strides 
[ RUN      ] ONNXCppAllTest/ONNXCppDriverTest.ONNXCppDriverUnitTest/test_conv_with_strides_padding
[       OK ] ONNXCppAllTest/ONNXCppDriverTest.ONNXCppDriverUnitTest/test_conv_with_strides_padding
> [ONNXIFI]Make TEST_P be able to show the test case name directly

- onnx/backend/test/cpp/test_main.cc
Not to ruin gtest argument by always assuming the last argument to be the data target dir
> [ONNXIFI]Maintain Gtest main.cc argument 

- onnx/cpp2py_export.cc
- onnx/defs/function.cc
- onnx/defs/function.h
- onnx/test/cpp/function_get_test.cc
This avoids redundant copies of functionproto returned to any API users.
> Change function ownership to ONNX

- onnx/checker.cc
In proto3 models, if the attribute value is set to be the default value (say 0 for int), it will not really have the value set, then used_fields will be 0. We'd relax the checker logic to pass such models.
> fix onnx checker to support proto3 models.

- onnx/backend/test/report/__init__.py
Using the deprecated API results in pages of warning spew when running with pytest.
> Shut up warnings about markers.

- cmake/external/googletest.cmake
googletest target cannot be found when using ninja to build onnx.
this pr fixed it by adding BUILD_BYPRODUCTS macro.
> Fix googletest building when using ninja

- onnx/optimizer/passes/lift_lexical_references.h
Resubmit, since we already over write it internally.
> Fix the Lift Lexical Reference pass in optimizer

- onnx/optimizer/pass_manager.cc
- onnx/optimizer/pass_manager.h
Use set is dangerous. The order is important for some passes. Use vector to replace set.
> Use vector instead of set to keep the order of the opt passes

- onnx/backend/test/cpp/driver_test.cc
- onnx/backend/test/cpp/gtest_utils.cc
- onnx/backend/test/cpp/gtest_utils.h
- onnx/backend/test/cpp/test_main.cc
orginally there are a few namespace missing in test driver, and now it is fixed.
> fix some issue with namespace

- CMakeLists.txt
- onnx/checker.cc
- onnx/defs/function.cc
- onnx/optimizer/pass.h
- onnx/optimizer/passes/eliminate_identity.h
- onnx/optimizer/passes/eliminate_nop_pad.h
- onnx/optimizer/passes/eliminate_nop_transpose.h
- onnx/optimizer/passes/fuse_consecutive_log_softmax.h
- onnx/optimizer/passes/fuse_consecutive_squeezes.h
- onnx/optimizer/passes/fuse_consecutive_transposes.h
- onnx/optimizer/passes/fuse_transpose_into_gemm.h
- onnx/optimizer/passes/nop.h
- onnx/version_converter/adapters/averagepool_7_6.h
- onnx/version_converter/adapters/batch_normalization_6_5.h
- onnx/version_converter/adapters/batch_normalization_6_7.h
- onnx/version_converter/adapters/broadcast_backward_compatibility.h
- onnx/version_converter/adapters/compatible.h
- onnx/version_converter/adapters/concat_3_4.h
- onnx/version_converter/adapters/dropout_6_7.h
- onnx/version_converter/adapters/gemm_6_7.h
- onnx/version_converter/adapters/gemm_7_6.h
- onnx/version_converter/adapters/maxpool_8_7.h
- onnx/version_converter/adapters/remove_consumed_inputs.h
- onnx/version_converter/adapters/set_is_test.h
- onnx/version_converter/adapters/sum_8_7.h
- onnx/version_converter/adapters/type_restriction.h
As explained in #1538 and shown in #1540 the warnings generated by GCC and Clang can help to spot real bugs. An example is added enum values but forgotten handling in switch cases. Unless this is already caught by tests it will hit you to late.
This enables `-Wall -Wextra` (the most useful ones on linux) and extends `ONNX_WERROR` to acutally add `-Werror` (I assume CI does set `ONNX_WERROR=ON`)
In the last commit all warnings currently produced are fixed. Most of them were unused parameters or variables which might only have a performance impact. But on 1 case of static initialization the variable is not used and might be eliminated by the optimizer. The solution I changed this too is easier to read (no comma operator) and safe.
> Enable -Wall -Wextra -Werror for CI

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
The type of output tensor should be type of the first input tensor (the pooled input image). This change fixes it to be so.
> Fix output type bug in MaxUnpool definition.

- onnx/defs/tensor/defs.cc
- onnx/test/shape_inference_test.py
For `data_shape = [d0, d1, ..., d{r-1}]` and`indices_shape = [s0, s1, ..., s{q-1}]`, the output shape is `[d0, ..., d{axis-1}, s0, ..., s{q-1}, d{axis+1}, ..., d{r-1}]`.
> Implemented shape inference for Gather

- onnx/defs/shape_inference.h
In ./onnx/shape_inference/implementation.h:
We have
```
std::unique_ptr<GraphInferencer> new_inferencer{new GraphInferencerImpl(...)}
```
Therefore, the destructor of GraphInferencer must be virtual.
> Add a virtual destructor to GraphInferencer

- onnx/cpp2py_export.cc
- onnx/defs/nn/defs.cc
- onnx/test/shape_inference_test.py
Currently there is a bug in shape inference for `MaxUnpool` op. Specifically, the problem happens when `output_shape` input is provided. In this case, the current code checks (wrongly) the `dim_size` for `output_shape` with the `dim_size` for first input tensor. The right thing to do is to match the number of elements in `output_shape` (which must be rank 1) to the `dim_size` of first input tensor. 
This PR fixes that. I have also included two test points in `shape_inference_test.py` for this scenario.
> Fix MaxUnpool shape inference when output_shape is provided as input

- onnx/backend/test/cpp/driver_test.cc
We should comply with the requirements of the onnxifi interface for async execution of run.
@zrphercule @yinghai
> [onnxifi] Make sure that backend handles run async

- .circleci/config.yml
213 will be deleted by an automatic job soon
> Bump docker image version to 230 used in CircleCI

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
Input `indices` and `depth` do not have to be the same type. This change separates the types for the two.
> Separate types of inputs 1 and 2 in OneHot op.

- onnx/shape_inference/implementation.cc
Clang 3.8 has a detect, which cannot accept variable with compiler-generated default constructor.
This diff will fix the problem.
Reference: https://circleci.com/gh/pytorch/pytorch/291144?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> Use an empty initializer to create map

- onnx/shape_inference/implementation.cc
Otherwise, some compiler may fail to compile, e.g., https://circleci.com/gh/pytorch/pytorch/336106?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> [easy] Fix the const map initializatoin

- onnx/shape_inference/implementation.cc
- onnx/test/shape_inference_test.py
Without this change, extract_constant_to_initializer is mandatory to infer shapes from Constant node. It seems `onnx/backend/test/data/pytorch-converted/test_PixelShuffle` has `Constant` and `Reshape` for example.
> Infer shape from data in Constant nodes

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/dynamicslice.py
np.long is a platform dependent type. Replace use of np.long with np.int64.
> Replace np.long by np.int64

- onnx/backend/test/case/model/__init__.py
- onnx/backend/test/case/node/__init__.py
- onnx/backend/test/case/test_case.py
- onnx/backend/test/cmd_tools.py
- onnx/backend/test/data/real/test_bvlc_alexnet/data.json
- onnx/backend/test/data/real/test_densenet121/data.json
- onnx/backend/test/data/real/test_inception_v1/data.json
- onnx/backend/test/data/real/test_inception_v2/data.json
- onnx/backend/test/data/real/test_resnet50/data.json
- onnx/backend/test/data/real/test_shufflenet/data.json
- onnx/backend/test/data/real/test_squeezenet/data.json
- onnx/backend/test/data/real/test_vgg19/data.json
- onnx/backend/test/data/real/test_zfnet512/data.json
- onnx/backend/test/loader/__init__.py
- onnx/backend/test/runner/__init__.py
Some models, rtol=1e-3 and atol=1e-7 may be too tight. Let's enable that different models may have different rtol and atol.
> Support rtol and atol at the model granularity

- onnx/backend/test/case/model/__init__.py
since AMD and NVidia GPU's difference on the precision. Let's relax the precision on the densenet121 a little bit.
> Turn rtol to 0.002 on densenet121

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/sample/ops/__init__.py
- onnx/backend/sample/ops/abs.py
- onnx/backend/test/case/node/abs.py
- onnx/defs/gen_doc.py
Add sample implementation for Abs operator serving as example.
Sample example will serve for two purposes:
- generating more test data
- documentation
> Add sample implementation support

- onnx/shape_inference/implementation.cc
> Show string names of data types instead of int IDs

- setup.py
This PR is taken for #1563 except the line:
```
cmake_args.append('-DCMAKE_BUILD_TYPE=%s' % build_type)
```
Before this fix,  if you run 
```
pip install -e .
```
on Windows, you will find, the CMAKE_BUILD_TYPE used for generating the project is 'Release'
But the real build type used with msbuild is 'Debug'
They should be the same.
You can verify it by open CMakeCache.txt and search CMAKE_BUILD_TYPE. Its value should be 'Release'
And, in .setuptools-cmake-build, if there is a sub folder name 'Debug', then it's wrong.
> Fix: setup.py is using wrong cmake build type

- onnx/onnxifi_ext.h
- onnx/onnxifi_loader.h
Today we have onnxSetGraphIO (https://github.com/onnx/onnx/blob/9a26a21a5b8dc8ff35ca1fffb84338fe250603f9/onnx/onnxifi.h#L1874) and onnxRunGraph (https://github.com/onnx/onnx/blob/9a26a21a5b8dc8ff35ca1fffb84338fe250603f9/onnx/onnxifi.h#L1973) as two separate functions, which makes it difficult to do atomic evaluation. We would like to have a new interface onnxSetIOAndRunGraph() which basically combines two.
> [ONNXIFI]Add extension of onnxSetIOAndRunGraph

- onnx/checker.cc
- onnx/test/checker_test.py
Let's print the warning now. So people can smoothly remove the experimental ops in their models.
> Allow removed experimental ops in the checker for now

- docs/Versioning.md
- Updating released version table for ONNX 1.4.1 (IR Version 4, OpSet version 9, ONNX-ML version 1)
- Removing "ISSUE" comments from public documentation
> Versioning doc update for ONNX 1.4.1

- onnx/defs/nn/defs.cc
Forget to fix another op in the previous pr.
Treat auto_pad notset as no auto_pad,
since our newest Modelzoo onnx models still make auto_pad notset instead of removing it.
> Fix shape inference when auto_pad is notset again

- onnx/checker.cc
- onnx/test/checker_test.py
We don't have a good way to expose and integrate non-standard domain operators yet. Let's skip the schema check on the non-standard domain ops.
> Skip the schema check on ops in non-standard domain

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/averagepool.py
- onnx/backend/test/case/node/maxpool.py
- onnx/backend/test/data/node/test_averagepool_2d_ceil/model.onnx
- onnx/backend/test/data/node/test_maxpool_2d_ceil/model.onnx
It fixes Pytest errors that happen after running 'tools/update_doc.sh'
The error message appears like this:
```
_____________ ERROR collecting onnx/test/test_backend_test.py _____________
test_backend_test.py:93: in <module>
backend_test = onnx.backend.test.BackendTest(DummyBackend, __name__)
../backend/test/runner/__init__.py:67: in __init__
self._add_model_test(rt, 'Node')
../backend/test/runner/__init__.py:315: in _add_model_test
self._add_test(kind + 'Model', model_test.name, run, model_marker)
../backend/test/runner/__init__.py:233: in _add_test
'Test name must start with test_: {}'.format(test_name))
E   ValueError: Test name must start with test_: export_averagepool_2d_ceil
===========================================================================
```
> fix testcase names of maxpool_2d_ceil and averagepool_2d_ceil

- LICENSE
- community/readme.md
LICENSE formatting change is so that GitHub will auto recognize it as MIT. No change to the actual license
> Update LICENSE formatting and clarify # of WG chairs

- onnx/defs/math/defs.cc
- onnx/test/shape_inference_test.py
Recent commit changes the logic
https://github.com/onnx/onnx/blob/6de42d7d7f8ad6e601a8388147400b344b2728ea/onnx/defs/math/defs.cc#L774
to
https://github.com/onnx/onnx/blob/3717dc617fa06e4eea326e85dc0ccfdcdf4f4ab5/onnx/defs/math/defs.cc#L754
to accommodate qlinearmatmul when there are more than 2 inputs.
However it seems the logic should be
```
if (!hasInputShape(ctx, input1Idx) || !hasInputShape(ctx, input2Idx)) {
```
This is causing a bug when only one of the input does not have shape. Also these cases are not captured in the previous unit tests.
> Fix shape inference for matmul

- onnx/defs/generator/defs.cc
- onnx/defs/tensor/defs.cc
Bug fix for ConstantOfShape shape inference. mutable_shape for output should be called only when we can do the shape inference.
> Fix shape inference for ConstantOfShape op

- docs/IR.md
The acronym was being used without being defined. Thanks @shauheen for letting me know what that stands for.
> Define the IR acronym

- onnx/common/ir.h
"TypeName& operator=(const TypeName&) = delete"  may be better than "void operator=(const TypeName&) = delete"
> fix macro ONNX_DISALLOW_COPY_AND_ASSIGN bug

- onnx/defs/nn/defs.cc
- onnx/test/shape_inference_test.py
The shape inference is wrong when auto_pad is set to SAME_UPPER or SAME_LOWER and the dilation is not one, because kernel_shape rather than effective_kernel_shape is used.
The simplest model for reproducing it:
```python
import onnx
from onnx import helper, shape_inference
from onnx import AttributeProto, TensorProto, GraphProto
X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [1, 16, 16, 16])
W = helper.make_tensor_value_info('W', TensorProto.FLOAT, [16, 16, 3, 3])
Z = helper.make_tensor_value_info('Z', TensorProto.FLOAT, [1, 16, 16, 16])
conv_node_def = helper.make_node(
'Conv', # node name
['X', 'W'], # inputs
['Y'], # outputs
auto_pad='SAME_UPPER', # attributes
dilations=[2, 2],
)
id_node_def = helper.make_node(
'Identity', # node name
['Y'], # inputs
['Z'] # outputs
) …
```
> Fix bug that kernel_shape rather than effective_kernel_shape is used in dilated conv

- tools/update_doc.sh
Related issue: #2049 
1. The script echoes "Please run this script in the ONNX root folder" when "onnx/defs/gen_doc.py" _exists_.
1. The script runs `python setup.py develop` without `--user`. So the script can only be run as a root user. It's not the best practice. What's more, the script will create or edit many files, and they will be all owned by root. As a result, the regular user cannot delete, edit or git add them anymore without running chown manually.
> Fix wrong condition and add "--user" in update_doc.sh

- docs/Versioning.md
It is also needed to register the operator in `operator_sets.h` or `operator_sets-ml.h` when adding a new operator, or strange things like [this](https://github.com/onnx/onnx/pull/2057#issuecomment-497376833) will happen. However, it is not documented.
> Add a missing step for adding an operator in versioning.md

- docs/IR.md
This PR is to ensure the consistency on relations between graph's input and initializer.
Essentially, a graph's initializer is not required to be subset of the graph's input, and
any initializer not part of graph's input are considered constant definition in the graph.
> Fix inconsistency in describing graph's initializer. 

- onnx/checker.cc
Adds a newline and fixes and double space to the experimental op warning.
> Missing newline fix  

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
Issue: https://github.com/onnx/onnx/issues/1857
The output tensor should have the same rank as the input (as in [shape inference](https://github.com/onnx/onnx/blob/master/onnx/defs/nn/defs.cc#L1483))
> Fix globalpool output shape

- onnx/defs/object_detection/defs.cc
- onnx/defs/shape_inference.h
- onnx/test/shape_inference_test.py
Fix errors in RoiAlign shape inference. The existing version has the following issues:
(a) It assumes that the attributes for height and width are present, but they are optional. This will cause a null-dereference.
(b) It assumes that the input-shape dimensions are all known values, but they could be unknown or symbolic dimensions. This will cause output dimensions to be inferred as zero incorrectly.
This PR also adds shape-inference-tests to catch above two issues.
This PR also adds some utility functions to help simplify writing shape-inference.
> Fix errors in RoiAlign shape inference code

- setup.py
No need to backport
https://github.com/python/typing/issues/573#issuecomment-405986724
> Skip install typing package for python >=3.5

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
ONNX spec for gather operator does not clearly specify expectation from indices attribute. Adding this PR to clarify this ambiguity referenced in issue : https://github.com/onnx/onnx/issues/2179
> Clarify ambiguity in gather spec regarding indices out of bounds

- onnx/defs/tensor/defs.cc
Per the Squeeze op spec : "If an axis is selected with shape entry not equal to one, an error is raised." This check is not done in squeeze shape inference. Adding this PR to address this gap.
This issue is reported here: https://github.com/onnx/onnx/issues/1993
> Add check to disallow squeezing input axes which are not 1

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
It is reported that "round_prefer_floor" and "round_prefer_ceil" are not clear. "round half down" and "round half up" are commonly used terms according to wikipedia.
> Update the description of nearest_mode of resize op

- onnx/backend/test/data/node/test_cumsum_1d_reverse_exclusive/model.onnx
The test data model in **test_cumsum_1d_reverse_exclusive** was missing the exclusive attribute value. Set this value to 1 in updated model.
> Fix testdata model for CumSum. Add exclusive attribute.

- onnx/defs/tensor/defs.cc
Otherwise, we will buffer overflow. The logic is already covered by the negative axis case of Squeeze serialized test.
cc: @neginraoof @spandantiwari
> fix the buffer overflow problem in shape inference logic of Squeeze op

- docs/IR.md
- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.in.proto
- onnx/onnx.proto
- onnx/onnx.proto3
The types of inputs and outputs are required only for the top-level graph and not for subgraphs. Update the documentation to clarify this. (Also clarify documentation about variadic inputs and outputs.)
> Update documentation about required input output types

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
We should use ASCII tokens whenever possible because, for example, windows build and Linux build lead to different symbols in the current `Gather-11`.
> Avoid uses of special chars

- docs/IR.md
Minor fix in IR documentation to keep up with the relaxation that initializers need not be graph inputs. (Duplicate of the PR https://github.com/onnx/onnx/pull/2317 which was abandoned.)
> Update IR doc to clarify initializers are permitted as node inputs

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/object_detection/defs.cc
- onnx/defs/object_detection/old.cc
- onnx/defs/operator_sets.h
In opset 10, NMS doesn't produce shape. With the newly added shape inference function, some existing models can be broken due to the interaction between NSM and IF nodes (IF's then branch and else branch produce different shapes). Thus, I feel it'd be better to bump the version of NMS so that old code can still work with old models.
Because shape inference produces side information for a model, if we consider side information a part of the spec, we also need to bump operator's version each time we add a shape inference function.
> Bump NMS version for avoiding regression in existing models

- onnx/defs/math/defs.cc
Fix missing comma in exception message. Causes invalid message depending on what's in memory prior to the constant char string.
e.g. you get this:
"[ShapeInferenceError]  , 1]. Its actual value is: -10"
instead of
"[ShapeInferenceError] 'axis' must be in [-2 , 1]. Its actual value is: -10"
> Fix broken error message string formatting in softmax shape inferencing

- onnx/defs/tensor/defs.cc
- onnx/test/shape_inference_test.py
The shape inference logic basically propagated the shape of the `indices` input to the output shape. This logic is correct but we need to add a guard to make sure the `indices` input has a shape associated with it.
> Add shape existence check in GatherElements shape inference logic

- CMakeLists.txt
Fix https://github.com/onnx/onnx/issues/2481
> python_out does not recognize dllexport_decl.

- appveyor.yml
https://ci.appveyor.com/project/onnx/onnx/builds/29586926/job/0cx9q6ffptkye0cm
>ImportError: 
IPython 7.10+ supports Python 3.6 and above.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Python 3.3 and 3.4 were supported up to IPython 6.x.
Python 3.5 was supported with IPython 7.0 to 7.9.
See IPython `README.rst` file for more information:
> Fix Windows py3.5 CI

- docs/ManagingExperimentalOps.md
The 1.6 release missed adding a row for opset 11 to the table.
Many experimental operators were removed from ONNX, including dozens used in client models for published applications, which now cause warnings to be written to the console in check_node. e.g. "Warning: Affine was a removed experimental op. In the future, we may directly reject this operator...". These warnings provide no guidance on what to do though, and they're confusing to the user given frameworks like ONNX Runtime continue to support these operators anyway for backwards compatibility. Since this is related to versioning, I'm proposing to document the guidance here (note we can't it in Operators.md because these operators don't exist anymore, and we can't include it in ChangeLog.md either because all records of these …
> Update ManagingExperimentalOps.md to include deprecated operators table

- .circleci/build.sh
- appveyor.yml
For circleci, `nijna` cannot be installed with `pip>=20`, so we switch to `pip=19`. Anaconda doesn't have packages for `protobuf=3.9.2`  when `python=3.5`, so we drop python 3.5 Windows builds. I don't know if this is a long-term solution, but at least I can unblock myself with them.
> Fix circleci build and drop unsupported Windows builds

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/generator/defs.cc
- onnx/defs/generator/old.cc
- onnx/defs/operator_sets.h
- onnx/test/shape_inference_test.py
This PR follow comments https://github.com/onnx/onnx/pull/2575#issuecomment-582698230 and https://github.com/onnx/onnx/pull/2575#issuecomment-582581695 in order to allow Function operators like https://github.com/onnx/onnx/pull/2575 to promote scalar values to tensors.
This PR define new attributes `value_int`, `value_ints`, `value_float`,  `value_floats`,  `value_string`, `value_strings` that take *scalar types* for the Constant operator.
Right now scalar and tensors have two separated type systems. This do not create any trouble with operator that are implemented in backend as the backend is responsible of mixing scalars and tensors in the way he want.
But for operators defined as functions (i.e. graph) such mixing should happen directly in the defined graph. Unfortunately, we miss an …
> Allow Constant operator to promote scalar and list to tensors.

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/math/defs.cc
I think this triggers bugs in VC. So let's avoid # .
https://circleci.com/api/v1.1/project/github/pytorch/pytorch/4474680/output/105/0?file=true&allocation-id=5e444da0eb32cc36d80175e8-0-build%2F2AADD64F
```
C:\Users\circleci\project\build\win_tmp\bin\sccache.exe  cl   /TP -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -D_OPENMP_NOFORCE_MANIFEST -I..\cmake\..\third_party\benchmark\include -Icaffe2\contrib\aten -I..\third_party\onnx -Ithird_party\onnx -I..\cmake\..\third_party\googletest\googlemock\include -I..\cmake\..\third_party\googletest\googletest\include -I..\third_party\protobuf\src -Iwin_tmp\mkl\include -I..\cmake\..\third_party\eigen -IC:\Jenkins\Miniconda3\include -IC:\Jenkins\Miniconda3\lib\site-packages\numpy\core\include -I..\cmake\..\third_party\pybind11\include …
```
> Use // instead of #

- CMakeLists.txt
- appveyor.yml
- cmake/external/googletest.cmake
- cmake/unittest.cmake
1. Add conda's Library\bin folder to the PATH, because libprotobuf.dll is there.
2. Fix the protobuf version mismatch problem. Currently the C/C++ part is 3.9.2 but the python part is 3.11.3. This PR changes them to the same version: 3.11.3
3. USE_MSVC_STATIC_RUNTIME should be disabled when the libprotobuf is from conda
4. We should set the gtest_force_shared_crt variable according to the value of USE_MSVC_STATIC_RUNTIME
> Fix CI build break

- docs/Changelog.md
- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/celu.py
- onnx/defs/attr_proto_util.h
- onnx/defs/math/defs.cc
- onnx/defs/nn/defs.cc
- onnx/defs/operator_sets.h
- onnx/shape_inference/implementation.cc
- onnx/test/shape_inference_test.py
I had a look at your guidelines and tutorial for adding missing op according to https://github.com/onnx/onnx/issues/1121#issuecomment-519319483 .
The CELU operator has been required at this issue https://github.com/onnx/onnx/issues/1121 and is now part of the new operator request list https://github.com/onnx/onnx/issues/1646 .
First introduced in [Continuously Differentiable Exponential Linear Units](https://arxiv.org/abs/1704.07483) the CELU is similar to the ELU operation.
Given the attribute α, CELU is a pointwise application of the following formula:
```
CELU(x)=max(0,x)+min(0,α*(exp(x/α)−1))
```
and allow `leakage` of the gradient in the negative values, while having a differential remaining continuous for any value of alpha (which is not the case of ELU).
It is [implemented in …
> Implement CELU node as a Function

- .github/workflows/ci.yml
- CMakeLists.txt
- onnx/backend/test/case/model/__init__.py
- onnx/test/test_backend_test.py
- setup.py
To replace https://github.com/onnx/wheel-builder
Sample run: https://github.com/snnn/onnx/actions/runs/47068032
You can download the wheels from there and try it.
> Add a release pipeline for Windows python packages

- onnx/defs/math/defs.cc
- onnx/test/shape_inference_test.py
There's a bug in einsum shape inference for inferring the output rank with ellipsis in right hand side of the equation.
> Fix for einsum shape ineference

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/math/defs.cc
Add clarification on the values that labels/target values can take when `ignore_index` is specified.
> Update SoftmaxCrossEntropyLoss and NegativeLogLikelihoodLoss documentation.

- pipelines/Windows-CI.yml
Creating an Azure pipeline for Windows CI builds.
Checking in the YML file will enable us to run Azure pipelines (free for open source tools) in conjunction with current CIs (appveyor, travis, circleCI) without any breaking changes. Once we confirm everything is working well, we can start deprecating paid services / lowering to free tiers.
Builds of Azure pipelines: https://dev.azure.com/onnx-pipelines/onnx/_build
Plan: remove paid Appveyor subscription for builds by April 21, so we do not have to renew this service.
> Azure Pipelines - Windows CI

- setup.py
When building with python3 respect setuptools `--parallel` option, i.e.:
`python3 setup.py build --parallel=4` should not spawn more than 4 compiler jobs at once
Also, if neither of the options is specified, check `MAX_JOBS` environment variable
Test Plan:  `MAX_JOBS=4 pip3 install  git+https://github.com/malfet/onnx@follow-parallel-build-option` and see how many jobs are spawned
> Control build paralllelism via `--parallel` option

- onnx/defs/shape_inference.h
If input shape is unknown, propagateShapeFromInputToOutput may convert
it to a scalar shape. It is not correct. The propagation of unknown
shape should still lead to unknown shape. Below is an example which can repro this error.
```c
for (size_t i = 0; i < ctx.getNumOutputs(); ++i) {
propagateElemTypeFromInputToOutput(ctx, i + 1, i);
/*
auto typeProto = ctx.getInputType(i + 1);
if (!hasShape(*typeProto)) {
continue;
}
*/
propagateShapeFromInputToOutput(ctx, i + 1, i);
}
```
To workaround this problem, we need to uncomment the `hasShape` check. This PR includes that check in propagateShapeFromInputToOutput to make it safer.
> Fix propagateShapeFromInputToOutput

- docs/Relicensing.md
Add a document to collect approvals for relicensing ONNX repo
files from MIT to Apache-2.0
Invite organizations to add the name of their organization, the
name of the authorized approver, e.g legal, and the date the
email was received indicating the approval for relicensing.
> Relicensing MIT to Apache-2.0

- docs/Changelog.md
- docs/IR.md
- docs/Operators.md
- onnx/defs/controlflow/defs.cc
- onnx/numpy_helper.py
Add more descriptions in documents:
1. Specify that `.initializer` is not in topological order but `.node` is
2. Add a description: Subgraph input/output matching is based on order not name.
1. Users are confused about why `initializer` does not follow topological order https://github.com/onnx/onnx/issues/2860
2. Users thought the input/output of subgraph (produced by loop node) is matching by the name. https://github.com/onnx/onnx/issues/2498
> Update description for initializer in IR and Loop in operator

- .azure-pipelines/Linux-CI.yml
- .azure-pipelines/MacOS-CI.yml
In Azurepipelines all pipeline failures are not caught, with Travis CI no more being required for PR merge this is a big issue as the PRs are not accurately validated. This PR fixes error reporting for mac and linux pipelines and adds missing checks from travis pipeline to azurepipelines
> fixes for linux and mac ci pipelines

- .circleci/test.sh
https://github.com/pytorch/vision/issues/2480
The master branch of pytorch/vision needs additionally `apt install libturbojpeg`.
Old fix: https://github.com/onnx/onnx/pull/2890
However, using an old commit is a temporary solution. onnx should use the latest pytorch/vision.
> Use the master of pytorch/vision in CircleCI

- .azure-pipelines/Linux-CI.yml
- .azure-pipelines/MacOS-CI.yml
- .azure-pipelines/Windows-CI.yml
- .github/workflows/ci.yml
- .travis/script.sh
pytest 6.0.0 made deprecation warnings fail by default. Pinning pytest to 5.4.3 to fix all CI failures
https://docs.pytest.org/en/stable/deprecations.html#id5
> pin pytest version

- .azure-pipelines/Windows-CI.yml
- onnx/test/test_external_data.py
I checked the Azure Pipeline doc it seems that Microsoft-hosted agents cannot increase the memory. If we cannot enhance our CI Windows machine, the workaround might be to catch `MemoryError` as well. In that case, the test is useless on Windows, but it has been covered on Linux and Mac. (This test worked normally on them) 
https://github.com/onnx/onnx/pull/2929
`TestLarge2GBExternalData` tests 2 GB models with `onnx.checker`. However, some machines will encounter `MemoryError` because of the hardware limitation. (e.g., Azure Pipeline Windows Machine)
> Catch unexpected MemoryError for large model test on Windows-CI

- .circleci/test.sh
To prevent the link (download dependency for torch/vision) from being invalid again, it should use a stable version.
Related to https://github.com/onnx/onnx/pull/2909, the latest version of libturbojpeg becomes invalid just now.
> [CircleCI] Use stable libturbojpeg for torch/vision

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
The scales is set as Single input, it's not possible to set an empty string name for it because we have schema check for Single input(https://github.com/onnx/onnx/blob/72b701f7a55cafa4b8ab66a21dc22da0905b2f4c/onnx/defs/schema.cc#L227-L234). The doc is not correct. The only way is to set a nonempty string as the name but set it to empty data (empty shape).
Another option is to set scales as Optional input, but it requires opset version change.
> Doc update for Resize to correct some wrong information

- .azure-pipelines/Linux-CI.yml
Linux-CIs started to fail without any change of master commit. 
There might be some updates in `mypy` package or AzurePipeline.
Remove setting ONNX_NAMESPACE because it has been exported already.
https://github.com/onnx/onnx/issues/2972
> Fix Linux-CIs Failure: remove setting ONNX_NAMESPACE

- onnx/helper.py
- onnx/test/shape_inference_test.py
Add a check in make_tensor to ensure that the specified dims and the number of elements in the tensor are consistent. Fix a couple of bugs in shape-inference-tests that were violating this condition.
> Add size check to make_tensor

- docs/Optimizer.md
- onnx/optimizer/optimize.cc
ONNX Optimizer is moving to https://github.com/onnx/optimizer (https://github.com/onnx/optimizer/issues/1). A warning message should be added to suggest users use the new repo.
> Add a warning message for optimizer

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
As title. If an element in output tensor is selected from `updates`, that input element should receive gradient propagating from the output-side gradient in backward propagation. Fix #2991.
> Fix scatter family's differentiable tags

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
Pytorch has 3 specific modes for quantization
For training case the “Quantization aware training” QAT is applicable as described in the below linked page
https://pytorch.org/docs/stable/quantization.html#quantization-workflows
Snippet from the page under Quantization workflows & QAT (#3) “…Computations will take place in FP32 but with values clamped and rounded to simulate the effects of INT8 quantization…”
Code for checking QAT
https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html
> Define the differentiable variables for NN operator

- onnx/checker.cc
- onnx/helper.py
- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.in.proto
- onnx/onnx.proto
- onnx/onnx.proto3
- onnx/test/checker_test.py
Clearly specify in proto files that values name is considered a SparseTensor name.
Enforce values name is present and not empty in checker.
Enforce that the sparse tensor initializers name is unique across initializers and sparse initializers.
Add python tests.
> Improve sparse tensor support when used as sparse initializers

- onnx/helper.py
- onnx/test/helper_test.py
Duplicate of https://github.com/onnx/onnx/pull/1940 for solving the CLA and DCO issue
@calebmadrigal Thank you so much for your contribution!
**Motivation**
This fix is required for lightgbm models and needs to be in the upcoming 1.8 release hence pushing this forward
> [Dup] Changed make_attribute to allow a mix of ints and floats 

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/reduction/defs.cc
Still need to update documentation.
Signed-off-by: Svetlana Levitan <sveta_levitan@yahoo.com>
> Add differentiability indicators to reduction operators, needed for ONNX Training

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/math/defs.cc
Added the tags to about half of all Math operators.
Most math operations are clearly differentiable, at least in most points and when values are float or double.
Some can be discussed and argued either way.
I originally marked "floor" and "ceiling" as non-differentiable because their derivatives are 0 in most points and not defined for integer arguments, but PyTorch reports their derivatives as 0, and Wei-Sheng recommends marking them as differentiable.
Also, I assumed that the divisor in "mod" is fixed and hence not differentiable, let me know if that is incorrect.
@wschin
> Adding differentiability tags to Math operators, needed for ONNX Training

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/math/defs.cc
- onnx/defs/tensor/defs.cc
This PR tags `Resize` and `Compress`. This PR also changes the differentiable tags for `Round` and `Sign`. I think it's better to mark them non-differentiable until we agree a way to compute gradient at their discontinuous points. 
`Resize`:
We use Pytorch `Upsample` to understand the differentiability of ONNX `Resize`. As shown in my Python code below, there is only one differentiable input and one differentiable output. The rest parameters such as `scale` are constants and not differentiable.
```python
import torch
import torch.nn as nn
class MyModel(nn.Module):
def __init__(self):
super(MyModel, self).__init__()
self.layer = nn.Upsample(scale_factor=2, mode='bilinear')
def forward(self, x):
y = self.layer(x)
y.retain_grad()
return y
model = MyModel()
x = torch.arange(1, 5, …
```
> Add Some Differentiable Tags for The Rest Ops in tensor/defs.cc

- onnx/defs/nn/defs.cc
Correct the condition from `nullptr != auto_pad_attr` to `nullptr != auto_pad_attr && auto_pad_attr->s() != "NOTSET"`.
**Motivation**
https://github.com/jcwchen/onnx/blob/master/onnx/defs/nn/defs.cc#L1218
There is a bug in this condition. Even though the pads attribute cannot be used simultaneously with auto_pad attribute, the default value "NOTSET" is acceptable.
Thank @askhade for catching this.
> Fix Convtranspose attribute check bug: default value is acceptable

- onnx/shape_inference/implementation.cc
- Both update value_info and output for output with undefined type 
- Throw `ONNX_NAMESPACE::InferenceError` instead of `std::runtime_error`, which is more proper for debugging
**Motivation**
shape_inference used to update “undefined” output to value_info, but after this PR (https://github.com/onnx/onnx/pull/2783), if the type of output is undefined, shape_inference will directly merge inferred type into the output instead of creating a new value_info with the output’s name. It should be fine for valid models, but it will influence the behavior of invalid models (like missing output type initially).
However, part of `torch.onnx.export` replies on `onnx.shape_inference` and it only considers value_info. As a workaround, shape_inference now both updates value_info and output …
> Both update value_info and output for shape_inference undefined output

- README.md
- community/readme.md
- community/sigs.md
- community/working-groups.md
- docs/OnnxReleases.md
Hi All, I noticed that all Gitter rooms are marked as deprecated
Therefore, updated all Gitter links to corresponding Slack links
However, I did leave Gitter links associated with [Completed working groups](https://github.com/onnx/onnx/blob/master/community/working-groups.md#completed-working-groups) and [Inactive working group](https://github.com/onnx/onnx/blob/master/community/working-groups.md#inactive-working-groups) as is.
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
> Update all docs with Gitter links to Slack links

- .azure-pipelines/Linux-CI.yml
- .azure-pipelines/MacOS-CI.yml
- .github/workflows/release_win.yml
Follow up on https://github.com/onnx/onnx/pull/3106#issuecomment-725583770, with onnx deprecating support for python 2.7, modified builds to remove jobs that test python 2.7 compatability
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
> Remove python 2.7 CI build tests

- onnx/defs/schema.h
- onnx/test/cpp/function_context_test.cc
Add a default-value for type-context in FunctionBodyBuildContextImpl constructor for backward-compatibility.
This will allow users to upgrade to this version of ONNX without breaking existing usage, allowing them to add the type-context when needed.
Add a test-case to test the usage as well.
> Add default value for type-context in FunctionBodyBuildContextImpl constructor 

- onnx/defs/tensor/old.cc
https://github.com/onnx/onnx/pull/2328/ did not fix the shape inference of the old Split.
for #1735
> Fix shape inference of Split-2

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/math/defs.cc
- onnx/defs/math/old.cc
- onnx/defs/operator_sets.h
- onnx/defs/schema.h
Bump onnx opset version to 14.
Add data types of float16 and bfloat16 for inputs/outputs in CumSum operator
Signed-off-by: Tianlei Wu <tlwu@microsoft.com>
> CumSum-14:  add data types float16 and bfloat16

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
Update Pad documentation to be consistent with schema, stating the
acceptable input and output types are all tensor types, not limited
to numeric types. Also document the recommended defaults for string
and bool types.
Signed-off-by: Chin Huang <chhuang@us.ibm.com>
> Update Pad documentation to be consistent with schema

- .github/workflows/release_win.yml
- setup.py
- Sync numpy version (1.16.6) in all release pipelines. Mac and Linux were done. This PR is for Windows release pipeline.
- Set numpy 1.16.6 as the minimum install dependency.
- 
**Motivation**
https://github.com/onnx/onnx/pull/3181
To prevent potential version conflict, use fixed version numpy 1.16.6 as build dependency.
> Make Windows release use numpy 1.16.6

- README.md
Remove ppc64le daily build due to lack of practical use cases
and resources to maintain it.
Signed-off-by: Chin Huang <chhuang@us.ibm.com>
> Remove ppc64le daily build

- docs/OnnxReleases.md
- docs/Versioning.md
- onnx/common/version.h
- onnx/helper.py
Set 1.8.1 in version related files.
Fix broken url in ONNX release doc.
**Motivation**
ONNX 1.8.1 has been released.
https://github.com/onnx/onnx/issues/3287
> Set 1.8.1 in version related files

- docs/ExternalData.md
- docs/PythonAPIOverview.md
- onnx/__init__.py
- onnx/external_data_helper.py
- onnx/test/test_external_data.py
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
Update external data helpers to modify an existing function `convert_model_to_external_data` to take a `model_file_path` and `convert_attribute` to convert attributes to external data only when specified to `true` and to save the model when `model_file_path` is specified
fixes #3228 
assign @askhade for review
> Modify existing function in external data helper

- .azure-pipelines/Linux-CI.yml
- .azure-pipelines/MacOS-CI.yml
- .azure-pipelines/Windows-CI.yml
To support Python 3.6 in ONNX, fix ipython version as 7.16.1, which is the latest version for Python 3.6. Will remove it in the future once ONNX has deprecated Python 3.6.
**Motivation**
https://github.com/ipython/ipython#overview ipython 7.17+ does not support Python 3.6 anymore. It causes test errors of .ipynb. To support Python 3.6, ONNX CI will use an old version of IPython.
> Fix CI Python 3.6 failing due to .ipynb

- README.md
- setup.py
In order to display a project desctiption on PyPI, we need to adjst the Readme file to avoid relative links and add it to `setup.py` as `long_descrioption`.
> Add content of Readme to package description

- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
Even when the input shape is unavailable, the output of Shape will always be a rank-1 vector.
> [Shape inference] Always set the output of Shape to be rank-1

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
- Add another type constrain mentions more: it allows all float type for U, but backend would only impl for fp32
- Add missing bfloat16
**Motivation**
Continue the remain work from: https://github.com/onnx/onnx/pull/3402. During mixed precision training of BatchNorm, for numerical stability, in the current state, we usually keep input_mean, input_var and running_mean and running_var in fp32, while X and Y can be in fp16. Therefore we add a new type constrain for this difference.
> Add new type constrains for variance and mean in BatchNorm

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
Cherry-pick the PR of add new type constrain for BatchNorm now to prevent more opset bump in the future.
**Motivation**
We did bump BatchNorm to opset 14 for training mode. It's better to further separate the type constrain for input and mean, variance. For numerical stability, in the current state, we usually keep input_mean, input_var and running_mean and running_var in fp32, while X and Y can be in fp16. Therefore we add a new type constrain for this difference.
> [1.9.0] Cherry-pick: add new type constrains for BatchNorm 

- onnx/defs/nn/defs.cc
- onnx/test/shape_inference_test.py
- Type inference bug fix: propagate output mean/variance from input mean/variance instead of input X.
- Add a test for different types of input (X v.s. mean and variance).
**Motivation**
Since the data type of mean and variance can be different from X, the output of mean and variance should be propagated from input mean and variance instead.
> Fix Batchnorm type inference for mean and variance and add a test

- onnx/defs/nn/defs.cc
- onnx/test/shape_inference_test.py
Cherry-pick this PR: https://github.com/onnx/onnx/pull/3432 to consume type inference bug fix for BatchNorm.
**Motivation**
Fix type inference bug fix for BatchNorm
> [1.9.0] Cherry-pick type inference bug fix for BatchNorm

- docs/CONTRIBUTING.md
Let's make this clearer so people don't waste an hour (like me 😅) wondering why running the script yields no changes to Operators.md. For some reason, the much more rarely updated Operators-ml.md is the default update target when `ONNX_ML` is not defined, rather than the one everyone typically wants to update. 🙃 Also, explicitly relist the install step rather than referring back to an earlier step which is actually executed from a different directory (which confuses things).
FYI @jcwchen
> Clarify CONTRIBUTING.md documentation generation steps

- .github/workflows/release_linux_i686.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- .github/workflows/weekly_mac_ci.yml
- Install flatbuffers (ort's dependency) before pip install ort-nightly to prevent version conflict issue 
- Add `workflow_dispatch` to manually trigger CI
**Motivation**
Current release CIs are failing due to installing ort-nightly
> Fix ort failure in CI and add manually trigger

- .azure-pipelines/Linux-CI.yml
- .github/workflows/manylinux/entrypoint.sh
- README.md
Instead of 3.11.x, specify v.3.11.3 to install protobuf
**Motivation**
AzurePipelines Linux CI fails duo to wrong protobuf version installation... Somehow the branch name of 3.11.x cannot be found anymore
> Fix protobuf version in Linux-Ci to prevent version issue

- RELEASE-MANAGEMENT.md
- docs/Versioning.md
- onnx/onnx-operators-ml.proto
- onnx/onnx-operators-ml.proto3
- onnx/onnx-operators.in.proto
- onnx/onnx-operators.proto
- onnx/onnx-operators.proto3
Mostly for improved readability.
Biggest changes:
* In the operator set versioning example, remove references to the
concept of deprecation. The versioning system does not actually have
a deprecation mechanism. In the example, the operator A is not present
in operator set version 4. Models that wish to use it will have to
specify an opset version < 4.
* Clarifying what should be done to model versions
when accuracy or performance changes. The previous text did not
include any clear guidance.
> Minor improvements to versioning doc.

- onnx/checker.py
- onnx/shape_inference.py
- onnx/test/checker_test.py
- onnx/test/shape_inference_test.py
Avoids many serialization of a large model (when e.g. running it with onnxruntime)
Signed-off-by: IceTDrinker <49040125+IceTDrinker@users.noreply.github.com>
> Allow to check and run shape inference on a serialized model

- .github/workflows/manylinux/entrypoint.sh
- .github/workflows/manylinux/test_package_i686.sh
- .github/workflows/release_linux_x86_64.yml
To detect the produced wheel correctly, change the naming match for the Linux wheel. (`*-manylinux*` to `*.manylinux*`)
**Motivation**
Linux release CI fails without any related code change. This error is caused by the produced wheel cannot be detected. The naming convention of the wheel has been changed from `onnx-*.manylinux*.whl` into `onnx-*.manylinux*.whl`.
> Fix Linux release CI: Correct manylinux wheel name

- onnx/defs/tensor/defs.cc
Fixes https://github.com/onnx/onnx/issues/3515
There seem to be 2 problems here:
1) Shape inference should not give up as soon as a symbolic dimension is found, but only if the axes spec wants to act on that dimension, i.e. if it's absent or if it contains that dimension explicitly
2) In case shape inference gives up, it should not predict a rank of 0 
I have fixed (1) but (2) still remains to be addressed.
> Fix Squeeze shape inference

- .github/workflows/weekly_mac_ci.yml
- workflow_scripts/config.py
- To fix protobuf.rb not found, directly build protobuf 3.11.3 from source, just like what other CIs do
- Switch caffenet-3 and caffenet-6 in skip list due to the bug fix: https://github.com/onnx/models/pull/388
Weekly-CI has failed for a while
> Fix weekly-CI failure: correct protobuf installation and skip list

- docs/AddNewOp.md
Small change in documentation to fix a link which leads to a fork instead of main repository.
> Add new operator doc - fix broken link

- onnx/defs/quantization/defs.cc
- onnx/test/shape_inference_test.py
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- Add shape inference function to dynamic quantize linear
- Why is this change required? What problem does it solve? 
explicitly add shape inference function
fixes #3505
> Add shape inference function for dynamic quantize linear

- CMakeLists.txt
With this change when ONNX_WERROR is set to OFF none of the libs will treat warnings as error.
Removing a few explicitly disabled warnings which don't show up any more
Fixes #3530 
> honor ONNX_WERROR for all platforms and all libs

- onnx/checker.cc
- onnx/checker.h
Adding checks for opset compatibility between different model local functions and relaxing schema check in opset compatibility when the ops do not belong to onnx standard domains.
> checker updates for model local functions

- .github/workflows/release_linux_x86_64.yml
Previously apt-get version of protobuf should be an old version... To sync protobuf version in every CI, install protobuf 3.11.3 in LinuxRelease CI
Sync protobuf version in every CI
> Sync protobuf version in every CI: Install protobuf 3.11.3 in LinuxRelease CI

- onnx/defs/quantization/defs.cc
- onnx/test/shape_inference_test.py
This PR fixes the out of range bug in QuantizeLinear shape inference.
The 3rd input (y_zero_point) of QuantizeLinear is optional and can be null. Needs to check if it exists when inferring the output type.
> Fix QuantizeLinear shape inference

- onnx/backend/test/runner/__init__.py
Signed-off-by: degaochu <degaochu@cn.ibm.com>
- update function assert_similar_outputs() in onnx/backend/test/runner/init.py to support sequence/list as model/node's output.
- To fix onnx backend test failed for sequence output operators like identity operator
- fix issue https://github.com/onnx/onnx/issues/3562
> fix test_identity_sequence issue

- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.in.proto
- onnx/onnx.proto
- onnx/onnx.proto3
Change the expected behavior when an operator with the same name as model local function exists in the domain specified by the model local function.
> Update spec for model local functions

- onnx/helper.py
* Create alias make_sequence_value_info for backwards compatibility
Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>
* Add extra newline between functions to fix flake8 issue
Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>
* Add deprecation warnings for the make_sequence_value_info alias
Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>
* Update test release version to 1.9.101
Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>
* Fix more flake8 whitespace issues
Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>
> make_sequence_value_info alias for backwards compatibility (#3603)

- onnx/common/graph_node_list.h
- onnx/defs/parser.cc
Warnings fixed:
* `onnx/version_converter/convert.cc:93:63: error: implicitly-declared ‘onnx::generic_graph_node_list_iterator<onnx::Node>& onnx::generic_graph_node_list_iterator<onnx::Node>::operator=(const onnx::generic_graph_node_list_iterator<onnx::Node>&)’ is deprecated [-Werror=deprec
ated-copy]`
* `onnx/defs/parser.cc:395:11: error: this statement may fall through [-Werror=implicit-fallthrough=]`
Before this, building with `ONNX_WERROR=ON` failed for me on Linux.
After this, it succeeds.
> Fix compilation warnings.

- onnx/defs/generator/defs.cc
- onnx/defs/tensor/old.cc
- onnx/defs/tensor_proto_util.cc
- onnx/defs/tensor_util.cc
- onnx/version_converter/adapters/upsample_9_8.h
- Fix arm crash due to unaligned raw_data buffer of initializer tensors
- This issue was first reported #2813, and was reported by internal users of onnxruntime
- For now this issue only repros on arm32 but not arm64, this does not repro on x86 or x86_64
- The initializer tensors for slice are usually tensors with a single int64_t element, if the data is store in the raw_data, which is represented as a std::string, where the internal data (`std::string::c_str()`) is aligned as char*, so the reinterpret_cast<const int64_t*> of the raw_data will crash due to misalignment, (`Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN)`)
- The fix is to copy the raw_data by byte instead of copying by the destination type (`int64_t` in this crash)
> Fix arm crash due to unaligned raw_data buffer of initializer tensors

- onnx/defs/nn/defs.cc
- onnx/defs/nn/old.cc
- onnx/test/shape_inference_test.py
Fix a couple of issues with BatchNorm shape inference:
(a) Permit 1D input (for input 0)
(b) Check ranks of other inputs
See issues:
https://github.com/onnx/onnx/issues/3555
https://github.com/onnx/onnx/issues/3629
> Batchnorm shape inference

- CMakeLists.txt
- Fix build failure using XCode new build system
- XCode has 2 build systems (legacy and new), they coexist from XCode 10, see https://developer.apple.com/documentation/xcode-release-notes/build-system-release-notes-for-xcode-10
- The legacy build system will be deprecated in XCode 13, see, https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes
- ONNX build will fail if using new build system, using XCode is required to build for macOS arm and iOS, a typical failure can be seen here, https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=463519&view=logs&j=f7cc61a9-cc70-56e7-b06c-4668ca17e426&t=94d8905a-2b2a-5234-7c64-ea82d695b352
- The fix is to make `gen_onnx_operators_proto` and …
> Fix build failure using XCode new build system

- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- .github/workflows/weekly_mac_ci.yml
- docs/OnnxReleases.md
- Build and test source distribution in CI weekly (in one environment should be sufficient); Also onnx-weekly TestPyPI package will have source distribution as well
- Add a new label "test ONNX Model Zoo" to manually trigger CI testing the PR with all models from ONNX Model Zoo (use it with caution because it will waste git-lfs quota in onnx/models)
Enhance CIs
> Test source distribution in CI; Add a label for manually trigger testing ONNX Model Zoo CI

- .github/workflows/release_mac.yml
Fix weekly-CI failure (https://github.com/onnx/onnx/actions/runs/1180353371): twine upload from the right place: `dist/*.whl`.
https://github.com/onnx/onnx/pull/3666 My PR brought a wrong update: the built wheel should be under `dist/*.whl` instead of `onnx/dist/*.whl`.
> Fix weekly-CI failure: correct the path for twine upload

- .github/workflows/manylinux/test_package_i686.sh
- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- README.md
- requirements.txt
- Set minimum supported Protobuf version as 3.12 in requirements.txt
- Mention minimum supported dependencies in ReadMe
- Make CIs test with minimum supported Protobuf
https://github.com/onnx/onnx/issues/3656 The latest ONNX package doesn't work with some old protobuf package
> Set minimum supported Protobuf version as 3.12 since lower versions do not work

- onnx/shape_inference/implementation.h
ONNX 1.10 fails to compile when using older versions of `gcc`, for example on CentOS, with the following error:
```
In file included from /onnx/onnx/shape_inference/implementation.cc:5:0:
/onnx/onnx/shape_inference/implementation.h: In constructor 'onnx::shape_inference::DataPropagationContextImpl::DataPropagationContextImpl(onnx::NodeProto&, const std::unordered_map<std::basic_string<char>, onnx::TypeProto*>&, const std::unordered_map<std::basic_string<char>, const onnx::TensorProto*>&, std::unordered_map<std::basic_string<char>, onnx::TensorShapeProto>&)':
/onnx/onnx/shape_inference/implementation.h:276:47: error: invalid initialization of non-const reference of type 'std::unordered_map<std::basic_string<char>, onnx::TensorShapeProto>&' from an rvalue of type …
```
> [ONNX 1.10] Fix for compilation error on older compilers

- docs/ShapeInference.md
- docs/proposals/SymbolicShapeInfProposal.md
- Adding the proposal for symbolic shape inference. This proposal was already accepted and has been implemented in onnx 1.10 adding this for documenting the proposal in the repo.
> Add documentation for symbolic shape inf and partial data propagation

- onnx/helper.py
- onnx/mapping.py
- onnx/numpy_helper.py
- onnx/test/helper_test.py
- Add conversion float16->uint16 in make_tensor so users can simply give it a float list or numpy array
- Do the same thing for bloat16
- Add tests
https://github.com/onnx/onnx/issues/3715 Currently users need additional code to convert float16 tensor. `make_tensor` should handle the conversion to simplify the usage.
> Handle float16/bfloat16 to uint16 properly in helper functions

- community/working-groups.md
Signed-off-by: Joaquin Anton <janton@nvidia.com>
- Adds a link to the preprocessing working group in working-groups.md
- List new WG
> Add link to preprocessing WG Slack channel

- onnx/defs/tensor/defs.cc
`!hasNInputShapes(ctx, 1)` is still needed to check Shape's input. Besides, I removed `ctx.getInputType(0)->tensor_type().has_shape()` because this check is included in `!hasNInputShapes(ctx, 1)`.
https://github.com/onnx/tensorflow-onnx/pull/1731 Shape'15 crashes if the input type is not specified.
> Stricter check for Shape's input: check input type

- docs/Broadcasting.md
- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
Remove the history section. Although this is useful information, it made
it tricky to insert the broadcasting text at the right place, and it's
inconsistent with all the other operators, which don't have a history
section.
Also hide the numpy URL behind a link.
Makes it clear that the operator supports multidirectional broadcasting.
> Document that Where supports multidirectional broadcasting.

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/argmax.py
- test_argmax_no_keepdims_example
- test_argmax_default_axis_example
- test_argmax_no_keepdims_example_select_last_index
Signed-off-by: Yi-Hong Lyu <yilyu@microsoft.com>
> Fix some examples for ArgMax

- docs/PythonAPIOverview.md
- onnx/__init__.py
- onnx/compose.py
- onnx/test/compose_test.py
- Introduces a set of utilities under `onnx.compose` that help with creating combines models out of several graphs.
Usage example:
```
model_graph = ...   # Expects [N, H, W, C]
preprocessing_graph = ... # Expects [H, W, C]
preprocessing_graph = onnx.compose.expand_out_dim(preprocessing_graph, 0)
preprocessing_graph = onnx.compose.add_prefix(preprocessing_graph, 'preprocessing/')
combined_graph = onnx.compose.merge_graphs(preprocessing_graph, model_graph, [("preprocessing/data_expanded", "data")])
combined_model = onnx.compose.merge_models(m1, m2,  [("preprocessing/data_expanded", "data")], ir_version=15)
```
- ONNX preprocessing models can be distributed as separate ONNX models that are defined in terms of a single sample. ONNX compose utils can …
> Add compose utils

- onnx/shape_inference/implementation.cc
- onnx/test/shape_inference_test.py
- onnx/test/symbolic_shape_test.py
Before this change, existing `dim_param` was overwritten by generated symbols like `unk__`. `NonZero` is used to test the behavior.
We'd like to annotate output values of ops which produce unknown dims (e.g., NonZero) by pre-setting `dim_param`s of such values. However, current ONNX overwrites them.
Reproduce script:
```
import onnx
import onnx.shape_inference
import torch
class NonZero(torch.nn.Module):
def forward(self, x):
return torch.nonzero(x)
x = torch.rand(7)
torch.onnx.export(NonZero(), x, "nonzero.onnx",
output_names=["y"],
dynamic_axes={"y": {0: "NZ"}})
model = onnx.load("nonzero.onnx")
model = onnx.shape_inference.infer_shapes(model)
print(model.graph.output)  # "NZ" is overwritten by "unk__0"
```
Previous behavior:
| …
> Honor existing dim_param in shape inference

- onnx/examples/np_array_tensorproto.ipynb
- workflow_scripts/config.py
- Revert: Add caffe3 model into skip list again
- Try to retire code related to old numpy (1.13) since now ONNX requires numpy >=1.16
- Weekly-ci for testing ONNX model zoo failed due to removing caffe3 model for testing accidentally
- Linux-CI failed due to numpy
> Fix weekly/Linux CI failures: correct skip list and remove old numpy related code

- onnx/defs/nn/old.cc
- onnx/version_converter/adapters/softmax_12_13.h
ConvTranspose shape inference fails in theis example for opset 10:
```
import onnx
from onnx import helper, TensorProto, shape_inference
node = helper.make_node(
'ConvTranspose', 
['in', 'w'], 
['out'], 
auto_pad='SAME_UPPER',
strides=[2, 1]
)
nodes = [node]
inputs = [
helper.make_tensor_value_info('in', TensorProto.FLOAT, [1, 3, 7, 5]),
helper.make_tensor_value_info('w', TensorProto.INT64,  [3, 3, 2, 3])
]
outputs = [helper.make_tensor_value_info('out', TensorProto.FLOAT, [1, 3, 14, 5])]
graph = helper.make_graph(nodes, "g", inputs, outputs, [])
model = helper.make_model(graph, opset_imports=[helper.make_opsetid('', 11)])
shape_inference.infer_shapes(model)
print('ok!')
model = helper.make_model(graph, opset_imports=[helper.make_opsetid('', 10)])
shape_inference.infer_shapes(model) …
```
> Fix old ConvTranspose shape inference and softmax upgrader

- .github/workflows/manylinux/test_package_i686.sh
- .github/workflows/release_linux_i686.yml
Froze NumPy version as previous version (1.21.5) for Python 3.8 and Python 3.9.
Linux-i686-release CI is failing.
> Fix Linux i686 Release CI failure due to the latest NumPy

- docs/OnnxReleases.md
- Remind release manager to remove old onnx-weekly packages after release
- Remove old instructions (1.9) since they have been done
Space on TestPyPI is limited and onnx-weekly package keeps using more and more space because it releases packages weekly. To save space, this time I manually removed some old packages. In the future, it would be better for release managers to handle it after every release.
> Remind release manager to remove old onnx-weekly packages after release

- .azure-pipelines/MacOS-CI.yml
- .github/workflows/weekly_mac_ci.yml
- onnx/backend/base.py
- Bump to 10.15 in AzurePipeline 
- There are two more places need branch renaming
Mac-CI in AzurePipeline is failing due to unsupported 10.14
> Bump to 10.15 in AzurePipeline because 10.14 was deprecated

- .github/workflows/release_mac.yml
Remove testing ort-nightly for Mac Python 3.6 due to unsupported ort-nightly
Currently mac release CI for Python 3.6 is failing due to missing Python 3.6 ort-nightly package for Mac: https://test.pypi.org/project/ort-nightly/1.11.0.dev20220118004/
> Remove testing ort-nightly for Mac Python 3.6 due to unsupported ort-nightly

- .azure-pipelines/Windows-CI.yml
Upgrade Windows version in AzurePipeline.
vs2017-win2016 was just deprecated from AzurePipeline.
> Upgrade Windows version in AzurePipeline since 2017 was deprecated

- docs/CONTRIBUTING.md
Python 2 is not supported anymore.
> Remove documentation about Python 2.

- onnx/onnxifi_wrapper.c
Only zero out `backend_ids` if it is not `NULL`
When we run ONNX through [Cppcheck](https://cppcheck.sourceforge.io/) we get the following warning:
```
<error id="nullPointer" severity="warning" msg="Possible null pointer dereference: backend_ids" verbose="Possible null pointer dereference: backend_ids" cwe="476">
<location file="DLCpp/third_party/onnx-mlir/third_party/onnx/onnx/onnxifi_wrapper.c" line="354" column="10" info="Null pointer dereference"/>
<location file="DLCpp/third_party/onnx-mlir/third_party/onnx/onnx/onnxifi_wrapper.c" line="344" column="32" info="Assignment 'backend_ids=NULL', assigned value is 0"/>
``` 
This PR avoids the warning by only doing the memset when `backend_ids` was successfully malloced and is no longer NULL.
> Fix Cppcheck warning about memset on NULL backend_ids

- onnx/backend/test/report/__init__.py
Signed-off-by: Kevin Chen <kevinch@nvidia.com>
- Fix incorrect type annotations in backend test reporting
-  https://github.com/onnx/onnx/pull/3962 introduced type annotations, but types `pytest.nodes.Item` and `pytest.terminal.TerminalReporter` belong to `_pytest` instead of `pytest`
> [BUG] Use correct pytest types in backend

- .github/workflows/release_linux_i686.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- .github/workflows/weekly_mac_ci.yml
- .github/workflows/win_no_exception_ci.yml
- change to setup-python@v2 since it still supports Python 3.6
- Bump MSVC to 2022 because the latest machine is now Windows Server 2022
There is no Python support on GitHub action now (setup-python@v1)
> Fix Python 3.6 failure: upgrade to setup-python v2

- .github/workflows/release_linux_i686.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- .github/workflows/weekly_mac_ci.yml
- .github/workflows/win_no_exception_ci.yml
To fix CI failure, cherry pick this: https://github.com/onnx/onnx/pull/4002 first to unblock developments in the main stream.
Same as release branch (rel-1.11.0), CIs in main branch also failed due to unsupported Python 3.6 and "Visual Studio 16 2019".
> Cherry pick in the main branch: use v2 to get Python 3.6 support (#4002)

- requirements.txt
Loose NumPy requirement to grant more flexibility.
Closes https://github.com/onnx/onnx/issues/4053. Some old TensorFlow versions are not compatible with NumPy>=1.20. Recently ONNX bumped its NumPy version for building wheels: https://github.com/onnx/onnx/pull/4001 because of Python 3.10 support and resolving vulnerability issue from old NumPy. However, ONNX itself does not have strict dependency on NumPy. IMO, it should be OK to make minimum version requirement for NumPy lower to grant more flexibility for ONNX downstream repos.
cc @fatcat-z
> Loose NumPy requirement to grant more flexibility

- onnx/checker.cc
Refine the error message of checker
Old:
> Field 'shape' of type is required but missing.
New:
> Field 'shape' of 'type' is required but missing.
> refine checker message

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
Signed-off-by: Scott Cyphers <cyphers@lightmatter.co>
- Reworked the description of `Slice`.
- The intended behavior for negative values is unclear; the referenced NumPy documentation is equally unclear, as is Python's documentation.
> Clearer description of Slice

- docs/IR.md
This is consistent with current precedent. e.g. ONNX Runtime fails with "conv ... Error No Op registered for conv with domain_version of 7", as it must be "Conv".
Signed-off-by: Dwayne Robinson <dwayner@microsoft.com>
- Update IR.md to clarify op type case sensitivity.
- *Why is this change required? What problem does it solve?* To clarify behavior.
- *If it fixes an open issue, please link to the issue here.* https://github.com/onnx/onnx/issues/1934
> Clarify that op_type is case sensitive

- onnx/examples/np_array_tensorproto.ipynb
Remove unused LooseVersion
CIs for Python 3.10 failed due to additional warnings for deprecated LooseVersion. It should be removed because it is used.
> Fix Python 3.10 CI failure: Remove unused LooseVersion

- CODEOWNERS
- README.md
- Fix the broken link of Linux Foundation Slack
- Fix the typo of a code owner
Closes #4058. The code owner seems like a typo and the slack link is broken.
> Fix broken links: slack and code owner

- docs/OnnxReleases.md
Signed-off-by: Liqun Fu <liqfu@microsoft.com>
Add details on requiring onnxruntime (to update with the latest onnx) and fixing bugs detected with onnruntime ci pipeline runs. 
- To better estimate onnx release timeline and effort. Testing with onnxruntime makes onnx release more stable.
> update release process with more onnxruntime update details

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
When `axis=1`, and `k = indices[i_{0}, ..., i_{q-1}]`
the Gather op should have output
`output[j_{0}, i_{0}, ..., i_{q-1}, j_{1}, ..., j_{r-2}] = input[j_{0}, k, j_{1}, ..., j_{r-2}]`
instead of 
`output[i_{0}, ..., i_{q-1}, j_{0}, ..., j_{r-2}] = input[j_{0}, k, j_{1}, ..., j_{r-2}]`
This avoids confusion when people read the Operator doc.
#3640
> Fix a minor typo in operator Gather documentation

- docs/ShapeInference.md
Signed-off-by: Ganesan Ramalingam <grama@microsoft.com>
Update the shape-inference documentation.
Helps developers who write shape-inference code for operators avoid some common mistakes.
> Update shape inference documentation

- onnx/version_converter/convert.h
Fix version_converter crash: use %d to print integer
Closes https://github.com/onnx/onnx/issues/4178. Current version_converter crashes when the target version is higher than the latest opset_version.
> Fix version_converter crash: use %d to print integer

- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.in.proto
- onnx/onnx.proto
- onnx/onnx.proto3
* Use reserved keyword rather than comments.
* Remove trailing white-space.
* Add missing space before `=`.
> Clean up protocol buffer definitions

- .azure-pipelines/Linux-CI.yml
- .azure-pipelines/MacOS-CI.yml
- .azure-pipelines/Windows-CI.yml
Ignore input.pb consistency check for test generation in CIs
https://github.com/onnx/onnx/pull/3855 brought test generation consistency check in CIs. However, it will also check generated input.pb. It's possible that input uses numpy.random, which might behave differently on different platforms.
> Ignore input.pb consistency check for test generation in CIs

- onnx/helper.py
- onnx/mapping.py
- onnx/numpy_helper.py
- onnx/test/helper_test.py
**Fix bf16 Support**
Fix bfloat16 support in helper and numpy_helper.py. 
Without native bfloat16 support in numpy implementing bfloat16 support for ONNX is a bit complicated. Recently support was added by encoding bfloat16 as float16. this is not correct as this is a lossy encoding; it's also a bit confusing as a design and indeed broke some bespoke tools on my end that didn't expect the bfloat16 to be encoded as float16 in the ONNX file.
I've implemented some changes here that give rudimentary support (not completely broken) but i do have a two questions that i believe need to be answered before committing these changes.
1. what is the proper binary encoding of bfloat16 in ONNX protobuf format (is this documented? should it be?)
2. it appears that "raw" …
> Fix bf16 Support

- onnx/helper.py
- onnx/mapping.py
- onnx/test/helper_test.py
- The map in TENSOR_TYPE_TO_NP_TYPE is the "used" NumPy type instead of "stored" NumPy type. 
- Fix a mapping bug in make_tensor for raw. It should use storage type instead.
- Add comments for confusing maps: TENSOR_TYPE_TO_NP_TYPE and TENSOR_TYPE_TO_STORAGE_TENSOR_TYPE
(*Updated)
There are two similar maps in mapping:
- TENSOR_TYPE_TO_NP_TYPE: which NumPy type you will use to create such a TensorProto. Take float16 as an example, you can directly use numpy.float16 as values for make_tensor.
- TENSOR_TYPE_TO_STORAGE_TENSOR_TYPE: which ONNX Tensor type wou will use to "store" such a TensorProto. Take float16 as an example again, by model proto definition, you should use "TensorProto.UINT16" to store "TensorProto.FLOAT16".
Based on the float16 example, I think the map for …
> Fix mapping TensorProto to NumPy for bfloat16

- onnx/helper.py
- onnx/mapping.py
- onnx/test/helper_test.py
* fix mapping for bfloat16
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>
* fix typo
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>
* remove old comments
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>
* use storage_type for expected size instead
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>
* nit: add comments for maps
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>
* better comments for maps
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>
(cherry picked from commit c2825db5276419cf74c0f23dd3dea8fd5ef7adad)
> Fix mapping TensorProto to NumPy for bfloat16 (#4234)

- README.md
`pip` and `conda` handle installing the prerequisites.
> Remove prerequisites from installation instruction

- .github/workflows/manylinux/entrypoint.sh
- docs/Changelog-ml.md
- docs/Changelog.md
- docs/MetadataProps.md
- docs/Operators-ml.md
- docs/Operators.md
- docs/TypeDenotation.md
- onnx/compose.py
- onnx/defs/controlflow/defs.cc
- onnx/defs/controlflow/old.cc
- onnx/defs/nn/defs.cc
- onnx/defs/nn/old.cc
- onnx/defs/schema.h
- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
- onnx/defs/traditionalml/defs.cc
- onnx/defs/traditionalml/old.cc
- onnx/test/helper_test.py
- onnx/version_converter/adapters/scan_9_8.h
Fix some typos.
Fix some typos for doc and comments.
> Fix some typos.

- onnx/shape_inference/implementation.cc
Fix crash: only traverse graph to add symbols if symbol table presents
To clarify: it is unrelated to data propagation and TraverseGraphsToAddExistingSymbols was included in the basic shape inference to enable shape inference to infer symbolic shapes for unknown dimensions. After it was added, ONNX graph-level shape inference "always" traverses the whole graph to add existing symbols so current ONNX always presents symbol_table.
However, it's possible that some users rely on C++ ONNX shape inference code and they don't want to infer symbolic shapes at all by making symbol_table as nullptr. ONNX shouldn't crash for that case. Therefore, **checking nullptr for symbol_table every time before dereferencing symbol_table is required.**
Possible further …
> Fix crash: only traverse graph to add symbols if symbol table presents

- onnx/defs/schema.cc
- onnx/test/checker_test.py
Revert #3979: Checker should validate the node's inputs/outputs have names when Variadic
It seems possible that some operators set Variadic for some dynamic situations. For instance, PythonOpGrad from ORT might have an empty input for Variadic input. To unblock the failure right before the release, loosen the onnx.checker for now. Going forward, we should consider to make the check only for Loop op. Reopen issue #3969 for future tracking.
> Revert #3979: Checker should validate the node's inputs/outputs have names when Variadic

- onnx/common/ir.h
Add `Graph::is_constant_initializer(const Value*) const` in ir.h
I'm developing [onnx optimizer](https://github.com/onnx/optimizer) and find that it is helpful to have an `is_constant_initializer` method to check whether a Value is an initializer but not an input (a.k.a. a [constant initializer](https://github.com/onnx/onnx/blob/main/docs/IR.md#graphs)). Only constant initializers can be safely eliminated or fused.
> add is_constant_initializer in ir.h

- onnx/utils.py
Signed-off-by: Kyle Sayers <kylesayrs@gmail.com>
This change decreases `extract_model`'s run time by first checking for a non-matching node_output_name and then checking if the node has been reached yet. The speedup is because, for each node, the number of `node.output`s is likely to be small while the number of `reachable_nodes` can be quite large.
- This change solves run time issues which severely limits the practical usefulness of `extract_model` for large graphs
- Use cases such as zero shot embedding pipelines benefit from being able to dynamically and quickly extract models
> [Ready to Merge] extract_model run time optimization

- onnx/__init__.py
Add detailed error message for saving 2GB proto.
Currently saving 2GB proto will simply get complaint from Protobuf.  To improve user experience, ONNX should suggest a possible solution in the error message.
cc @BowenBao not sure whether it is the right improvement you are looking for. Please review it. Thanks!
> Add detailed error message for saving 2GB proto

- README.md
Signed-off-by: Joaquin Anton <janton@nvidia.com>
- Clarify the minimum version required of ONNX in the README.md. As older Ubuntu users will get not compatible versions of protobuf when installing from the ubuntu repositories.
- Avoid confusion.
> Clarify minimum version of Protobuf required by ONNX

- .github/workflows/lint.yaml
pyflakes does not support diff_context, creating too much noise. So we disable it.
- Set diff_context in all other checks
- We do not need to reenable pyflakes because flake8 is supposed to include pyflakes. We just need to configure properly
> Remove pyflakes from CI

- onnx/test/shape_inference_test.py
- onnx/utils.py
- requirements-dev.txt
- setup.py
flake8 [released](https://pypi.org/project/flake8/#history) 5.0.0 and 5.0.1 these days, making the CI fail: https://github.com/onnx/onnx/pull/4385 https://github.com/onnx/onnx/pull/4395.
This PR fixes errors it reported, and uses flake8==5.0.1 instead of always using the latest version.
> Fix errors reported by flake8 5.0.2

- docs/IR.md
- onnx/helper.py
- Adds `onnx.helper.make_attribute_ref` to create parent function attribute references.
- Explains the mechanism of passing attribute references in `IR.md`.
- When developing code generating ONNX models, supporting the function specification requires attribute references. This  PR helps clarify the expected method for doing this.
- Fixes #4374
> Clarify and add helper for making attribute references

- docs/CONTRIBUTING.md
Update contributor guidelines to note cpp tests require linking to built libraries (i.e. ONNXIFI_DUMMY_LIBRARY). 
- The cpp tests fail when running locally for me.
- The ci scripts also set LD_LIBRARY_PATH
> add docs for cpp tests requiring built libraries

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
Signed-off-by: Yuan Yao <yuanyao@nvidia.com>
Add more details for conversion among numerical types for the Cast op
In the previous version of the spec for Cast, not much detail is given for out-of-range conversion among numerical types. Here we explicitly list all the pair-wise conversions and indicate when to expect undefined behavior.
Suggestions are welcome for conversions to/from string types, from people to whom string conversions are relevant.
> Specify pairwise conversion behavior for the Cast op

- onnx/common/ir_pb_converter.cc
origin annotation in onnx/onnx/common/ir_pb_converter.cc
https://github.com/onnx/onnx/blob/eb634addcbb23ec1baf4d548d826bf3932527533/onnx/common/ir_pb_converter.cc#L229-L234
this pull request replace the second label "5)" with "6)"
Fix annotation mistaken
> Modify the annotation: fix the label serial number mistake

- .git-blame-ignore-revs
Ignore the format PR(fddb2b6d4ea3fb3dba751d884865042503260899) in git blame
So that github does not show the formatting PR in blame which obscures the history.
> Ignore the format PR in git blame

- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- .github/workflows/weekly_mac_ci.yml
- .github/workflows/win_no_exception_ci.yml
- In Windows CI, use the fixed Python version 3.10.5 as Python 3.10 for now because Python 3.10.6 is missing some compiler tools like BLAS/MKL for building NumPy from source
- Upgrade to setup-msbuild@v1.1
- Upgrade to setup-python@v4
- Remove if condition for skipping ORT with Python 3.10 because the latest ORT has supported Python 3.10.
Fixes https://github.com/onnx/onnx/issues/4439.
> Fix Windows Release Python 3.10 CI failure when building NumPy from source

- README.md
- community/readme.md
- community/sigs.md
Remove sentences about deprecated onnx-docker in docs.
https://github.com/onnx/onnx-docker was just deprecated recently. Related sentences in the documents should be updated.
> Remove sentences about deprecated onnx-docker in docs

- onnx/checker.cc
- onnx/checker.h
- onnx/shape_inference/implementation.cc
- To prevent confusion, make check_model always not modify the model.
- Use `LoadProtoFromPath` to simplify duplicate code.
After this PR, all check_model with full_check Python/C++ APIs won't update the model in place. 
Fixes https://github.com/onnx/onnx/issues/4422. Follow-up work for https://github.com/onnx/onnx/pull/4386.
> Make check_model with full_check always not modify the model in place

- onnx/defs/math/defs.cc
- onnx/defs/quantization/defs.cc
- onnx/defs/quantization/old.cc
- onnx/defs/shape_inference.h
- onnx/defs/tensor/utils.cc
See https://github.com/onnx/onnx/issues/4447 for a discussion.
> Add hasInput method to InferenceContext

- .azure-pipelines/MacOS-CI.yml
- .github/workflows/release_mac.yml
- Upgrade macOS in azp due to upcoming deprecation.
- Make all release pipelines use the latest OS and let Azurepipelines use older OS to enhance test coverage.
Upcoming deprecation:
```
This is a scheduled macOS-10.15 brownout. The macOS-10.15 environment is deprecated and will be removed on September 30th, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5583
The remote provider was unable to process the request.
```
Currently it fails occasionally.
> Upgrade macOS in azp due to upcoming deprecation

- .github/workflows/release_win.yml
- CMakeLists.txt
- README.md
- onnx/checker.cc
- onnx/common/path.cc
- onnx/common/path.h
- onnx/test/cpp/common_path_test.cc
- onnx/test/shape_inference_test.py
- onnx/test/test_external_data.py
- onnx/utils.py
Cherry-pick https://github.com/onnx/onnx/pull/4400 and https://github.com/onnx/onnx/pull/4470 for 1.12.1. It will be used for updating ONNX commit in ONNX Runtime to solve vulnerability issue while loading external tensors from files outside the directory.
With the base of rel-1.12.0, cherry-pick https://github.com/onnx/onnx/pull/4400 and https://github.com/onnx/onnx/pull/4470 to solve vulnerability issue while loading external tensors from files outside the directory.
> [1.12.1] Solve vulnerability issue while loading external tensors

- onnx/backend/test/case/node/__init__.py
Signed-off-by: Liqun Fu <liqfu@microsoft.com>
avoid modifying node when creating test cases
An operator node is used to create test cases.  Sometimes a node is used to create multiple test cases. This requires that the node is immutable when creating a test case. This is especially true when a test with default attributes. In this PR, change is added to avoid default attributes being added to the original node which will cause subsequent test case creation failure.
This bug was detected when changing ReduceSumSquare to function op. When extended cases were created, a attribute of empty attribute was added to the original node which cause the next test case to fail.
> avoid modifying node when creating test cases

- README.md
Signed-off-by: JackBoosY <yuzaiyang@beyondsoft.com>
`onnx` is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `onnx` and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `onnx`, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/onnx/portfile.cmake). We try to keep the library maintained as close as possible to the original library. :)
> Add vcpkg instruct step

- docs/PythonAPIOverview.md
- onnx/helper.py
- onnx/mapping.py
- onnx/numpy_helper.py
- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.in.proto
- onnx/onnx.proto
- onnx/onnx.proto3
- onnx/test/helper_test.py
- Add missing case for SequenceProto.MAP in numpy_helper.to_list.
- Fix issue onnx/issues/4552, make `tensor_dtype_to_field` not throw deprecation warning by introducing a identical dictionary `_STORAGE_TENSOR_TYPE_TO_FIELD`. Same case for `NP_TYPE_TO_TENSOR_TYPE`.
- Partially fix https://github.com/onnx/onnx/issues/4549: enable `printable_attribute` to handle bfloat16.
Recent https://github.com/onnx/onnx/pull/4270 refactored existing code, but I forgot to add the case for SequenceProto.MAP in to_list.
cc @gramalingam Please review this PR. Sorry that I should catch this in advance before my PR got merged. Thank you!
> Fix several issues regarding recent mapping update

- .github/workflows/codeql.yml
- .github/workflows/lint.yaml
- .github/workflows/pages.yml
- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- .github/workflows/weekly_mac_ci.yml
- Build onnx in page creating CI with the full prerequisite such as upgrading pip, installing shared protoc, setting config.
- All CIs use the same version of actions/checkout@v3
The CI of Deploy static content to Pages is still failing because ONNX was not built successfully.
> Build onnx in page creating CI

- .github/workflows/pages.yml
Manually catch build succeeded for page creating CI.
pages.yml still failed because it cannot detect build succeeded with warnings. See more details [here](https://github.com/onnx/onnx/pull/4570#issuecomment-1268809300).
> Manually catch build succeeded for page creating CI

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
Clarify a couple of issues in ScatterND documentation (see https://github.com/onnx/onnx/issues/4548).
* Negative index values are allowed.
* Delete outdated comment about duplicate indices.
> Update ScatterND documentation

- .azure-pipelines/Linux-CI.yml
- .github/workflows/pages.yml
- docs/OnnxReleases.md
- Only manually trigger page deployment
- Update release document to let release manager manually deploy it after every release
- Remove duplicate code style check in Linux-CI. Going forward it will be done by another required CI: https://github.com/onnx/onnx/blob/4637098e881d0d2f63caa5e945a9fdc620e11e06/.github/workflows/lint.yaml#L83.
- Currently the website will be updated after every main branch push. For now we only want to trigger it manually with the stable released content.
- https://github.com/onnx/onnx/blob/4637098e881d0d2f63caa5e945a9fdc620e11e06/.github/workflows/lint.yaml#L83 now enforce-style is required. Remove the same check in Linux-CI.
> Only manually trigger page deployment and remove duplicate style check in Linux-CI

- onnx/defs/traditionalml/defs.cc
- onnx/test/shape_inference_test.py
Adds/extends type & shape inference for operators in `ai.onnx.ml`:
- `CategoryMapper`
- `TreeEnsembleRegressor`
- `TreeEnsembleClassifier`
Traditional ML operators under `ai.onnx.ml` tend to be lacking in type and shape inference.
There is still a need for improving documentation for these operators and extending inference for other operators. They also generally lack sanity-checking whether they are properly specified - for example for the tree ensemble family, where there's a lot of attributes and almost no checking is done.
As a general note, adding new inference/verify functions is a bit of a pain. There's a lot of somewhat generic patterns (attributes of equal length, only one of attribute group is set, make dimensions equal to given shape list) that seem to be done really …
> Add type inference for CategoryMapper & TreeEnsembleRegressor/Classifier

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
Clarify the documentation of MaxPool operator to explain why the storage-order attribute is used. (See https://github.com/onnx/onnx/issues/2290 ).
> Update maxpool doc

- .github/workflows/codeql.yml
Use Python 3.10 is CI job CodeQL.
Job CodeQL Is using the latest python to check style. It recently became Python 3.11 but this needs PR #4490.
> Use Python 3.10 in CI job CodeQL

- onnx/backend/test/report/coverage.py
`tabulate` function doesn't add new line to last row so it will be mixed up with next pytest summary
Without this, the pytest summary would be broken like following:
```
...
Tanh                   No attributes
ThresholdedRelu        alpha: 1
Tile                   No attributes
TopK                   axis: 2
largest: 1
sorted: 1
Transpose              perm: 9
Trilu                  upper: 1
Xor                    No attributes
PRelu                  No attributes============================= 1100 passed, 985 skipped, 80 xfailed, 1400 warnings in 11.72s ==============================
```
> Output missing last new line from coverage reporter

- onnx/backend/base.py
Fix enforce-style CI error: solve empty-body issue raised by mypy 0.990
Currently enforce-style CI failed due to the latest mypy 0.990
> Fix enforce-style CI error: solve empty-body issue raised by mypy 0.990

- docs/docsgen/source/intro/concepts.rst
In line 54,
Changed y = onnx.Add(ax, c) to y = onnx.Add(r, c)
Signed-off-by: Anand Krishna <51157561+AnandKri@users.noreply.github.com>
> Fixed Typo in concepts.rst

- .github/workflows/release_mac.yml
Only submit source distribution in one CI (Python 3.10 + x86_64)
Only "one" CI will submit source distribution weekly to TestPyPI. After adding universal2 support, we should filter it out for the action of source distribution.
> Fix weekly mac release CI: only submit source distribution in one CI

- docs/docsgen/source/intro/python.rst
In line 23 there was an extra closing brace.
Signed-off-by: Ishan Singh <86545965+Ishan-cmd@users.noreply.github.com>
> Fix typo in python.rst

- docs/docsgen/source/intro/python.rst
Signed-off-by: Armen Gabrielyan <armengabrielyan16@gmail.com>
This is to remove unused imports from Python code examples.
Dead imports does not provide any value.
> Remove unused imports from code examples

- docs/docsgen/source/onnx_sphinx.py
ai.onnx.ml are missing from page: https://onnx.ai/onnx/operators/. It was broken by PR: https://github.com/onnx/onnx/pull/4753.
> Fix missing page for ai.onnx.ml domain

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
Fixes issue #4799. Removes an empty line confusing the markdown parser. Changes can be seen [here](https://github.com/xadupre/onnx/blob/changes/docs/Changelog.md#batchnormalization-15).
> Fix pages Changes.md

- community/readme.md
- community/repo_guidelines.md
Signed-off-by: Andreas Fehlner <fehlner@arcor.de>
* Reduce redundancy
* Make it easier for new interest to find out which structure and working groups are currently active (rather than highlighting the historical structure) 
* Adapting to the circumstances. (e.g. the Steering Committee Repo should belong to the SC and not to a SIG).
PR as decided at the SC meeting of 1/18/2023.
> cleanup in governance file

- onnx/test/reference_evaluator_backend_test.py
A skipped backend test is now passing with the reference implementation after #4769 is merged.
Increase test coverage.
> Unskip a backend test in the list supported by the reference implementation

- README.md
Previous badges didn't show what platform the pipeline was for.
> update CI pipeline badges to include name of pipeline platform

- .azure-pipelines/Linux-CI.yml
"The Ubuntu 18.04 Actions runner image will begin deprecation on 2022/08/08 and will be fully unsupported by 2023/04/01"
https://github.com/actions/runner-images/issues/6002
Does python 3.7 work with ubuntu 20.04 ? should not make a difference?
Signed-off-by: Andreas Fehlner <fehlner@arcor.de>
> Update Linux-CI.yml. Ubuntu18.04 deprecated (unsupported by 2023/04/01)

- .github/workflows/weekly_mac_ci.yml
Fix `python setup.py install` failure after this PR: https://github.com/onnx/onnx/pull/4772.
Error when `python setup.py install`:
```
/Users/runner/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
warnings.warn(
No local packages or working download links found for onnx==1.14.0
error: Could not find suitable distribution for Requirement.parse('onnx==1.14.0')
Error: Process completed with exit code 1.
```
> Fix python setup.py install failure in weekly pipeline

- onnx/defs/parser.cc
- onnx/test/cpp/parser_test.cc
The parser does not handle non-tensor types used in graph input/outputs. Fix the bug.
> Fix parser bug in handling non-tensor types

- .github/workflows/scorecard.yml
Signed-off-by: Andreas Fehlner <fehlner@arcor.de>
Add the scorecard github action to monitor / improve security
Currently we use or pass the "Best Practices" according to the Open Source Security Foundation (OpenSSF) by self-declaration. 
The project Insights of the Linux-Foundation https://insights-v2.lfx.linuxfoundation.org/lfai-onnx/overview shows points we can improve.
One point is "Security" and at the OpenSSF there is another project that deals with security that I would like to introduce. (https://github.com/ossf/scorecard)
I prefer the projects of OpenSSF compared to others because we already "use" OpenSSF and it is also a project of the Linux Foundation. 
When it is integrated, I will make other changes to make it better for example in our readme (to show the badge...) and to …
> Introduce scorecard.yaml (OpenSSF Scorecard - Security health metrics for Open Source)

- requirements-dev.txt
Remove non-required pyzmq due to different license
The license for pyzmq may not be compatible with our ONNX license
> Remove non-required pyzmq due to different license

- docs/docsgen/source/onnx_sphinx.py
Render types as inline code.
Before
After
-----
Doc readability
> Sphinx type name rendering

- onnx/common/path.cc
- onnx/common/path.h
- onnx/onnx-operators-ml.proto
- onnx/onnx-operators-ml.proto3
- onnx/onnx-operators.in.proto
- onnx/onnx-operators.proto
- onnx/onnx-operators.proto3
* correct license information in built proto files (original onnx.in.proto already had the correct license information)
* Add spdx license to cc / h files
These files where also highlighted at the fossology scan from the linux foundation. (mail could be found at https://lists.lfaidata.foundation/g/onnx-technical-discuss/topic/96811486)
> replace MIT with Apache-2.0

- onnx/reference/ops/op_non_zero.py
- onnx/test/test_backend_reference.py
Fix Windows x86 pipeline failure: handle NumPy behavior in reference:
- Disable float_to_bfloat test cases
- Specify np.int64 for np.nonzero(x)
Fix Windows x86 pipeline failure:
```
FAILED onnx/test/test_backend_reference.py::OnnxBackendNodeModelTest::test_cast_FLOAT_to_BFLOAT16_cpu - TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
FAILED onnx/test/test_backend_reference.py::OnnxBackendNodeModelTest::test_castlike_FLOAT_to_BFLOAT16_cpu - TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
FAILED onnx/test/test_backend_reference.py::OnnxBackendNodeModelTest::test_c …
```
> Fix Windows x86 pipeline failure: handle NumPy behavior in reference

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/reduction/utils.cc
Clarify that the input of a reduction op can be a rank-0 tensor.
There seems to be some confusion whether this is valid or not. The interpretation and return-value are straightforward with no ambiguity. So, clarify this explicitly.
> Clarify reduction op inputs can be rank-0 tensors (scalars)

- workflow_scripts/config.py
Enable version_conversion for 12 to 13 for ONNX Model Zoo models which have opset_version 12.
Follow-up after https://github.com/onnx/onnx/pull/4974. The version_conversion issue of Softmax has been resolved.
> Enable version_conversion for 12 to 13 with ONNX Model Zoo models

- onnx/reference/ops/op_deform_conv.py
`numpy.float` is deprecated in latest numpy version. Change it to `float` instead. This error was not caught by the previous [PR ](https://github.com/onnx/onnx/pull/4783) pipeline but by the release CI pipeline after merge.
> fix numpy type in DeformConv python implementation

- docs/docsgen/source/onnx_sphinx.py
LayerNormalization has context dependent function but it's documented as non function in sphinx generated doc: https://onnx.ai/onnx/operators/onnx__LayerNormalization.html
> Also use `has_context_dependent_function` in sphinx document

- requirements.txt
Do not set minimum required NumPy version in requirements.txt to grant the most flexibility for NumPy versions. For release onnx package, higher and safer NumPy version are using now: https://github.com/onnx/onnx/blob/main/requirements-release.txt.
An alternative is just bumping minimum required NumPy version, but it's possible that in the future another user complains onnx cannot work with an old version of NumPy. Actually unlike Protobuf, onnx itself does not have "hard requirement" about NumPy version, it seems fine to me we can provide more flexibility for required NumPy version with ONNX and let users decide which NumPy version they want to use with onnx. From ONNX official package perspective, the wheel will still be built with a higher version of NumPy, which is safer and more …
> Do not set minimum required NumPy version in requirements.txt

- onnx/version_converter/convert.cc
Removes `std::cerr` prints directly into STDERR whenever `version_converter` encounters ops outside `ai.onnx`. 
For now, the prints are kept behind an `if (DEBUG)` similar to some other ones in the same function. This is to make this change as smooth as possible. They can be removed entirely in the future, as the function could be refactored anyway (what are "ConstantFill", "Undefined", "Captured" ops? I've never seen them)
Though `version_converter` might usually be used in an interactive context, Spox uses it often programmatically. The current prints pollute the standard output log and the are confusing as they are not properly labelled with traceback. 
I would appreciate merging this before the code freeze a lot!
> Remove `stderr` prints in `version_converter`

- onnx/defs/schema.h
onnx/defs/schema.h forgot to include <map> header file, but the file uses std::map
Make it be compatible with the latest protobuf code.
> Fix some build errors with the latest protobuf version

- onnx/defs/schema.h
Restore functions removed in PR #5123 as deprecated. That avoids breaking packages taking a dependency on the C++ API.
> Deprecate function with suffix _with_bfloat

- onnx/__init__.py
Add `__all__` to `__init__.py`
API clarity and control. Intelisense will be able to tell what is exposed. Previously it often complains that "TypeProto is not exposed in onnx" etc.
> Add __all__ to __init__.py

- .lintrunner.toml
- requirements-dev.txt
So running `lintrunner` now means `lintrunner -m main`, which is easier.
https://github.com/suo/lintrunner/commit/75ea9c09cd6904e6e53170af0661fd3dcb39c9e9#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fc
cc @jcwchen
> Update .lintrunner.toml to include a merge base

- .github/workflows/clang_tidy_review.yml
- .github/workflows/clang_tidy_review_post.yml
Fix clang-tidy CI: use v0.12.3 to enable comment from forks
Apply fix from https://github.com/ZedThree/clang-tidy-review/issues/82.
> Fix clang-tidy CI: use v0.12.3 to enable comment from forks

- docs/docsgen/source/api/hub.rst
Document missing hub functions in Python documentation
> Extend python API documentation

- docs/docsgen/source/conf.py
Display math in docs with mathjax
| Before | After |
| - | - |
| <img width="778" alt="image" src="https://user-images.githubusercontent.com/11205048/232920682-a13811a4-28f8-4985-86c8-b57be6d134ad.png"> | <img width="788" alt="image" src="https://user-images.githubusercontent.com/11205048/232920636-dc7fcc96-9657-4606-b416-23f89c77082d.png"> |
cc @jcwchen @xadupre
> Display math in docs

- workflow_scripts/config.py
Skip preprocessing model for testing version_converter due to unknown domain: local.
Weekly CI for testing ONNX Model Zoo failed because preprocessing model has unknown opset domain: local. The version conversion is not completed: the converted model is wrong -- `resnet-preproc-v1-18.onnx failed because: Field 'type' of 'value_info' is required but missing.`
> Skip preprocessing model for testing version_converter due to unknown domain 

- .github/workflows/clang_tidy_review.yml
- .github/workflows/clang_tidy_review_post.yml
- Fix permission to enable write access for PRs
- Bump versionas  v0.13.0 for clang-tidy-review
Try to fix https://github.com/onnx/onnx/issues/5093.
> Fix permission and bump version as v0.13.0 for clang-tidy-review

- .github/workflows/lint.yml
- .lintrunner.toml
- requirements-dev.txt
- requirements-lintrunner.txt
RUFF can now format since lintrunner-adapters v0.8. Removed the RUFF-FIX linter
> Enable RUFF as a formatter

- .github/workflows/lint.yml
So that it is able to post sarif code scan results.
cc @jcwchen
> Add security-events permission to the lint action

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
referring to https://github.com/onnx/onnx/blob/main/onnx/defs/tensor/defs.cc#L2676-L2683
Onehot operator should support scalar and tensor with rank 1 both for depth input.
Previous PR by my teammate was [here](https://github.com/onnx/onnx/pull/5193). I made the changes mentioned by @xadupre in that PR: modified Operators.md, built the package and ran gen_doc.py, and signed the commit.
> Modify OneHot operator explanation

- .github/workflows/pages.yml
To fix CI failure for doc generation, pin Python Protobuf version as 3.20.2 for now.
Fix CI failure for doc generation. The root cause is Protobuf compatibility issue. (protoc from apt-get is not compatible with Python Protobuf>=4.21)
> Pin Python Protobuf version as 3.20.2 for documentation generation CI

- docs/OnnxReleases.md
- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.in.proto
- onnx/onnx.proto
- onnx/onnx.proto3
Update the latest IR release date: IR VERSION 9 published on May 5, 2023.
Although previously onnx only updated its TBD date when there is a newer IR bump in future release, it seem better and harmless to me that we can update the proto files right after the fresh IR bump for better documentation.
> Update the latest IR release date: IR VERSION 9 published on May 5, 2023

- setup.py
Described by https://github.com/onnx/onnx/issues/5194
Since `python setup.py build` works fine, I compared the `os.environ` and found that `pip install -e .` add a strange `PYTHONPATH` to `os.environ`. Deleting it make the installation working fine.
> Fix ModuleNotFoundError: No module named 'cmake'

- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- requirements-release.txt
Stop uploading onnx-weekly package to TestPyPI. Only keep uploading onnx-weekly package to PyPI.
Closes https://github.com/onnx/onnx/issues/4930.
> Stop uploading onnx-weekly package to TestPyPI

- onnx/test/test_backend_onnxruntime.py
Skip not implemented failures for tests with ORT 1.15. 
Currently onnxruntime related tests failed, because ORT 1.15 was just out recently and some new operators are not implemented yet in ORT 1.15. (pending PR: https://github.com/microsoft/onnxruntime/pull/14731)
> Skip not implemented failures for tests with ORT 1.15

- .github/dependabot.yml
So that lintrunner and other dependencies are updated. We can simply ignore the PRs that will update requirements.txt.
> Configure dependabot to update pip dependencies

- onnx/checker.py
Remove metaprogramming in onnx.checker according to the comment and make them plain functions again.
- Also add `__all__` and updated docstrings.
- Raise `TypeError` instead of `RuntimeError` in checkers when the protobuf message type is unexpected.
Better engineering
> Remove metaprogramming in onnx.checker

- onnx/reference/ops/op_quantize_linear.py
- onnx/reference/reference_evaluator.py
- onnx/test/reference_evaluator_test.py
The ReferenceEvaluator was only tested with float 8 constants (in node Constant), not in initializers. This fixes that issues.
Fixes a bug.
> Supports float 8 initializers in ReferenceEvaluator

- onnx/test/shape_inference_test.py
https://github.com/onnx/onnx/issues/4160
Shape inference tests for older opset versions are not supported before this PR. This refactor would help to test old-versioned ops.
This PR introduces a function `all_versions_for` to help generate test functions for all versions of one Op. The users can use `@parameterized.expand(all_versions_for("${op_name}"))` to annotate the test function to apply the test function to all op versions. The test function should have the arguments like `def test_op(self, version_name, op_version)`. `version_name` is usually unused but it's better to keep that to make the parameterized test name more readable. For example, with this `version_name`, the test name will have a version suffix showed as follows.
> Refactor shape_inference_test for old Op versions PR1

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/quantization/defs.cc
`T2` should match `x_scale`, not `y_scale`.
> fix typo in DequantizeLinear spec

- onnx/backend/test/case/node/scatternd.py
- onnx/reference/ops/op_scatternd.py
- onnx/test/reference_evaluator_test.py
Changed the way the reference implementation implemented ScatterND. The problem lied in the fact that currently the implementation uses [integer array indexing](https://numpy.org/devdocs/user/basics.indexing.html#integer-array-indexing) instead of multidimensional slicing. 
This change solves  #5353.
> Fix ScatterND implementation

- CMakeLists.txt
- Allow to override CMAKE_CXX_STANDARD and CMAKE_POSITION_INDEPENDENT_CODE
- CMAKE_POSITION_INDEPENDENT_CODE is not required for cases when static library is compiled into executable. So, we need to a way to disable `CMAKE_POSITION_INDEPENDENT_CODE=ON`
- Protobuf depends on ABSL library, which requires CXX17. So, when we compile against latest versions of protobuf and ABSL, we need to set CXX17, but ONNX overrides these values to CXX14. So, we need an option to override the project default values.
> Allow to override cmake options from cmd options, external projects

- onnx/defs/shape_inference.h
Add missing header: <algorithm> in shape_inference.h.
Closes https://github.com/onnx/onnx/issues/5346. If using shape_inference.h independently, it cannot use std::transform because `<algorithm>` is not included.
> Add missing header in shape_inference.h

- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- .github/workflows/scorecard.yml
- docs/OnnxReleases.md
- Test onnxruntime 1.15 with opset 19/IR 9 in CI
- Fix test source distribution -- CI should first uninstall onnx-weekly instead of onnx to test `pip install` from PyPI's source distribution.
onnxruntime 1.15.0 was out recently and the test version in ONNX should be bumped as 19 (IR as 9) to increase test coverage.
> Test onnxruntime 1.15 with opset 19/IR 9 and fix test source distribution

- .github/workflows/dco_merge_group.yml
Create a dummy dco workflow to enable merge queue: it won't check anything, but it should make DCO pass in the merge queue. The PR itself has already checked DCO and there is no need to check it again in the merge queue. Ideally with this PR https://github.com/onnx/onnx/pull/4890, we should finally be able to use merge queue feature in onnx repo. I don't not sure whether it can really work, but it's worth a shot.
A workaround to enable merge_queue for DCO workflow: https://github.com/onnx/onnx/issues/4884. Now onnx repo has more PRs to merge every day and having this merge queue feature can save a lot of time for merging multiple PRs.
> Dummy dco workflow to enable merge queue

- .azure-pipelines/Windows-CI.yml
- .github/workflows/codeql.yml
- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- .github/workflows/weekly_mac_ci.yml
- .github/workflows/win_no_exception_ci.yml
- I noticed typically py38_onnx_ml pipeline was very slowly created... Using newer version of Python 3.9 might help. If it is still too slow, we need to review the build time for build internal Protobuf and see whether we can make it faster.
- Set maxParallel as 6 to ensure every pipelines on Windows run at the same time.
- Make heavy release CIs cancel-in-progress.
Merge queue automatically removed PR, because some of pipelines (mainly py38_onnx_ml on Windows) are too slow and hit the timeout for merge queue. We should solve it in both ways:
- Increase the timeout for merge queue (just increased from 60 to 90 mins)
- Accelerate the slow Windows CI if possible
The PR is doing the later one. The former one needs to be done by the maintainer. cc @prasanthpul.
> Solve merge queue timeout issue: accelerate windows CI

- README.md
- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
- README.md
- Mention Protobuf will be internally installed if there is not preinstalled Protobuf.
- Upgrade recommended Protobuf version from 3.20.2 to 4.21.12, which is the same version as what release pipelines are using.
- Potential Slice-13 typo: `start[i]` -> `starts[i]`, `end[i]` -> `ends[i]`, `step[i]` -> `steps[i]`. Not sure whether it is intended, but they seem misleading -- Users might mistake the correct attribute name `steps` for `step`. Thanks @satyajandhyala for catching this.
- With https://github.com/onnx/onnx/pull/5196, now ONNX is able to install Protobuf internally if there is not preinstalled Protobuf. README.md should reflect that enhancement. Besides, currently release Pipelines are using Protobuf 21.12 (4.21.12) and so let's upgrade the recommended Protobuf version …
> [Doc] Update README.md regarding Protobuf update and fix typo in Slice-13 spec

- onnx/shape_inference/implementation.cc
To fix error message like
```
No opset import for domainai.onnx.preview.training optype Momentum
```
to 
```
No opset import for domain ai.onnx.preview.training optype Momentum
```
> Add missing space for schema not found error message in shape inferece

- MANIFEST.in
- setup.py
- Add missing requirements-reference.txt in MANIFEST.
- Refactor load requirements files as common `load_packages_from_requirements`.
When testing with installing from source distribution (weekly CI), there is an error that the new requirements-reference.txt is not found: https://github.com/onnx/onnx/actions/runs/5779508230/job/15661885724.
> Fix missing requirements-reference.txt for installing from source distribution

- .github/workflows/lint.yml
I realized the SARIF file wasn’t uploaded without always()
Use `i` to toggle comment display if needed.
> Always upload SARIF in PR

- .github/dependabot.yml
Reduce dependabot update frequency to monthly so we don't need to handle PRs every week.
Set limit to 10. We shouldn't have more than that.
> Reduce dependabot update frequency to monthly

- onnx/defs/shape_inference.cc
- onnx/defs/shape_inference.h
Rename source/target to inferred/declared in shape inference code to reduce confusion
Fixes #5470
> Rename source/target to inferred/declared

- onnx/defs/parser.cc
- onnx/defs/parser.h
- onnx/defs/printer.cc
- onnx/test/cpp/parser_test.cc
The existing parser and printer for ONNX text format does not support an empty list as an attribute value. Fix this.
> Support for parsing and printing empty list value as attribute

- onnx/helper.py
- onnx/test/helper_test.py
Adds a helper function to translate `AttributeProto` types to human-readable strings. This function is used to improve the exception string generated when the inferred `AttributeProto` type mismatches the specified `AttributeProto` type supplied to `make_attribute`.
Fixes #5442
> Show human-readable attribute type names in `helper.make_attribute` exception

- onnx/serialization.py
- onnx/test/basic_test.py
Add support for serializing to and deserializing from the ONNX textual representation, and register it under the `onnxtxt` file extension and format. 
Users can now save a model to the textual representation with `onnx.save_model(model, "model.onnxtxt")`
Note that the textual format has known limitations, including (1) it doesn’t serialize tensor protos or initializers and (2) bugs like #5102. We will call this out in a documentation in a separate PR.
> Create the onnxtxt serialization format

- pyproject.toml
Specify setuptools in the build-system section in pyproject.toml. So that setuptools gets installed when it is not in the environment when doing local install. 
Fixes https://github.com/onnx/onnx/issues/4878
> Specify the build-system in pyproject.toml

- pyproject.toml
Reverts onnx/onnx#5531 because the macos release pipeline is broken due to the change.
> Revert "Specify the build-system in pyproject.toml"

- .github/workflows/release_mac.yml
- docs/OnnxReleases.md
- pyproject.toml
Specify setuptools in the build-system section in pyproject.toml. So that setuptools gets installed when it is not in the environment when doing local install. 
Second attempt of #5531 by removing `--no-use-pep517` in the test pipeline
Fixes https://github.com/onnx/onnx/issues/4878
> Specify the build-system in pyproject.toml - second attempt

- onnx/helper.py
- onnx/test/helper_test.py
`make_tensor_value_info("X", TensorProto.FLOAT, [None])` is a valid input (according to `check_model`) but `printable_graph` raises an exception because the shape is unknown.
Prints out `'.'` when a dimension is unknown.
> Do not raise an exception in printable_graph when shape is not specified

- onnx/compose.py
Correction in the code of `merge_graphs` function while extracting output names from the two graphs if outputs are not provided in the parameters.
> Minor bug fix in merge graphs.

- docs/docsgen/source/intro/python.md
Use tensor_dtype_to_np_dtype instead of deprecated TENSOR_TYPE_TO_NP_TYPE in https://onnx.ai/onnx/intro/python.html. This is the only place I found which mentions deprecated functions from mapping.py.
Fixes https://github.com/onnx/onnx/issues/5392.
> [Web] Use tensor_dtype_to_np_dtype instead of deprecated function

- .github/workflows/release_mac.yml
Fix sed -i error in Mac release Pipeline for onnx-weekly.
Fixes https://github.com/onnx/onnx/actions/runs/6216622822/job/16870683053. sed command on Mac is slightly different from the one on Linux: the suffix is mandatory.
> Fix sed -i error in Mac release Pipeline for onnx-weekly

- onnx/defs/parser.cc
- onnx/defs/parser.h
- onnx/test/parser_test.py
onnx seems to ignore certain possibilities when it comes to otherwise valid IEEE float values. So far this change just adds functionality to the parser to recognize `inf` or `-inf` as floats. However, this seems to point towards more issues. Should onnx recognize any string parse-able by `std::stof` as a float literal?
The current state of this PR does address #5102, although not in a very elegant fashion.
> Getting onnx to treat `inf/-inf` as float literals.

- .azure-pipelines/MacOS-CI.yml
- .azure-pipelines/Windows-CI.yml
Move onnxruntime test from Windows to MacOS.
Currently Windows-CI failed, because it tested with the latest onnxruntime (1.16.0 just out yesterday) without setting the max supported versions correctly before "pytest":
https://github.com/onnx/onnx/blob/3d015412360115e989ea78c5eb75911374fd0dd0/.azure-pipelines/Windows-CI.yml#L131
To fix such failure, instead of adding more setting commands in Windows CI, I prefer to move the equivalent onnxruntime test to MacOS, because MacOS is averagely the fastest CI in onnx repo. This move can make the cost time for each AzurePipelines CI more even.
> [CI] Move onnxruntime test from Windows to MacOS

- .github/workflows/auto_update_doc.yml
- onnx/backend/test/case/node/__init__.py
- onnx/backend/test/cmd_tools.py
- Extend `onnx/backend/test/cmd_tools.py` with a new option: "diff", which will only update the backend node test data whose script has been updated.
- Make `auto_update_doc.yml` CI utilize "--diff" and update the backend node test data accordingly.
https://github.com/onnx/onnx/pull/5450 "auto update doc" was introduced for helping users update docs like Operators.md and TestCoverage.md. It will be also useful that the CI can help users update backend node test as well.
> Update diff bakend node tests for auto update doc

- docs/Versioning.md
- onnx/common/version.h
- onnx/defs/schema.h
- onnx/test/helper_test.py
prepare for rel-1.15.0 branch cut (planned for 09/22 https://github.com/onnx/onnx/wiki/Logistics-for-ONNX-Release-1.15.0)
ONNX 1.15.0 is planned to be released on 10/10
> prepare for rel-1.15.0

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/quantization/defs.cc
Hi! Something went wrong with my other pull request (#5601), so I forked the right version and tried again:
I changed the operator definition for DynamicQuantizeLinear to be consistent with the reference implementation as described in #5597
#5597
> Updated docs for DynamicQuantizeLinear to be consistent with reference implementation

- .github/workflows/release_win.yml
Fix Windows weekly release CI failure: use the correct env setting method in Windows GitHub Action.
Windows release CI misused the package name as onnx-weekly without dev version: https://pypi.org/project/onnx-weekly/1.15.0/#files. I will delete this wheel.
> Fix Windows weekly release CI failure

- onnx/common/ir.h
- onnx/test/cpp/ir_test.cc
The version-converter generates invalid ONNX identifiers (like "1"). Change it to generate a valid identifier.
> Fix version-converter to generate valid identifiers

- .github/workflows/lint.yml
Disable non-const reference check from cpplint.
Preferred coding-style: over pointers, when non-null.
> Disable non-const reference check from cpplint

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
doc for affineGrid: output shape is in correct. See https://pytorch.org/docs/stable/generated/torch.nn.functional.affine_grid.html. It shoud be (N, H, W, 2) or (N, D, H, W, 3) 
fix for 1.15.0 release
> Fix affineGrid doc error - output shape shall has no 'C' in it

- README.md
Use absolute link in README.md entirely to correctly show links on PyPI: https://pypi.org/project/onnx/.
Fixes https://github.com/onnx/onnx/issues/5616. There are still few relative links in README.md.
> Use absolute link in README.md entirely

- onnx/checker.cc
This PR closes #5668 and fixes building onnx on non-glibc linux systems (e.g. Alpine Linux / musl).
The latest version of onnx (1.14.1) currently fails to compile on non-glibc systems (e.g. musl) due to an unsupported call to `stat64()` in checker.cc. See the latest [pipeline log](https://gitlab.alpinelinux.org/leso-kn/aports/-/jobs/1143766#L1155) of [aports!52138](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/52138) for an example case.
> Do not use LFS64 on non-glibc linux (#5668)

- onnx/reference/ops/op_tfidf_vectorizer.py
- onnx/test/reference_evaluator_ml_test.py
Current implementation of TfIdfVectorizer does not support string inputs. This implements this supported behaviour and adds unit tests.
> Reference implementation for TfIdfVectorizer supports string inputs

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/reducemax.py
Adds missing ReduceMax test with empty set
There is test for ReduceMin but for ReduceMax seems to be missing in https://github.com/onnx/onnx/pull/5568
> Add missing ReduceMax's empty set test

- workflow_scripts/config.py
Skip ssd_mobilenet_v1 due to recent subgraph shape inference enhancement.
The CI of `Weekly CI with the latest ONNX and ONNX Model Zoo` started failing after Aug 27 (passed on Aug 20) probably due to this sugraph shape inference enhancement: https://github.com/onnx/onnx/pull/5488 (merged on Aug 21).
The root cause is track in Model Zoo repo: https://github.com/onnx/models/issues/628 and will be fixed there. For now we can just skip this test in ONNX repo.
cc @gramalingam since we have discussed it yesterday.
> Skip ssd_mobilenet_v1 due to subgraph shape inference enhancement

- onnx/defs/quantization/defs.cc
- onnx/test/shape_inference_test.py
Fix shape inference for types float16 and bfloat16 for operator DequantizeLinear.
Shape inference is wrong for DequanzeLinear-19 as reported in issue #5704.
> Fix shape inference for DequantizeLinear

- docs/OnnxReleases.md
To re-order release steps so that release branch is created before release tag is to be created. This is because release branch is needed for creating a tag.
TO reduce mistake of creating a release tag with in-correct branch
> update release doc for tag creation

- onnx/checker.py
- Use `lexical_scope_ctx` instead of `ctx` in `checker.py`
- Provide default contexts in `check_function()`
Follow up to https://github.com/onnx/onnx/pull/5693
Close #5755
> Add default for check_function & Use lexical_scope_ctx for readability

- onnx/defs/schema.cc
Print the actual and expected attribute types in checker when there is a mismatched attribute type to help debugging.
https://github.com/pytorch/pytorch/issues/112831
> Print the actual and expected attribute types in checker

- onnx/checker.py
- onnx/helper.py
- onnx/test/checker_test.py
Resurrect check function context logic to handle when context is not provided to `check_function`. We need to support None because otherwise `check_function` breaks backward compatibility when only the first argument is provided.
Fix https://github.com/onnx/onnx/issues/5774
> Resurrect check function context logic

- CMakeLists.txt
- pyproject.toml
- setup.py
- tools/protoc-gen-mypy.py
https://github.com/onnx/onnx/pull/5697 should include pyi files but doesn't. This is because we do not have a required build dependency `protobuf` when the `build` module creates the isolated build environment. I added it as a required dependency and updated outdated configs.
- Include protobuf in build dependencies
- Raise an error instead of silently skip when `tools/protoc-gen-mypy.py` gets import error.
> Include pyi files in build

- onnx/test/cpp/inliner_test.cc
Replace "sanity" with "safety".
Inclusive terminology change
> Replace sanity with saftey for inclusive terminology

- onnx/defs/parser.cc
Without C++17 current codebase cannot be compiled. 
But it seems that `string_view` include is not used and we can drop it.
> Removed unused string_view include

- .github/workflows/release_mac.yml
- onnx/test/test_backend_reference.py
release build breaks due to https://github.com/onnx/onnx/pull/5806
filesystem not available on Mac 10.12.
also need to skip 2 reference implement tests (test_qlinearmatmul_3D_int8_float16_cpu, test_qlinearmatmul_3D_int8_float32_cpu) which are failing on MacOS (https://github.com/onnx/onnx/issues/5792)
fix mac release CI
> Use mac-release 10.15

- pyproject.toml
The attribute `editable_mode` in setuptools `build_py` was only introduced in v64, https://github.com/pypa/setuptools/commit/207da8caa9e2673ab8470f78dc10901e0d60a96f.
Since `editable_mode` is used in `setup.py` without try-except for AttributeErrors, `pyproject.toml` should require `setuptools>=64`.
This is the cause of the original error in #5716.
If compatibility with older `setuptools` versions is desired, then another fix could be to introduce try-except blocks in two places in `setup.py`. This would add to the complexity of `setup.py`.
> fix: need setuptools>=64 for editable_mode

- onnx/inliner/inliner.cc
- onnx/test/cpp/inliner_test.cc
Addresses issue mentioned in https://github.com/onnx/onnx/pull/5817
The inliner was not processing subgraphs for inlining.
> Process subgraphs in inliner

- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- .github/workflows/scorecard.yml
Reverts onnx/onnx#5830. It is breaking the release pipeline.
https://github.com/actions/upload-artifact/issues/478
> Revert "Bump actions/upload-artifact from 3.1.3 to 4.0.0"

- onnx/test/helper_test.py
- onnx/test/reference_evaluator_test.py
some int4 tests requires numpy version higher than 1.22.0 for support of elementwise operations on numpy arrays of custom dtypes. release CIs have test of old numpy versions and thus failed.
make release CI to pass.
> Skip some int4 test with old numpy version

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
> Add `perm` length constraint in Transpose doc

- onnx/defs/shape_inference.cc
> Print tensor dtypes as strings in shape inference

- docs/docsgen/source/onnx_sphinx.py
- Render function bodies when an operator has a function definition.
- Fix attribute documentation formatting
Fixes https://github.com/onnx/onnx/issues/5872
> Improve attribute docs formatting on the docs site

- docs/Changelog-ml.md
- docs/Operators-ml.md
- onnx/defs/schema.cc
- onnx/defs/traditionalml/defs.cc
The use of the `OpSchema::Attr` with conditionExplanation ends up having a default AttributeProto without a TensorProto field. The `default_tensor` attribute is optional and so should not be setting a default value.
cc @gramalingam
> Fix label encoder definition in schema

- onnx/test/test_backend_onnxruntime.py
Fix https://github.com/onnx/onnx/issues/5894
unblock ci by skipping known ort test failures
> Unblock ci by skipping known ort 1.17 test failures

- requirements-min.txt
- requirements.txt
Fix Linux release pipeline due to usage of np.broadcast_shapes which was introduced in numpy==1.20.0
Fix https://github.com/onnx/onnx/issues/5900
> Bump Numpy minimal version to 1.20

- onnx/numpy_helper.py
This removes the invocation of `convert_endian()` from `numpy_helper.to_array()` in favor of another implementation, since convert_endian() modifies the TensorProto.
This change was needed due to observed issues when trying to load an ONNX model that was exported on a s390x system via tf2onnx. Debugging showed that the TeensorProto was being modified by endianness conversion operations, which led to model incorrectness under certain circumstances.
Fixes #5901.
> Fix endianness conversion in numpy_helper.to_array()

- onnx/cpp2py_export.cc
Remove deprecated properties from FormalParameter.
The properties are set to be removed for the 1.16 release. Fixes https://github.com/onnx/onnx/issues/5074
> Remove deprecated properties from FormalParameter

- .azure-pipelines/Linux-CI.yml
- .azure-pipelines/MacOS-CI.yml
- .azure-pipelines/Windows-CI.yml
- .reuse/dep5
Add License/Copyright headers to azure yml files
Some cleanup (reduce number of files/exceptions within dep5 file)
> Add License/Copyright headers to azure yml files

- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.in.proto
- onnx/onnx.proto
- onnx/onnx.proto3
Update onnx.proto and derivatives to specify storgae type for 4bit types in int32_data
Storage type for the recently added UINT4, INT4 types was not documented.
> Document UINT4, INT4 storage type

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/quantization/defs.cc
- onnx/onnx-ml.proto
- onnx/onnx-ml.proto3
- onnx/onnx.in.proto
- onnx/onnx.proto
- onnx/onnx.proto3
* Added line breaks in QuantizeLinear and DequantizeLinear operators documentation for readability in markdown format.
* Added additional information about UINT4/INT4 in onnx.proto
> Q/DQ docs readability + 4bit info in onnx.proto

- .azure-pipelines/Windows-CI.yml
https://gitlab.kitware.com/cmake/cmake/-/issues/25704
> The latest Cmake 3.28.3 is failing with "Could NOT find Protobuf (missing: Protobuf_LIBRARIES)". Use Cmake 3.27.9

- onnx/reference/op_run.py
- onnx/reference/ops/_op.py
- onnx/reference/ops/_op_list.py
- onnx/reference/ops/aionnx_preview_training/_op_list.py
- onnx/reference/ops/aionnxml/_op_list.py
- onnx/reference/ops/aionnxml/op_tree_ensemble.py
- onnx/reference/ops/experimental/_op_list.py
- onnx/reference/ops/op_rnn.py
- onnx/reference/ops/op_scan.py
- onnx/reference/reference_evaluator.py
- onnx/test/reference_evaluator_test.py
The current implementation still uses ReferenceEvaluator even when this evaluator was overloaded in a subclass. This PR makes sure that every local function or subgraph uses the new class to execute the local functions and sub graphs.
> Fix ReferenceEvaluator when run from a subclass

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/generator/defs.cc
Boolean type was unintentionally dropped in #5811. 
Revert to previous version and add the new types uint4, int4. 
Modify type constraint comment to mention boolean is allowed.
> Fix ConstantOfShape type constraints

- docs/OnnxReleases.md
Update steps on drafting a Release following cutting a release branch.
The original steps had creating a tag immediately after cutting the branch. However tags are intended to be static and not updated once cut. We don't want to create the final tag until we are ready to officially release (ie all validation has been completed, no more bug fixes to be merged, etc). Instead we can _draft_ a release with the desired tag when the branch is cut. Then the tag won't actually be created until the release is published.
> OnnxReleases.md Release drafting

- .github/workflows/check_urls.yml
- docs/Hub.md
Cherry-pick (#5972) - Fix Check URLs errors
* Update ONNX model zoo URL to reflect changes in their repo
* Update timeout so https://github.com/onnx/onnx/blob/main/docs/Operators.md passes
(cherry picked from commit b411f3b7ca8363dba92568f46ddbba989674cd30)
> [Cherry-pick] Fix Check URLs errors in `rel-1.16`

- pyproject.toml
- setup.py
* Fix builds from source and pip tar.gz on s390x systems
* Revert (#5195) and replace with fix from [this comment](https://github.com/onnx/onnx/issues/5194#issuecomment-1749336155) from the original issue (#5194)
* Building on s390x (and other environments depending on python setup) fails 
* The issue also can also appear when installing `1.16.0rc1` from TestPyPI for environments where we don't have pre-built wheels 
* Failures include not being able to find pacakges despite them being installed 
``` 
pip3 install -e . ... 
-- Could NOT find pybind11 (missing: pybind11_DIR)
... 
Traceback (most recent call last): File "/onnx/.setuptools-cmake-build/tools/protoc-gen-mypy.py", line 28, in <module>
import google.protobuf.descriptor_pb2 as d_typed 
```
* The issue is cased by (#5195) which …
> Fix source and pip tar.gz builds on s390x systems

- onnx/common/ir.h
#5628 missed some getNextUnique() and causes name conflict.
> Fix unique_name

- onnx/common/ir.h
* Cherry-pick #5992 into `rel-1.16.0` branch
* #5628 missed some getNextUnique() and causes name conflict.
> [Cherry-pick] Fix unique_name

- onnx/defs/schema.cc
- onnx/test/shape_inference_test.py
The bug is SegFault during shape inference if the schema not be set inference function.
The schema has `CheckInputOutputType` for shape inference and `Verify` for raw node proto. And the behavior is not fully aligned.
fixes #5989
> Fix SegFault bug in shape inference

- onnx/defs/schema.cc
- onnx/test/shape_inference_test.py
Cherry-Pick #5990 into `rel-1.16.0` branch
The bug is SegFault during shape inference if the schema not be set inference function.
The schema has `CheckInputOutputType` for shape inference and `Verify` for raw node proto. And the behavior is not fully aligned.
fixes #5989
> [Cherry-pick]Fix SegFault bug in shape inference

- onnx/compose.py
Recursively searching through the nodes for input in merge graphs function.
While connecting and merging two models in which there is subgraph in one of them, inputs and outputs of subgraph was being overlooked and were left dangling. 
This fixes https://github.com/onnx/onnx/issues/5985
> Fix `onnx.compose` when connecting subgraphs

- .azure-pipelines/Windows-CI.yml
* Cherry-pick #5975 into `rel-1.16.0` fix find libprotobuf which is suggested by https://gitlab.kitware.com/cmake/cmake/-/issues/25704
* Required so cherry-pick #5986 can pass tests
> [Cherry-pick] Use CMAKE_PREFIX_PATH in finding libprotobuf (#5975)

- onnx/defs/operator_sets.h
- onnx/defs/schema.h
* Bump ai.onnx opset to 22
* Bump opset to 22 for future 1.17.0 release now that 1.16 branch has been cut.
> Bump ai.onnx opset to 22

- onnx/defs/schema.cc
- onnx/defs/schema.h
- Add `OpSchema::VerifyInputNum` and `OpSchema::VerifyOutputNum` methods. The logic has been moved from `OpSchema::Verify`.
- Replaced the input/output number check logic in `OpSchema::CheckInputOutputType` with calls to the new interfaces.
- Without using the `Node(domain::op_type::version)` string pattern in `OpSchema::CheckInputOutputType` when calling `fail_check`, as the `op_type` will be displayed by the shape inference common exception. Otherwise, it would appear redundant.
follow-up #5990
resolve #5993
> Generalize input/output number check in shape inference

- onnx/defs/math/defs.cc
- onnx/test/shape_inference_test.py
In the development of ONNX Runtime, we need know the output shape of each Op node for statical graph compilation. However, we found that we could use onnx shape inference to achieve almost all output shapes except the output shape of Einsum. In `onnx/defs/math/defs.cc`, we found that there was only Rank Inference function for Einsum instead of Shape Inference. 
Given the results of equation parsing and the input shapes of the Einsum operation, we can easily infer the output shape. As such, we have expanded the rank inference to include shape inference for Einsum.
> Replace rank inference with shape inference for Einsum op

- README.md
latest cmake requires to set CMAKE_PREFIX_PATH (https://gitlab.kitware.com/cmake/cmake/-/issues/25704)
> build from source instruction with latest cmake change

- docs/OnnxReleases.md
Added Spox and conda-forge/onnx-feedstock as partner projects to be notified about imminent releases.
We had some breaking changes in the past. Checking against more downstream projects will reduce the risk of disrupting parts of the ecosystem with a new release.
> Add more partner projects to be notified about new releases

- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
- onnx/test/shape_inference_test.py
- Even if the `depth` value of `OneHot` is specified as an initializer, the value is ignored during shape inference currently.
- This is a correct shape inference from my understanding, but let me if this is wrong.
> Handle `OneHot`'s `depth` value during shape inference

- pyproject.toml
Current fix of https://github.com/onnx/onnx/issues/5194 forces out system installed cmake. It forces to use a cmake installed via pyproject.toml in a python environment. The cmake in python environment fails on Windows - onnx.sln cannot be built with visual studio due to protobuf code generation error.
This PR skip cmake install in pyproject.toml in Windows. It is better only include cmake in pyproject.toml if needed.
> Not to install cmake in pyproject.toml on Windows

- onnx/shape_inference/implementation.cc
> fix a skipped shape infer code

- onnx/__init__.py
- onnx/serialization.py
Usage seen in https://github.com/onnx/onnx-mlir/blob/5ef91c1be51eb578e61d2ae3c05fa821297a8ee2/test/mlir/onnx/parse/fun_model_test.onnxtext. (https://github.com/onnx/onnx-mlir/pull/2262). I added the `.onnxtext` extension to be a known extension for the serializer.
> Include the ".onnxtext" extension in supported serialization format

- onnx/reference/reference_evaluator.py
- onnx/test/model_container_refeval_test.py
- onnx/test/reference_evaluator_test.py
- onnx/test/tools_test.py
Intermediate results can only be printed right now. With this PR, they can be returned as well. 
See #6025.
> Allow ReferenceEvaluator to return intermediate results

- onnx/checker.cc
- onnx/test/checker_test.py
- onnx/test/compose_test.py
The current checker does not check that all graph outputs are defined. This PR adds such a check. (See issue https://github.com/onnx/onnx/issues/6040 ).
Note: We probably also want a separate check to ensure that a graph-input is not used as a graph-output. But leaving that for a separate PR, since it is a distinctly different check (and perhaps might require a different discussion).
Redo of PR #6070
> Check graph outputs are defined

- onnx/reference/ops/op_reduce_sum_square.py
- onnx/test/reference_evaluator_test.py
This PR aligns the op implementation for `ReduceSumSquare18` when `axes` are not specified and `noop_with_empty_axes != 0` with that of the reference.
Current implementation of `ReduceSumSquare18` when axes are empty and `noop_with_empty_axes != 1` squares the input data and then returns it, when according to the reference it should just return the input data with no changes.  
This addresses issue #6103
> Corrected the ReduceSumSqure op to match the reference

- workflow_scripts/test_model_zoo.py
Deletes model downloaded to disk after testing to avoid storage issues.
> Verify model deletion after testing

- .github/workflows/manylinux/entrypoint.sh
- .github/workflows/release_linux_aarch64.yml
Only install google-re2 from wheels.
The latest version of google-re2 dropped support for manylinux2014.
google-re2 fails to build from sources thus failing the Linux release pipelines.
This PR forces installation from wheels on manylinux which thus fallback on the latest version of google-re2 with a wheel for manylinux2014.
It reverts https://github.com/onnx/onnx/pull/6120 which forced all dependencies to be available as wheels (psutil is not which forbids installing recent versions of jupyter/ipykernel).
Another solution would be to bump the manylinux images to manylinux_2_28 but that could have impact on downstream users (e.g. impossible to install wheel from rh7, amazon linux 2, ubuntu 18.04).
> fix: install google-re2 with `--only-binary` option

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/quantization/defs.cc
- onnx/defs/quantization/old.cc
> Specify axis parameter for DequantizeLinear when input rank is 1

- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
The latest ORT 1.18.0 does not implement ML ops required for test_backend_onnxruntime.py. Pin to the previous ort release to pass the release CIs.
https://github.com/onnx/onnx/pull/6138#issuecomment-2118368537
> Pin onnxruntime to 1.17.3 for release CIs

- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
The latest ORT 1.18.0 does not implement ML ops required for test_backend_onnxruntime.py. Pin to the previous ort release to pass the release CIs.
https://github.com/onnx/onnx/pull/6138#issuecomment-2118368537
---------
Signed-off-by: Liqun Fu <liqfu@microsoft.com>
(cherry picked from commit 093a8d335a66ea136eb1f16b3a1ce6237ee353ab)
> Pin onnxruntime to 1.17.3 for release CIs (#6143)

- .github/workflows/main.yml
Future PRs need to reenable `pip install -e .` for all Python versions
> Fix CI on Windows 3.12

- docs/docsgen/source/intro/converters.md
This adds a short section explaining an alternative approach to dedicated converter libraries for library authors looking to implement ONNX export capability for their library. This approach leverages a standardised protocol (in this case the [Array API standard](https://data-apis.org/array-api/latest/)) and an ONNX based implementation of it (in this case [ndonnx](https://github.com/Quantco/ndonnx)).
This adds some broader context to the different ways libraries may want to explore ONNX export beyond the traditional approach with dedicated converter libraries.
> Add alternative approach in ONNX converter section

- onnx/external_data_helper.py
- onnx/test/test_external_data.py
The `external_data_helper.py` utilities do not handle model-local functions. Extend them to handle model-local functions. Add a test-case to validate.
> Handle functions in external data helper

- docs/docsgen/source/api/external_data_helper.md
- docs/docsgen/source/api/helper.md
- docs/docsgen/source/api/hub.md
- docs/docsgen/source/api/numpy_helper.md
- docs/docsgen/source/api/parser.md
- docs/docsgen/source/api/reference.md
- docs/docsgen/source/api/shape_inference.md
Add the  missing python api docs:
- docs/docsgen/source/api/external_data_helper.md
- uses_external_data
- docs/docsgen/source/api/helper.md
- get_node_attr_value
- set_metadata_props
- set_model_props
- make_attribute_ref
- make_map_type_proto
- make_model_gen_version
- create_op_set_id_version_map
- strip_doc_string
- pack_float32_to_4bit
- docs/docsgen/source/api/hub.md
- set_dir
- get_dir
- docs/docsgen/source/api/numpy_helper.md
- unpack_int4
- docs/docsgen/source/api/parser.md
- parse_node
- docs/docsgen/source/api/shape_inference.md
- infer_node_outputs
It also fixes the repeated docs in `docs/docsgen/source/api/helper.md`.
I was looking through the onnx python API documentation and noticed that there were some Python interfaces missing from the list, so I added them in.
> Add the missing python api docs

- .github/workflows/release_mac.yml
It seems the latests wheels aren't compatible with macOS 11 for some reason.
We can't test on macOS 11 anymore & macOS 11 is EOL.
Use MACOSX_DEPLOYMENT_TARGET=12.0 and move the tests to the lowest versioned runner available.
Note: the delocate tool did not find anything wrong with the target being 11.0 on the 1.16.1 wheel. It should have complained if using symbols only compatible with 12.0+ so it seems MACOSX_DEPLOYMENT_TARGET=11.0 was indeed respected and the root cause of the issue is still unknown.
#6191
> Use MACOSX_DEPLOYMENT_TARGET=12.0 for macOS wheels

- docs/ExternalData.md
On Windows, it is incorrect to say that offset needs to be multiple of page size. Instead offset needs to be multiple of VirtualAlloc allocation granularity.
You can see an error returned in ORT code if this is not the case https://github.com/microsoft/onnxruntime/blob/4e75605eec985e579ee1e8db9a2bb2fd441a4837/onnxruntime/core/platform/windows/env.cc#L453
We debugged an issue with ORT team where memory mapping was not working. Even when aligned to page_size, on Windows, memory mapping did not work until aligned to 64kb.
See [MapViewOfFile](https://learn.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffile)
Related: #6226
> ExternalData - On Windows document proper offset for memory mapping support

- onnx/shape_inference.py
- onnx/test/inference_function_test.py
Fix https://github.com/onnx/onnx/issues/6249
This PR handle the optional input in `onnx.shape_inference.infer_node_outputs` via skip the optional input type. The following modification are introduced:
- `onnx/shape_inference.py` Skip the input type if the input name is "".
- `onnx/test/inference_function_test.py` Add a unit test case of optioal input for `infer_node_outputs`
See https://github.com/onnx/onnx/issues/6249 for more detail.
> Handle the optional input in infer_node_outputs

- docs/Changelog.md
- onnx/defs/tensor/old.cc
- onnx/tools/net_drawer.py
Fix some broken URLs that failed test when I tried to create rel-1.16.2 branch.
* https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
* Automatically redirects to https://numpy.org/doc/stable/reference/arrays.indexing.html which now 404's
* Based on web.archive.org search, https://numpy.org/doc/stable/reference/routines.indexing.html has the same information as the old URL so updating to use that link instead.
* https://github.com/pytorch/pytorch/blob/master/caffe2/python/net_drawer.py
* Automatically redirects to main, but that file no longer exists in that branch. The last tag with the file was https://github.com/pytorch/pytorch/blob/v2.3.1/caffe2/python/net_drawer.py. 
* Based on the v2.3.1 version, I tried searching for a couple of the method names but got no hits. So I …
> Update broken URLs

- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
- requirements-min.txt
- requirements-reference.txt
Limit numpy version to <2 in tests to pass ci-piplines for 1.16.2. 
The change in requirements-min.txt is also needed to get the CI's to pass. There's an issue with the https://github.com/python-pillow/Pillow/pull/8187. We did try downgrading the version of pillow but that then failed to build for some reason.
> Limit numpy version to <2 in tests to pass ci-piplines for 1.16.2

- onnx/test/test_backend_onnxruntime.py
ORT 1.19.0 was just released. We need to update backend test to exclude tests are known to fail with it.
> Update ort filter to 1.20.0 to skip tests known to fail with ort 1.19.0

- docs/Versioning.md
- onnx/common/version.h
- onnx/defs/schema.h
- onnx/helper.py
- onnx/test/helper_test.py
Prepare for rel-1.17.0 branch cut (planned for 08/06 [https://github.com/onnx/onnx/wiki/Logistics-for-ONNX-Release-1.17.0](https://github.com/onnx/onnx/wiki/Logistics-for-ONNX-Release-1.17.0))
ONNX 1.17.0 is planned to be released on 08/20
> Prepare for rel-1.17.0

- onnx/defs/operator_sets.h
- onnx/defs/schema.h
Bump ai.onnx opset to 23
Bump opset to 23 for future 1.18.0 release now that 1.17 branch has been cut.
> Bump ai.onnx opset to 23

- .github/workflows/create_release.yml
After the release-pipeline upgrade (https://github.com/onnx/onnx/pull/6277)
the publishing the weekly does not work any more as the secrets are not available at the resuable workflows (
https://github.com/onnx/onnx/actions/runs/10551283959/job/29228497156 )
Link for the option I used for the secrets:
https://github.blog/changelog/2022-05-03-github-actions-simplify-using-secrets-with-reusable-workflows
In my opinion, we no longer need these secrets at the end. 
In the future, the publishing of the Onnx weekly builds will be solved via “trusted publishing” outside the individual OS release pipelines. This is already included in create_release.yml. Currently, the previous weeklys are published at pypi.org, in the test via trusted publishing at test.pypi.org
After a successful schedule test …
> Fix missing secrets for publishing of onnxweekly 

- onnx/defs/tensor/old.cc
- onnx/test/shape_inference_test.py
Early return causes wrong shape inference. When input has dynamic axes and Squeeze-11' axes is missing, output shape was always inferred as scalar. This will lead to validation error in downstream nodes.
Fix #6313
> Fix shape inference for Squeeze-1,11 with dynamic input shape

- .github/workflows/release_win.yml
Cherry-Pick (#6342) - The latest protobuf pkg 5.28.0 is failing on Windows. use the one pre… into the `rel-1.17.0` branch
Cherry pick commit to `rel-1.17.0` to fix protobuf package issue in windows testing
> [Cherry-Pick] Fix protobuf pkg 5.28.0 failing on Windows (#6342)

- docs/Syntax.md
- onnx/defs/parser.cc
- onnx/defs/parser.h
- onnx/defs/printer.cc
- onnx/test/cpp/parser_test.cc
Many onnx models used in practice use tensor names that are not valid C identifiers (as required by the ONNX standard). This PR extends the printer and parser to support such identifiers.
(It may be useful to relax the ONNX standard's requirements in this regard, but that's a separate issue, requiring some community discussion.)
> Extend printer and parser to support invalid identifiers

- .github/workflows/release_mac.yml
The code uses "matrix.target-architecture", but it is not in the strategy matrix?
Does it need to be added?
> Add missing matrix.target-architecture ? (Update release_mac.yml)

- .github/workflows/release_mac.yml
make sure that unique files names are used before uploading the wheels 
```
Run actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
> BugFix: make sure that unique files names are used before uploading the wheels 

- .github/workflows/create_release.yml
Scheduled workflows will only run on the default branch. 
(https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule)
Currently, the artifacts are also downloaded if they are not published to testpypi
> Simplify create_release.yml

- docs/Syntax.md
- onnx/defs/parser.cc
- onnx/defs/parser.h
- onnx/defs/printer.cc
- onnx/test/cpp/parser_test.cc
1) Adds support for node label in parser and printer
2) Adds some status-checks that were missed in recent addition to support invalid identifiers.
Node labels are now supported with the following syntax:
```
[a_node_label] y = MatMul (x, w)
```
However, we have a couple of options to choose from here:
(a) The ONNX spec says that the node label must be a valid identifier. So, we can allow for a valid identifier between the `[...]`, relying on a quoted string inside if the user wants to use something that is not a valid identifier.
(b) Alternatively, since `[` and `]` act as end-markers, like quotes, we can allow any string in-between, that is taken to be the node label. (Users will need to use an escape backslash if they want `]` in the label.)
Option (b) is better if users want to use …
> Support node labels in parser and printer

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
- onnx/defs/nn/old.cc
- onnx/reference/ops/op_quantize_linear.py
- onnx/test/version_converter/automatic_upgrade_test.py
- Fix typo in the description of the GroupNorm op regarding the shape of scale and bias.
- As discussed with @gramalingam and @AlexandreEichenberger, it's better to mark the older opset 18 version as deprecated since it contained a mistake.
- Also add a missing type cast in the numpy reference implementation of QuantizeLinear for FP4.
> Fix typo in the GroupNorm description

- .github/workflows/create_release.yml
Not all os release runs have to be successful: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-not-requiring-successful-dependent-jobs
> Not all release runs have to be successul for publishing weekly to testpypi

- .github/workflows/create_release.yml
Fix wrong publishing target (onnx instead of onnx-weekly)
@justinchuby : We configured it for onnx-weekly at test.pypi right?
> Fix wrong publishing target (onnx instead of onnx-weekly)

- .github/workflows/create_release.yml
Last commit was incomplete:  Activity type has to be added
Add activity types: label
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
"By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened. To trigger workflows by different activity types, use the types keyword. For more information, see "[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onevent_nametypes)."
> Trigger release pipeline when label "run release..." was added to PR

- onnx/defs/generator/defs.cc
- onnx/defs/math/defs.cc
- onnx/defs/math/old.cc
- onnx/defs/sequence/defs.cc
- onnx/defs/shape_inference.cc
- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
- onnx/defs/tensor/utils.cc
- onnx/defs/tensor_proto_util.cc
- onnx/defs/tensor_proto_util.h
- onnx/defs/tensor_util.cc
- onnx/defs/tensor_util.h
This PR fixed returning const vectors, which prevents compiler optimisations, some dangling references to them were also fixed.
> Avoid returning const vectors

- .clang-tidy
- CMakeLists.txt
- onnx/defs/data_type_utils.cc
- onnx/defs/nn/defs.cc
- onnx/defs/printer.cc
- onnx/defs/schema.h
- onnx/defs/tensor/defs.cc
- onnx/shape_inference/implementation.cc
- onnx/version_converter/convert.cc
This PR enabled readability-container-size-empty check in clang-tidy, fixed violations.
Better code.
> Fix more clang-tidy warnings

- onnx/checker.cc
- onnx/checker.h
- onnx/defs/function.cc
- onnx/defs/math/defs.cc
- onnx/defs/schema.cc
- onnx/defs/schema.h
Switch some usage of std::{map,set}  to unordered counterparts.
For faster search operations.
> Use std::unordered_{map,set}

- tools/protoc-gen-mypy.bat
This change modifies the mypy protoc plugin batch file to attempt to use the `py` executable if the `python` executable isn't found.
The full context and motivation is covered in https://github.com/onnx/onnx/issues/6406, but the summary is that different installers on Windows give the Python executable different names (`python` or `py`) and without this change this script blocks ONNX installation on Arm-based PCs, or any other Windows machines that use the official Python dot org installer.
> Support official Python launcher on Windows

- onnx/reference/ops/op_pool_common.py
for example
onnx/backend/test/case/node/averagepool.py
uses 
pads = None
> Update op_pool_common.py, add missing "| None"

- onnx/defs/parser.cc
- onnx/defs/parser.h
- onnx/test/cpp/parser_test.cc
- onnx/test/parser_test.py
Fix parser to handle empty optional parameters in edge cases. Currently, it does not handle a missing optional parameter in the first position.
There are a few edge cases. We have to handle both the original way of specifying a missing optional parameter (with nothing followed by a comma, see examples below) and the added new way we have now with support for quoted identifiers (using an empty string "").
Examples:
* `Op()` has no operands
* `Op(,x)` has two operands, the first being empty.
* `Op("")` has one operand, which is an empty string.
* `Op(,)` has one operand, which is an empty string.
Thus, we allow a trailing comma after a non-empty identifier with no effect.
* `Op(x,)` has one operand, which is 'x'.
> Fix parser to handle empty optional parameters in edge cases

- onnx/utils.py
Separate the `infer_shapes` option from the `check_model` option.
Whether to `infer_shapes` or not should be controlled independently.
The `check_model` check was applied to `infer_shapes` in https://github.com/onnx/onnx/pull/6344.
However, for some use cases like issue https://github.com/onnx/onnx/issues/6368, `infer_shapes` is necessary but it cannot pass `check_model` because the output node shape is missing.
Adding an empty dimension like PR https://github.com/onnx/onnx/pull/6437 doesn't work since `onnxruntime.InferenceSession` treats an empty dimension as a dimension.
> Separate the infer_shapes option from the check_model option

- onnx/defs/schema.cc
- onnx/defs/schema.h
Some methods of OpSchema contain static variables in onnx/defs/schema.h. They would be better moved to onnx/defs/schema.cc to avoid duplicated definitions when linking ONNX.
> Fix ODR violations

- onnx/common/model_helpers.cc
- onnx/common/status.cc
- onnx/common/status.h
- onnx/defs/parser.h
Change StatusCategory and StatusCode to enum classes for better type checking. 
For better type checking.
> Use enum class for StatusCategory and StatusCode

- onnx/common/array_ref.h
- onnx/common/ir.h
- onnx/common/ir_pb_converter.cc
- onnx/cpp2py_export.cc
- onnx/defs/shape_inference.h
- onnx/test/cpp/function_verify_test.cc
- onnx/test/cpp/shape_inference_test.cc
- onnx/version_converter/adapters/type_restriction.h
More fixes for static analyzer warnings, mostly about adding const to parameter references/pointers.
> Fix static analyzer warnings

- onnx/utils.py
1. Check model.ByteSize() to decide whether to use `infer_shapes_path` or `infer_shapes`.
2. Check model.ByteSize() to decide whether to use `save_as_external_data` on `onnx.save`.
Note that if `save_as_external_data=False`, the following `check_model` may fail.
Current `extract_model` function does not support models larger than 2GB.
For example, issue https://github.com/onnx/onnx/issues/6368 is caused by large models like an UNet.
This PR improves the existing function by checking the size of the model.
> Support models larger than 2GB

- onnx/defs/parser.cc
When reviewing the parser code, I found some invocations without checking the return value.
> Add missing CHECK_PARSER_STATUS

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
Enhanced documentation of CenterCropPad
It clarifies an ambiguous description on how the operator extracts the cropping window, and what padding value is used
> Enhance CenterCropPad documentation

- onnx/compose.py
- onnx/gen_proto.py
- onnx/helper.py
- onnx/hub.py
- onnx/utils.py
More robust type checking in Python.
> Add type annotations and fix some lint warnings in Python code

- onnx/utils.py
Use a dictionary `output_to_index` to map an output name to the index of the corresponding node.
There are some facts:
1. `reachable` and `unreachable` are mutually exclusive sets. `reachable` union `unreachable` equals to all nodes.
2. In onnx, output name is unique. `len(nodes_to_search)` is either 0 or 1.
```
nodes_to_search = [
index
for index in unreachable
if current_output_name in nodes[index].output
]
```
This step can be speed up by using a `dict` to map an output name to a node.
After introducing a dict, there's no reason to keep `unreachable`, all unreachable checks can be done by `reachable`
I did an experiment to extract a unet model (around 3.3GB, 4900 nodes).
```
extract_model(
input_path=model_path,
output_path=model_path + ".tmp",
input_names=[node.name for node in …
```
> Optimize dfs in extract_model by dict

- onnx/utils.py
1. Use a queue to replace the `new_nodes` list.
2. Use a dict to speedup function lookup.
> Optimize collect_referred_local_functions in extract_model

- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_win.yml
Remove Pypi Publishing inside release_*.yml jobs... 
create_release publishes wheels
Makes the release publines clearer/simpler. Publishing is carried out in a separate step. 
Possibly breaks something with the community, because different target repos (pypi vs testpypi)
> Remove pypi publishing inside "release_"

- onnx/utils.py
Moving `output_to_index` to `self.outmap = self._build_output_dict(self.graph)`, make `_collect_reachable_nodes` code clean.
> Move output map to a function in extract_model

- CMakeLists.txt
The code actually requires C++17, so newer g++ should not rely on __STDC_FORMAT_MACROS
> Remove __STDC_FORMAT_MACROS

- .github/workflows/create_release.yml
- docs/CIPipelines.md
change onnx-weekly destination from test.pypi to pypi
Now that the CI revision and subsequent tests with the separate publishing step in a separate step have been successful, it is time to switch to pypi. So that this can also be used again in productive operation.
> change onnx-weekly destination from test.pypi to pypi

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
- onnx/defs/nn/old.cc
bfloat16 was mistakenly added to GlobalLpPool in opset2. It should have been done in opset 22. This PR fixes the types.
Fixes https://github.com/onnx/onnx/issues/6502
> Fix GlobalLpPool input types

- CMakeLists.txt
CMake encourages the LANGUAGES keyword, although the effect is same without it.
> Add LANGUAGE to CMake project

- .github/workflows/pages.yml
Separate the page build to two steps: build and deploy. This way we build pages for every PR and deploy when the PR is merged.
This change allows us to ensure pages build is green before merging changes.
> Update page deployment CI to test building pages in PRs

- .github/workflows/create_release.yml
fix upload endpoint for pypi, https://github.com/pypi/warehouse/issues/17076
The upload endpoint was coded as https://pypi.org/legacy (it should be https://upload.pypi.org/legacy) which has a much stricter body size limit, so the upload is bounced before warehouse gets a chance to say "hey this isn't the upload endpoint
> Fix upload endpoint (pypi)

- .github/workflows/create_release.yml
The regular weekly builds should continue to go to pypi...only the manually triggered ones to test.pypi.
There is no reason to store the same test builds in two different locations
> Publish to test.pypi only for testing (with workflow dispatch)

- onnx/checker.py
While saving a model that was just barely under the 2GiB limit (using Optimum), I noticed that it was saved with the external data format, even though it should be able to be saved in a single file.
After further investigation, it was related to [these lines](https://github.com/huggingface/optimum/blob/65a8a94adaf136dd677d28cfc837c0acfe993031/optimum/onnx/graph_transformations.py#L135-L138), where the value of `onnx.MAXIMUM_PROTOBUF` is used to determine whether to use the external data format. This value is hardcoded to 2GB (=`2*10^9` bytes), even though it should be 2GiB (=`2*1024^3`), according to the [protobuf documentation](https://protobuf.dev/programming-guides/proto-limits/#:~:text=form%20must%20be-,%3C2GiB%2C,-as%20that%20is):
Unless there is a specific onnx specification which …
> Fix `MAXIMUM_PROTOBUF` size (2GiB, not 2GB)

- onnx/shape_inference/implementation.h
- onnx/test/cpp/data_propagation_test.cc
Redo of #6553 (due to DCO/signoff issues)
Extend the implementation of partial data propagation to make use of the rank of a tensor, if known. 
This enables more precise shape inference, especially in the presence of dynamic shapes involving some unknown dimensions. Generated models often use computed shapes that mix statically known and statically unknown dimensions (for example, in an expression such as `Concat (BatchSize, SequenceLength, OtherKnownDimensions)`). Even if `BatchSize` and `SequenceLength` are unknown, the other dimensions may be known, and it useful to track them to enable certain optimizations.
> Use rank in data propagation

- onnx/defs/data_propagators.h
- onnx/test/data_propagation_test.py
Fix issue https://github.com/onnx/onnx/issues/6276 (data propagation fails on Concat when first tensor is initialized empty).
> Fix handling of tensor rank in concat data propagation

- onnx/utils.py
In the extractor, when building the mapping from output names to node index, skip empty outputs. When searching reachable nodes, skip empty inputs.
For example, in the LLMs (e.g. Llama3) onnx model generated by onnxruntime-genai, there are nodes with optional inputs and outputs which are not used. Extracting a subgraph including these nodes will have an incorrect result.
> Fix: skip empty input output names in Extractor

- onnx/reference/custom_element_types.py
- onnx/test/reference_evaluator_test.py
With python 3.12, numpy==2.2.0,  ``np.float64 == None is True``. The PR address one place where this affects the results.
The happens when ml_dtypes is installed.
> Fix wrong comparison between numpy dtypes to None

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/cumsum.py
- onnx/reference/ops/op_cum_sum.py
This PR fixes the `dtype` returned from `CumSum` to be the same as the input. The tests included demonstrate that the change fixes the inconsistency. 
The ONNX [documentation](https://onnx.ai/onnx/operators/onnx__CumSum.html) states:
> - y (heterogeneous) - T:
> Output tensor of the same type as ‘x’ with cumulative sums of the x’s elements
This mismatch between the reference implementation and `onnxruntime` was found by running the [array-api](https://data-apis.org/array-api/latest/) test suite through [ndonnx](https://github.com/Quantco/ndonnx) on both.
> Fix reference implementation for CumSum

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/topk.py
- onnx/reference/ops/op_topk.py
- onnx/test/test_backend_onnxruntime.py
This PR fixes problems in the reference implementation of TopK in the following cases by rewriting the tiebreaker mechanism and unifying logic for all cases. 
The ONNX [documentation](https://onnx.ai/onnx/operators/onnx__TopK.html) states:
> Given two equivalent values, this operator uses the indices along the axis as a tiebreaker. That is, the element with the lower index will appear first.
This was not the case currently as the `flip` after the `argsort` changes the order of the same-valued elements. 
Additionally the logic around 2d shaped inputs introduces a bug for unsigned inputs as the negation overflowed.
This mismatch between the reference implementation and `onnxruntime` was found by running the [array-api](https://data-apis.org/array-api/latest/) test suite through …
> Fix reference implementation for TopK

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/unique.py
- onnx/backend/test/runner/__init__.py
- onnx/reference/ops/op_unique.py
This PR uses the [recommended way](https://numpy.org/doc/stable/reference/generated/numpy.unique.html) to ensure compatibility with `numpy.unique`.
Additionally the `strict` parameter is turned on for `numpy.testing.assert_allclose` to ensure that the `dtype`-s and `shape`-s match, this fortunately does not introduce additional test failures. 
The [shape inference](https://github.com/onnx/onnx/blob/b50fb874f71325030d93dae4ae04a2647de7a30e/onnx/defs/tensor/defs.cc#L3371) defined for `Unique`, tells us the fact that the `inverse_indices` output should be 1d. This was not the case when the input was of length 1, since the `squeeze` made it a scalar. 
This mismatch between the reference implementation and `onnxruntime` was found by running the …
> Fix reference implementation for Unique

- .github/workflows/main.yml
- CMakeLists.txt
- requirements-lintrunner.txt
Update protobuf to 5.29.2, which is latest before protobuf 6.30.x, which has more breaking changes. The related changes to ONNX are some C++ cleanups.
Newer dependency.
> Bump Protobuf to 5.29.2

- .github/workflows/release_test_weekly_sdist.yml
Add missing pytest
https://github.com/onnx/onnx/actions/runs/12343589760/job/34527736304
```
Collecting numpy>=1.20 (from onnx-weekly)
Downloading numpy-2.2.0-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 83.0 MB/s eta 0:00:00
Collecting protobuf>=3.20.2 (from onnx-weekly)
Using cached protobuf-5.29.1-cp38-abi3-macosx_10_9_universal2.whl (417 kB)
Building wheels for collected packages: onnx-weekly
Building wheel for onnx-weekly (pyproject.toml): started
Building wheel for onnx-weekly (pyproject.toml): still running...
Building wheel for onnx-weekly (pyproject.toml): still running...
Building wheel for onnx-weekly (pyproject.toml): still running...
Building wheel for onnx-weekly (pyproject.toml): finished with status 'done'
Created wheel for …
```
> Install missing pytest; Update release_test_weekly_sdist.yml

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/quantization/defs.cc
- onnx/reference/ops/op_dequantize_linear.py
- onnx/reference/ops/op_quantize_linear.py
Allow the scale type in Q/DQ ops to be different from the high-precision type.
- For Q, an additional optional attribute `precision` is introduced to control the precision of the division operation. The default precision is `y_scale` type.
- For DQ, an additional optional attribute `output_dtype` is introduced. The default is to set the output type to `x_scale` type. The output type is also the precision of the multiplication operation. The user can always add a cast node after DQ to cast to another desired type.
A motivating example is when the high-precision data type of Q/DQ is fp16, sometimes it can be beneficial to have fp32 scale to preserve more precision. 
Another example is for [OCP’s MX-compliant formats](https://www.opencompute.org/documents/ocp-microscaling-formats-mx-v1-0-spec …
> Allow scale type in QuantizeLinear and DequantizeLinear to be different from the high-precision type

- CMakeLists.txt
- Expose cxx standard
CXX standard exposure is required to properly build against ONNX library.
Example of the issue https://github.com/microsoft/vcpkg/pull/42942#discussion_r1903814682
Generated target will have new property:
> Expose cxx standard

- onnx/test/helper_test.py
- onnx/test/numpy_helper_test.py
- requirements-dev.txt
- requirements-release.txt
Remove the use of struct and leverage ml_dtypes to clean up helper tests. This should unblock https://github.com/onnx/onnx/pull/6621
> Remove struct and leverage ml_dtypes in helper tests

- onnx/test/helper_test.py
The change in #6631 mistakenly removed a skip
> Fix the bfloat16 test in helper for min numpy version

- onnx/numpy_helper.py
- onnx/test/helper_test.py
Refactor `to_array` to simplify and fix conversion logic.
- The `_to_array` function was renamed back to `to_array`, consolidating with existing logic that leverages custom dtypes.
- Created an unpack_4bit helper to unpack packed 4bit dtype data, replacing usage of the 4bit->float32 conversion functions because the original logic was not actually needed.
- Removed test skips because bugs were fixed.
- Type casting functions for custom dtypes will be marked private in the next PR. Public versions of them will be scheduled for deprecation. (#6639) Users should use other libraries like ml_dtypes for efficient type conversion in numpy.
Fix https://github.com/onnx/onnx/issues/6604
> Fix numpy_helper to_array

- backend.py
- pyproject.toml
- setup.py
Instead of unconditionally pulling `cmake` PyPI package in, check whether `cmake` is available first and add the dependency only when it is not available.  This is the same approach as used by the `scikit-build-core` package, and it improves portability, especially given that CMake frequently requires downstream patching to work.
In this version of the patch, I've created a minimal PEP517 build backend that inherits the functions provided by setuptools, and adds the CMake dependency when necessary.  This avoids using deprecated setuptools `setup_requires` argument, and it avoids adding CMake dependency when building source distributions.
Same as #6642, except using PEP517 backend instead of deprecated `setup_requires`.
> Add cmake dependency only when system cmake is not available (backend version)

- onnx/common/interned_strings.h
In Clang 17+, literal operator declaration requires no space after `operator""`, otherwise a deprecation warning is generated.
> Fix literal operator in Clang17+

- docs/docsgen/source/api/helper.md
- docs/docsgen/source/api/numpy_helper.md
- onnx/helper.py
- onnx/numpy_helper.py
- onnx/subbyte.py
- onnx/test/helper_test.py
- requirements.txt
Deprecate all type casting functions because they are mere utilities or reference implementations that should not be directly exposed to users. Users should leverage libraries like `ml_dtypes` for type conversion.
- Additionally turned convert_endian and split_complex_to_pairs into private. This is seen as low risk.
- Added typing_extensions as a dependency. This is a common dependency used by python packages as a polyfill for the typing module.
> Deprecate all type casting functions

- docs/IR.md
This pull request includes changes to the `docs/IR.md` file to relax the strictness of identifier syntax rules. 
* Changed the requirement for names within a graph to adhere to C90 identifier syntax rules from "MUST" to "SHOULD". (`docs/IR.md`, [docs/IR.mdL262-R262](diffhunk://#diff-abcfc88a55144836fff2a055d73bc894201789bda5c0de98594e931037b5ec21L262-R262))
* Updated the requirement for dimension variable names to adhere to C90 identifier syntax rules from "MUST" to "SHOULD". (`docs/IR.md`, [docs/IR.mdL477-R477](diffhunk://#diff-abcfc88a55144836fff2a055d73bc894201789bda5c0de98594e931037b5ec21L477-R477))
The change was motivated by practicality.
1. Currently tools in the ecosystem does not assume adherence, and popular source of ONNX models like the PyTorch exporter does not produce models …
> Relax naming requirements in IR spec

- .github/workflows/create_release.yml
- .github/workflows/release_linux_x86_64.yml
- Remove the secrets that are no longer required in the reusable workflow (no more direct publishing there)
- Add toplevel permissions: Is "read" correct here?
- Hints found by: https://github.com/woodruffw/zizmor
> Remove unnecessary secrets in pipeline

- .github/workflows/auto_update_doc.yml
- .github/workflows/check_urls.yml
- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/pages.yml
- .github/workflows/pr_checks.yml
- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_sdist.yml
- .github/workflows/release_win.yml
- .github/workflows/reuse.yml
- .github/workflows/weekly_mac_ci.yml
- .github/workflows/win_no_exception_ci.yml
- Hardening checkout
- when credential is needed, it should be made explicit
https://woodruffw.github.io/zizmor/audits/#remediation
```
By default, using [actions/checkout](https://github.com/actions/checkout) causes a credential to be persisted in the checked-out repo's .git/config, so that subsequent git operations can be authenticated.
Subsequent steps may accidentally publicly persist .git/config, e.g. by including it in a publicly accessible artifact via [actions/upload-artifact](https://github.com/actions/upload-artifact).
However, even without this, persisting the credential in the .git/config is non-ideal unless actually needed.
```
> Hardening of checkout

- onnx/helper.py
- onnx/numpy_helper.py
- onnx/subbyte.py
Use DeprecationWarning instead of FutureWarning because it is more appropriate: https://docs.python.org/3/library/exceptions.html#DeprecationWarning
> Use DeprecationWarning

- requirements-dev.txt
remove twine from requirements dev list
Reduce number of dependency. We use the trusted publishing github action. Twine is no longer necessary for our CI.
> remove twine from requirements-dev-file

- onnx/defs/generator/defs.cc
- onnx/defs/generator/old.cc
- onnx/defs/shape_inference.cc
- onnx/defs/shape_inference.h
- onnx/test/shape_inference_test.py
I added a flag parameter in the `getShapeInput` function to check shape dims non-negative in some cases.
This PR is to solve the issue #6135. It proposes that the operator `ConstantOfShape` doesn't check input validation and may produce negative output.
I added a flag to the `getShapeInput` function. When it's true, the function will check the shape returned and fail if any aim is negative. This flag is enabled on `ConstantOfShape` operator.
(By the way, it's my first time contributing a PR to the open-source community. Please let me know if there is anything wrong with it. Thank you for your attention and review🙂
> Check the input of ConstantOfShape to be non-negative

- docs/docsgen/source/technical/float8.md
There was a typo in the doc. 'specifciations'-> specification
Typo is fixed
There was a slight typo in the docs/docsgen/source/technical/float8.md file
> TypoFix in float8.md

- docs/docsgen/source/intro/python.md
Fix a tensor type inaccuracy in the docs
It might be confusing to the reader why is suddenly an integer mention in the docs since it's not used in the example above. Furthermore, the float type has a value of 1.
> Fix a tensor type inaccuracy in the docs

- CMakeLists.txt
In building Pytorch or other packages,  it's sometimes desirable to avoid the influence of old protobuf from the build host and force linking to local build. A new option ONNX_BUILD_CUSTOM_PROTOBUF was added for this purpose.
> Add protobuf local build option

- .github/workflows/create_release.yml
the pipeline job "check_for_publish_preview_build_to_testpypi_weekly" should check if all condition for publishing to testpyi are met.
This must be done in a separate job, as a job with a github-environement first checks whether the authorizations for using the environment have been checked. 
Currently, the “check for publish” preview job does not yet check which branch is to be used. 
This has the following undesired behavior
> check_for_publish_preview_build_to_testpypi_weekly in CI should fail for PullRequests

- .github/workflows/main_freethreading.yml
add windows 3.13t build to main_freethreading.yml
> add windows 3.13t build to main_freethreading.yml (Updates of external dependencies now enable this)

- MANIFEST.in
Add `backend.py` to `MANIFEST.in`, so that it is included in source distribution archives.
Fixes #6751
> Include `backend.py` in source distribution

- INSTALL.md
Fix some errors because Protobuf minimum version is now 4.25.1.
Better documentation.
> Clarify minimum Protobuf version in  INSTALL.md

- .github/workflows/release_linux_aarch64.yml
- .github/workflows/release_linux_x86_64.yml
- .github/workflows/release_mac.yml
- .github/workflows/release_mac_freethreading.yml
- .github/workflows/release_sdist.yml
Since we do the checkout of the git submodules directly at the checkout without a separate step, it is no longer necessary to keep the credentials.
> chore(config): set persist credentials to false

- .github/workflows/release_mac.yml
remove unnecesssary builds (we build universal2 whl)
```
('onnx_weekly-1.18.0.dev20250310-cp310-cp310-macosx_12_0_universal2.whl
', with blake2_256 hash                                                
'9ec8a1663ea77a15b4094e62644795ebb7e75b9adc04df731782128c59302022').   
See https://pypi.org/help/#file-name-reuse for more                    
information.</title>                                                   
</head>                                                               
<body>                                                                
<h1>400 File already exists                                          
('onnx_weekly-1.18.0.dev20250310-cp310-cp310-macosx_12_0_universal2.whl
', with blake2_256 hash …
```
> fix: dont' push wheels with the same filename to pypi twice

- .github/dependabot.yml
> Remove dependabot configs for dockerfiles

- requirements.txt
> Bump minimum numpy to 1.22

- .github/workflows/auto_update_doc.yml
Pulling commit using HEAD_SHA instead of HEAD_REF. 
This reduces the risk of Github Actions TOCTOU attack described here https://github.com/AdnaneKhan/ActionsTOCTOU
Ref #6736
> use HEAD_SHA instead of HEAD_REF in auto_update_doc.yml

- .github/workflows/main.yml
- .github/workflows/main_freethreading.yml
- CMakeLists.txt
- cmake/ProtoBufPatch.cmake
Try to integrate Protobuf C++ 6.30.1 since the Protobuf installed from pip is now in 6.30 
Better support of Protobuf.
> Bump protobuf to v30.1

- onnx/helper.py
Deprecate printable_graph because it is not catching up with the latest of onnx. Recommend users to use `onnx.printer.to_text` instead.
This PR also makes `create_op_set_id_version_map` private because it is intended as a private function.
> Deprecate printable_graph in helper

- .github/workflows/main.yml
- .github/workflows/main_freethreading.yml
- CMakeLists.txt
The main purpose is to remove the patch command.
Better tooling.
> Bump protobuf to v30.2

- onnx/py.typed
- pyproject.toml
py.typed is a marker file to support typing. See [pep 561](https://peps.python.org/pep-0561/). It's used to indicate that ONNX has typing support in the source code and tools such as mypy and pylint can take advantage of that. Therefore, we don't need an additional pyi file for typing.
Better code.
> Improve pyproject.toml and add py.typed

- onnx/common/ir_pb_converter.cc
- onnx/common/tensor.h
- onnx/test/version_converter_test.py
There is currently a bug in the convert.cc::conver_version() function for models with external data. This function calls ir_pb_converter.cc::ImportModelProto(), which calls ir_pb_converter.cc::graphProtoToGraph(), which calls ir_pb_converter.cc::tensorProtoToTensor(). But tensorProtoToTensor() doesn't handle external data. While TensorProto has external data support, the struct in tensor.h::Tensor does not. The version converter works on a Graph and not a GraphProto, so the conversion to Tensor struct destroys the external data references. This PR adds the missing logic for external data.
The change can be verified on a simple model with external data:
```
import onnx_graphsurgeon as gs
import onnx
import numpy as np
dtype = np.float32
X = gs.Variable(name="X", dtype=dtype, shape=(1,1))
Y …
```
> Fix external data bug in version converter

- requirements-release.txt
Remove ipython, twine from requirements*.txt #6874
twine is not used in the pipelines any more (trusted publishing is used)
ipython is an indirect dependency of nbval (only necessary for testing)
> Remove ipython, twine from requirements*.txt

- cmake/ONNXConfig.cmake.in
This uses the CMake configuration file mechanism to configure protobuf. 
This is needed to correctly account for the dependency on abseil of the recent versions of protobuf.
Moreover this has the side effect that the generated file is actually relocatable fine if we happen to build in one folder and deploy in another.
> Use CONFIG to find protobuf

- .clang-tidy
> Remove outdated comments in clang-tidy config

- .github/workflows/preview_source_dist_test.yml
- .github/workflows/release_win_freethreading.yml
- CONTRIBUTING.md
- README.md
- pyproject.toml
- requirements-dev.txt
- requirements-release.txt
- requirements-release_test.txt
Replaces #6896. onnx should not need nbval, jupyter... notebook should be turned into examples.
> Remove nbval dependency, replaces #6896

- .github/workflows/create_release.yml
When the display is small, e.g. on a smartphone, the full name cannot be read in the actions overview => therefore reducing the length of the names
> reduce length of names in create_release.yml

- .github/workflows/create_release.yml
- .github/workflows/release_win_arm64.yml
- requirements-release_build.txt
This pull request introduces support for building wheels for the Windows ARM64 platform.
This change is necessary to expand platform compatibility and ensure ONNX can run on ARM64-based Windows systems. It resolves issues related to missing support for this architecture.
> Add wheel build for windows arm64

- onnx/defs/schema.h
- onnx/shape_inference/implementation.h
Cherry pick changes for 1.18.0. Private symbols were exposed before https://github.com/onnx/onnx/pull/6393. Although these symbols are now hidden, there are some of them already used in PyTorch. For backward compatibility, we have to expose them. 
Better API compatibility.
> Export symbols used by PyTorch

- CMakeLists.txt
To deal with the Windows build failures in https://github.com/pytorch/pytorch/pull/151694. CMake targets can properly deal with the quotation of Windows paths. 
Fix build errors
> Use Python3::Interpreter instead of Python3_EXECUTABLE

- .github/workflows/manylinux/entrypoint.sh
This pull request makes updates to the `.github/workflows/manylinux/entrypoint.sh` script to streamline the installation of Python dependencies and ensure consistent behavior across Python versions. The most significant changes include removing redundant conditional logic and consolidating the installation of `requirements-release_build.txt`.
* Removed the conditional block for handling Python version `3.13t` and consolidated the installation of `requirements-release_build.txt` for all Python versions. This simplifies the script and ensures consistent behavior.
> Use requirements-release_build in entrypoint.sh

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
Clarify the `axes` input of [un]Squeeze to be 1D tensors.
Reduce ambiguity of the op spec.
Fixes https://github.com/onnx/onnx/issues/6886
> Clarify the `axes` input of [un]Squeeze to be 1D tensors

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/cast.py
This small PR evaluates and displays the `from` and `to` types in the error messages.
> Display types on cast node test errors

- CMakeLists.txt
The `export(EXPORT` is not required and causes errors when ONNX is used as a third-party library.
Better code.
> Fix CMake EXPORT

- .github/workflows/stale.yml
Update the workflow so that we can use `no-stale` to keep an issue or PR open. Additionally it will not close any bugs or milestone issues.
> Update stale workflow to not close issues that should stay open

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/math/defs.cc
Improve description of the `Mod` operator. Closes #5564
The description of the `Mod` operator has been very vague. The proposed change aligns with the behavior of onnxruntime and the onnx reference implementation.
<details>
<summary>Test against onnxruntime and onnx reference implementation</summary>
The following code snippet checks the existing behavior of onnxruntime and the onnx reference implementation. This is not a stable feature of spox, yet, thus the private imports.
Execute using pixi
```
pixi exec -s onnxruntime -s onnx -s spox -s numpy python mod.py 
```
or in any Python environment with onnx, onnxruntime and spox installed.
```python
import math
import spox
import spox._future
import spox.opset.ai.onnx.v21 as op
import numpy as np
BACKENDS = …
```
> Clarify Mod operator

- CMakeLists.txt
Reduce the amount of CMake code. Generated headers are not required for added to ``onnx_proto`` because proper include directories have been set. `add_custom_target` is used for more explicit dependency specification. Other unnecessary code has been removed due to improvements in the overall code quality.
Better tooling.
> Simplify proto source file generation

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/nn/defs.cc
The docs for the `ratio` input of the Dropout operator had two conflicting sentences, one implying the default is zero and the other stating it is 0.5. The [reference implementation](https://github.com/onnx/onnx/blob/27852b2883ff8e052bdd9a8677b179f1b806bdaf/onnx/backend/test/case/node/dropout.py#L14) and [ONNX Runtime](https://github.com/microsoft/onnxruntime/blob/494d356a641f1e4c646010dd9ed2fc2308b2cd0a/onnxruntime/core/providers/cpu/nn/dropout_op.h#L32) use 0.5, so take that as the correct value.
> Clarify default value for `ratio` input of Dropout operator

- .github/workflows/pixi-build.yml
- INSTALL.md
- REUSE.toml
- pixi.lock
- pixi.toml
This PR enables an easy, reproducible, and cross-platform (this PR ships linux-64 and osx-arm64 support, but Windows can be added, too) conda-forge-based developer environment using the [Pixi](https://pixi.sh/latest/) package manager. A CI workflow testing that onnx can be correctly built on MacOS arm64 and Linux x86-64 using recent and minimal dependencies is also included.
Sporadically contributing to onnx has been a pain point for me and my colleagues in the past. The issues are primarily centered on the following:
- No easily reproducible developer environment that is known to work (based on lock files). This means compatible (non-Python) dependencies such as protobuf, cmake, various linters, or compiler toolchains must be manually maintained and updated. 
- Required CMake flags and …
> Add Pixi development environment

- CMakeLists.txt
The `ONNX_VERIFY_PROTO3` code was incidentally removed in https://github.com/onnx/onnx/pull/6992. It's needed because the option is public.
> Restore ONNX_VERIFY_PROTO3

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
- onnx/defs/tensor/old.cc
Currect the float8 saturation behavior for Cast using table from the float8 technical documentation https://onnx.ai/onnx/technical/float8.html, since the behavior for +- Inf and NaN was not correctly specified.
Fixes https://github.com/onnx/onnx/issues/6220
> Update float8 table for the Cast op spec

- CMakeLists.txt
- requirements-release_test.txt
Fix #7082 for [CVE-2025-4565](https://www.cve.org/CVERecord?id=CVE-2025-4565)
Dependency management.
> Bump protobuf to 6.31.1

- docs/Changelog.md
- docs/Operators.md
- onnx/defs/tensor/defs.cc
Fix https://github.com/onnx/onnx/issues/6220 by updating Cast-24 and CastLike-24. Saturating casts should yield Max/-Max values. This is consistent with the Graphcore paper.
> Update the saturating behavior for E4M3FNUZ/E5M2FNUZ in Cast and CastLike

- .github/workflows/release_win_x86_64.yml
Switch pytest with upload artifact to the run
This allows downloading the wheels and offline testing, also when pytest fails
> Switch order of steps in  release_win_x86_64.yml

- onnx/reference/ops/op_hard_sigmoid.py
added cast of result to ``x.dtype`` which is necessary since the result needs to be of the same type as ``x`` regardless of the types of``alpha`` and ``beta``.
The problem arouse when testing onnx-reference via the https://github.com/cbourjau/onnx-tests tool.
> Fix return type of HardSigmoid in reference implementation

- onnx/reference/ops/op_hardmax.py
Hardmax threw an error when input had size 0, now it just returns the input if it has size 0.
> Fix hardmax reference implementation

- .github/workflows/stale.yml
"contributions welcome" issues should be kept open because they are expecting contributions.
> Make stale bot ignore "contributions welcome" issues

- .github/workflows/create_release.yml
A check or publishing to the official onnx-weekly should only be triggered by a manual "workflow dispatch" action.
Closes: https://github.com/onnx/onnx/issues/7185
@yuanyao-nv @justinchuby could be cherry picked for 1.19 (Functionally probably not necessary)
> Improve conditions in create_release.yml 

- onnx/reference/ops/op_softmax.py
When given an empty input, ``softmax`` should return an output of the same shape. Currently, an exception is raised by ``X.max`` in that case.
We came across this problem when testing the onnxruntime via [onnx-tests](https://github.com/cbourjau/onnx-tests).
> fixed handling of empty inputs for the softmax operator

- onnx/reference/ops/op_div.py
So far, the division operator in the reference implementation worked via ``np.divide``, which produces a float dtype when both inputs have an integer input dtype. the result was then cast back to integer dtype.
Now, integer division is put in place when both inputs are integers.
We came over this bug when testing the reference implementation vs. the onnxruntime in https://github.com/cbourjau/onnx-tests.
> Fix division for integer dtype in reference implementation

- onnx/__init__.py
- onnx/backend/test/case/node/__init__.py
- onnx/backend/test/runner/__init__.py
- onnx/backend/test/runner/item.py
- onnx/external_data_helper.py
- onnx/helper.py
- onnx/onnx_cpp2py_export/defs.pyi
- onnx/reference/ops/aionnxml/op_tree_ensemble.py
- onnx/reference/ops/op_resize.py
- onnx/serialization.py
- onnx/test/compose_test.py
- onnx/test/test_backend_reference.py
- onnx/tools/net_drawer.py
- pyproject.toml
Update target Python version to 3.10. The union typing has been simplified a lot.
Better typing
> Update required Python version to 3.10 and related fixes

- onnx/reference/ops/_op.py
- onnx/reference/ops/op_reduce_sum.py
Fix the `is_axes_empty` method to treat empty axis empty.
And as refactor, use this method in `ReduceSum_13`.
https://github.com/onnx/onnx/issues/7140
> Reference evaluator: treat empty axes as empty

- requirements.txt
Require ml_dtypes>=0.5.0 due to issues reported from https://github.com/onnx/onnx/issues/7249
> Require ml_dtypes>=0.5.0

- onnx/__init__.py
Override __repr__ for some proto classes to make it more efficient because. Prior to this change, calling repr on a big model proto would cause a costly serialization to run which dumps a lot of text. This change makes `repr(model_proto)` to return `'<onnx.onnx_ml_pb2.ModelProto object at 0x7572f254ada0>'`.
Users can still call `str()` model proto classes to obtain a prototext representation.
This also does not affect `print()` because print calls `str()`.
Fix https://github.com/onnx/onnx/issues/4738
> Override `__repr__` for some proto classes

- onnx/shape_inference.py
Import IR_VERSION separately (not from onnx) to avoid potential circular import situations.
> Clean up shape inference imports

- docs/Operators.md
- docs/TestCoverage.md
- onnx/backend/test/case/node/cast.py
- onnx/backend/test/case/node/castlike.py
- onnx/helper.py
- onnx/model_container.py
- onnx/numpy_helper.py
- onnx/test/checker_test.py
- onnx/test/helper_test.py
- onnx/test/test_external_data.py
- onnx/test/version_converter/automatic_upgrade_test.py
- onnx/test/version_converter_test.py
On big-endian machines, there are plenty of test fails due to missing/wrong byteswaps. I've created a couple of patches to fix those fails, in numpy_helper.py::from_array() and helper.py::make_tensor() and in various testcases.
Some of the fixed Testcases test_make_tensor_raw are also mentioned in the issue from 2024-07-14 created by tehbone:
[s390x test failures - test_make_tensor_raw #6181](https://github.com/onnx/onnx/issues/6181)
Especially the last commit "Adjust remaining tests which are using tobytes()." is not really required as all corresponding tests did not fail before. But it makes the tests more consistent as before.
In the end I'm down to 7 remaining fails:
```
7 failed, 5314 passed, 3660 skipped, 31 warnings
FAILED …
```
> Fix testsuite fails on s390x (big-endian)

- README.md
Removed Black code style badge from README as we use ruff instead.
> Remove Black code style badge
